import React,{useState,useEffect,useMemo} from 'react';
import {Play,Pause,RotateCcw,SkipForward,Lock} from 'lucide-react';
import {REQUESTS,PAGE_TOKENS,TOKENS_PER_PAGE,requestSharedPrefix,sharedPage} from './hicache-story';
import {deriveHiCacheEngineState,ENGINE_DEFAULTS} from './hicache-engine';
import {engineCopy,engineCode} from './hicache-engine-content';
import {nextVisualStep} from './hicache-playback';
import {hcCopy} from './hicache-content';
const copy={
 zh:{sequence:'请求 Token 序列',sharedPrefix:'与历史请求相同的前缀',newSuffix:'分叉后的后缀',tokenNote:'示意分词：每个词作为一个 Token，每 2 个 Token 一页；实际 tokenizer 的切分可能不同。相同单词只有前面的整个前缀也相同时，才能复用 KV。',title:'连续请求 · 一棵树，三层存储',intro:'从空缓存开始，四个请求依次进入。沿分叉找到共享前缀，再看同一页在哪里命中、怎样回到 GPU。点击请求可回放到它进入的时刻。',first:'建立历史',branch:'同前缀，换问题',pressure:'新分支挤出旧缓存',return:'回访旧问题并续写',queue:'请求队列',queued:'待进入',active:'处理中',complete:'已完成',root:'前缀根',tree:'逻辑索引 · 共享前缀只存一条路径',hint:'连线表示前缀延续；同一父节点的不同分支表示不同后缀。节点内各页可驻留在不同层。',idle:'等待第一个请求',arrive:'请求进入',match:'沿树匹配连续前缀',split:'在匹配边界拆分索引',query:'查询外部缓存',prefetch:'外部缓存 → DRAM',load:'DRAM → GPU',compute:'计算新页并插入树',release:'解除 GPU 引用',backup:'GPU → DRAM 备份',persist:'DRAM → 外部存储',evict:'容量已满 · 回收冷页',now:'当前操作',direct:'直接复用',host:'加载',storage:'预取后加载',miss:'重新计算',gpu:'GPU',selected:'追踪页',empty:'尚未建立缓存；播放后观察第一条路径生长。',note:'教学配置：2 Token / 页，1 MiB / 页；GPU 4 页、DRAM 5 页。及时备份、等待预取完成；预取阈值设为 1 页。按冷的无引用叶页回收，外部存储保留历史。本例为单实例串行流程，非性能基准。',saved:'本次可复用',work:'本次需计算',traffic:'累计跨层搬运',pages:'页',trace:'点击树节点或物理页，关联高亮各层副本；蓝 / 紫 / 绿分别对应 L1 / L2 / L3。',step:'步骤',plan:'匹配结果 · 沿请求顺序',unknown:'等待匹配',storageHint:'L3 徽标仅表示本次演示已确认的写入；再次取数仍需查询后端。'},
 en:{sequence:'Request token sequences',sharedPrefix:'Prefix shared with earlier requests',newSuffix:'Suffix after the branch',tokenNote:'Illustrative tokenization: one word per token, two tokens per page. Actual tokenizers may split differently. Matching words reuse KV only when their entire preceding prefix also matches.',title:'A request stream · one tree, three tiers',intro:'Four requests enter the same initially empty cache. Follow the branches to a shared prefix, then trace where each page hits and how it reaches the GPU. Click a request to replay its arrival.',first:'Build history',branch:'Shared prefix, new question',pressure:'New branch displaces old pages',return:'Revisit and extend',queue:'Request queue',queued:'Queued',active:'Running',complete:'Complete',root:'Prefix root',tree:'Logical index · one path per shared prefix',hint:'Edges extend a prefix; sibling branches hold different suffixes. Pages in one node can reside in different tiers.',idle:'Waiting for the first request',arrive:'Request arrives',match:'Match the continuous prefix',split:'Split the index at the match boundary',query:'Query external cache',prefetch:'External cache → DRAM',load:'DRAM → GPU',compute:'Compute a page and insert into tree',release:'Release GPU references',backup:'GPU → DRAM backup',persist:'DRAM → external storage',evict:'Capacity full · reclaim cold page',now:'Current operation',direct:'Reuse directly',host:'Load',storage:'Prefetch, then load',miss:'Compute',gpu:'GPU',selected:'Trace page',empty:'The cache is empty. Play to grow the first path.',note:'Teaching setup: 2 tokens / page, 1 MiB / page; GPU 4 pages, DRAM 5. Acknowledged write-through, wait-complete prefetch; prefetch threshold 1 page. Reclaim cold unreferenced leaf pages; external storage retains history. Single-instance serial illustration, not a benchmark.',saved:'Reusable this request',work:'Compute this request',traffic:'Total inter-tier traffic',pages:'pages',trace:'Select a tree node or physical page to highlight its copies. Blue / purple / green identify L1 / L2 / L3.',step:'Step',plan:'Match result · request order',unknown:'Awaiting match',storageHint:'L3 badges show writes confirmed in this demonstration. A subsequent fetch still queries the backend.'}
};
const tiers=['gpu','host','storage'];
function layoutTree(nodes){
 let leaf=0;const out=[];const heights=[];
 const visit=(n,depth)=>{const children=nodes.filter(c=>c.parent===n.id);const xs=children.map(c=>visit(c,depth+1));const x=xs.length?(xs[0]+xs.at(-1))/2:leaf++*202+12;const height=n.pages.length?16+n.pages.length*49:36;heights[depth]=Math.max(heights[depth]||0,height);out.push({...n,x,depth,height});return x;};
 visit(nodes[0],0);out.forEach(n=>{n.y=12+heights.slice(0,n.depth).reduce((sum,h)=>sum+h+34,0);});
 return{nodes:out,width:Math.max(340,leaf*202),height:Math.max(...out.map(n=>n.y+n.height))+20};
}
function EngineScene({lang,pool,selected,setSelected,options,settings}){
 const [step,setStep]=useState(0),[isPlaying,setPlaying]=useState(false);
 const m=useMemo(()=>deriveHiCacheEngineState(step,{...options,pool}),[step,options,pool]),t=k=>engineCopy[lang][k]||copy[lang][k]||hcCopy[lang][k];
 const graph=layoutTree(m.tree),request=REQUESTS[m.request];
 const reset=()=>{setPlaying(false);setStep(0);};
 const handleNextStep=()=>{setPlaying(false);setStep(s=>nextVisualStep(m.history,s));};
 const togglePlay=()=>{if(m.done)setStep(0);setPlaying(v=>!v);};
 useEffect(()=>{if(!isPlaying||m.done)return;const timer=setTimeout(()=>setStep(s=>nextVisualStep(m.history,s)),850);return()=>clearTimeout(timer);},[isPlaying,step,m.done,m.history]);
 const jump=n=>{setPlaying(false);setStep(n);};
 const related=m.tree.find(n=>n.pages.includes(selected))?.pages||[selected];
 const legacyOperationNote=m.kind==='evict'?(lang==='zh'?'只回收当前层的冷页槽位；已确认的下层副本与逻辑前缀仍然保留，活动请求引用的页不会被淘汰。':'Reclaim only this tier’s cold slot. Confirmed lower-tier copies and the logical prefix remain; active references prevent eviction.'):
 m.kind==='split'?(lang==='zh'?'在本次匹配结束处拆开压缩节点，共享前缀与旧后缀分开管理。只改变索引边界，不复制 KV，也不改变物理地址。':'Split the compressed node at this match boundary. The shared prefix and old suffix become separate nodes; KV data and physical addresses do not change.'):
 hcCopy[lang][`${m.kind==='prefetch'?'prefetchStage':m.kind}Note`];
 const operationNote=['allocate','queued','inflight'].includes(m.kind)?t('allocationNote'):m.kind==='chunk'?t('chunkNote'):m.kind==='consensus'?t('consensusNote'):m.kind==='quota_reject'?t('quotaNote'):engineCopy[lang][m.kind+'Note']||legacyOperationNote;
 return <section className="hc-workbench hc-story"><h2 data-section-anchor="radix-hicache">{t('title')}</h2><p>{t('intro')}</p>{settings}
 <div className="hc-sequences"><h3>{t('sequence')}</h3><div className="hc-sequence-scroll"><div className="hc-stream hc-token-stream" aria-label={t('queue')}>{REQUESTS.map((r,i)=>{const start=m.history.findIndex(e=>e.request===i&&e.kind==='arrive');const end=m.history.findIndex(e=>e.request===i&&e.kind==='complete');const shared=requestSharedPrefix(i);return <button key={r.name} className={step>=end?'passed':step>=start?'current':''} onClick={()=>jump(start)} aria-pressed={m.request===i&&step>0}><span className="hc-request-label"><b>0{i+1} · {t(r.name)}</b></span>{r.ids.map((id,index)=><span key={id} className={`hc-request-page ${index<shared?'shared':'suffix'} ${index===shared&&i>0?'branch-boundary':''} ${related.includes(id)?'linked':''}`}><span className="hc-word-pair">{PAGE_TOKENS[id].map((word,j)=><i key={j}>{word}</i>)}</span></span>)}<span className="hc-prefix-count" title={t('sharedPrefix')}>{shared*TOKENS_PER_PAGE} Token</span></button>;})}</div></div><small>{t('tokenNote')}</small></div>
 <div className="hc-play-row"><div><strong>{t(request.name)}</strong><progress value={step} max={m.limit} aria-label={t('step')}/></div><div className="chapter-playback hc-playback"><button onClick={reset} aria-label={t('reset')}><RotateCcw size={17}/></button><button onClick={togglePlay} aria-label={t(isPlaying&&!m.done?'pause':'play')}>{isPlaying&&!m.done?<Pause size={17}/>:<Play size={17}/>}</button><button onClick={handleNextStep} disabled={m.done} aria-label={t('next')}><SkipForward size={17}/></button></div></div>
 <div className="hc-story-canvas"><div className="hc-canvas-action" aria-live="polite"><strong>{t(m.kind)}{m.ids.length?` · ${m.ids.join(', ')}`:''}</strong><span>{t('readyPrefix')}: {m.readyPrefix} Token</span>{operationNote&&<details><summary>{t('runtime')}</summary><p>{operationNote}</p></details>}</div><div className="hc-story-tree"><h3>{t('tree')}</h3><small>{t('hint')}</small><div className="hc-graph-scroll"><div className="hc-graph" style={{width:graph.width,height:graph.height}}><svg width={graph.width} height={graph.height} aria-hidden="true">{graph.nodes.filter(n=>n.parent).map(n=>{const p=graph.nodes.find(p=>p.id===n.parent);return <path key={n.id} d={`M${p.x+90},${p.y+p.height} V${p.y+p.height+16} H${n.x+90} V${n.y}`} fill="none" stroke={n.pages.some(id=>request.ids.includes(id))&&step>0?'#6366f1':'#94a3b8'} strokeWidth="2.5"/>;})}</svg>{graph.nodes.map(n=><button key={n.id} className={`hc-graph-node ${n.pages.includes(selected)?'selected':''} ${n.pages.some(id=>m.ids.includes(id))?'active':''}`} style={{left:n.x,top:n.y,height:n.height}} onClick={()=>n.pages.length&&setSelected(n.pages[0])} aria-label={`${t('treeNode')} ${n.pages.join(' / ')||t('root')}`}>{!n.pages.length&&<strong>{t('root')}</strong>}{n.pages.map(id=><span className="hc-token-node-row" key={id}><span className={`hc-word-pair ${sharedPage(id)?'shared':'suffix'}`}>{PAGE_TOKENS[id].map((word,j)=><i key={j}>{word}</i>)}</span><span className="hc-residency"><b>{id}</b>{tiers.map((tier,i)=><i className={m.ready[tier].includes(id)?tier:'absent'} key={tier}>L{i+1}{m.ready[tier].includes(id)?'':' —'}</i>)}<small>G:{m.gpuRefs[id]||0} H:{m.hostRefs[id]||0}</small>{m.locked.includes(id)&&<Lock size={10}/>}</span></span>)}</button>)}</div></div>{m.tree.length===1&&<p>{t('empty')}</p>}<small>{t('storageHint')}</small></div>
 <div className="hc-story-pools">{tiers.map((tier,index)=><React.Fragment key={tier}><div className={`hc-tier ${tier}`}><div className="hc-tier-heading"><span><strong>{hcCopy[lang][`${tier}Tier`]}</strong><small>{hcCopy[lang][`${tier}Scope`]}</small></span><b>{m.pools[tier].filter(Boolean).length}/{m.capacity[tier]}</b></div><div className="hc-slots">{m.pools[tier].map((id,i)=>id?<button aria-label={`${tier} ${id}`} key={i} onClick={()=>setSelected(id)} className={`${related.includes(id)?'selected':''} ${m.ready[tier].includes(id)&&m.to===tier&&m.ids.includes(id)?'arrived':''}`}><strong title={PAGE_TOKENS[id].join(' ')}>{id}</strong><small>{['G','H','S'][index]}{i}</small>{!m.ready[tier].includes(id)&&<small className="hc-not-ready">{t('pending')}</small>}{tier==='gpu'&&m.locked.includes(id)&&<Lock size={10}/>}</button>:<span className="hc-slot-empty" key={i}>·</span>)}</div></div>{index<2&&<div className={`hc-transfer ${m.from&&m.to&&[m.from,m.to].includes(tier)&&[m.from,m.to].includes(tiers[index+1])?'moving':''}`}>{index===0?'L1 ⇄ L2':'L2 ⇄ L3'} · {m.from&&m.to&&[m.from,m.to].includes(tier)&&[m.from,m.to].includes(tiers[index+1])?`${t(m.kind)} · ${m.ids.join(', ')}`:hcCopy[lang][index===0?'load':'prefetchStage']}</div>}</React.Fragment>)}</div>
 <div className="hc-story-bottom"><div><h3>{t('plan')}</h3><div className="hc-route-strip">{request.ids.map(id=>{const route=m.routes.find(r=>r.id===id);return <button key={id} className={route?.source||''} onClick={()=>setSelected(id)}><b>{id}</b><span>{route?t(route.action==='fetch'?'storage':route.action==='compute'?'miss':route.action):t('unknown')}</span></button>;})}</div><div className="hc-story-metrics"><span>{t('plannedReuse')} ↑ <b>{m.routes.filter(r=>['direct','load','fetch'].includes(r.action)).length*TOKENS_PER_PAGE}</b> Token</span><span>{t('plannedCompute')} <b>{m.routes.filter(r=>r.action==='compute').length*TOKENS_PER_PAGE}</b> Token</span><span>{t('traffic')} ↑ <b>{m.traffic}</b> B</span></div></div><div className="hc-inspector" aria-live="polite"><h3>{t('selected')} · {PAGE_TOKENS[selected]?.join(' ')} · {selected}</h3><p>{tiers.filter(tier=>m.ready[tier].includes(selected)).map((tier,i)=>`${hcCopy[lang][`${tier}Tier`]} [${m.pools[tier].indexOf(selected)}]`).join(' / ')||t('notResident')}</p><small>{t('trace')}</small></div></div></div> <details className="hc-runtime-details"><summary>{t('runtime')}</summary><div className="hc-engine-state"><strong>{t('stateTitle')}</strong><span>{t('readyPrefix')}: {m.readyPrefix} Token</span>{m.transfer&&<span>{m.transfer.id} · {m.transfer.from} → {m.transfer.to} · {m.transfer.state==='ready'?t('ready'):m.transfer.state==='discarded'?t('prefetch_stop'):t('pending')}</span>}{m.reader&&<span>{t('reader')} · G:2</span>}{m.tail&&<span>{t('tail')}: {PAGE_TOKENS[m.tail.id][0]} · 1/2 · {t('unpublished')}</span>}{m.rankResult&&<span>Rank 0: {m.rankResult[0]} · Rank 1: {m.rankResult[1]} → {t('committed')}: {m.committed}</span>}<span>{t('candidate')} · GPU: {m.candidates.gpu.join(', ')||'—'} · DRAM: {m.candidates.host.join(', ')||'—'}</span>{engineCode[m.kind]&&<details><summary>{t('runtime')}</summary><pre>{engineCode[m.kind]}</pre></details>}</div></details>
<p>{t('unitNote')}</p>
 </section>;
}

export default function HiCacheStory({lang,pool,selected,setSelected}){
 const [options,setOptions]=useState({...ENGINE_DEFAULTS,concurrent:false});
 const t=k=>engineCopy[lang][k]||hcCopy[lang][k];
 const settings=<details className="hc-engine-settings" open><summary>{t('settings')}</summary><div className="hc-controls">{[
  ['prefetch','prefetchSetting',['wait_complete','timeout','best_effort']],
  ['write','writeSetting',['write_through','write_through_selective','write_back']],
  ['fault','faultSetting',['none','host_pressure','gpu_pressure','partial_read','rank_lag']],
 ].map(([key,label,values])=><label key={key}>{t(label)}<select value={options[key]} onChange={e=>setOptions({...options,[key]:e.target.value})}>{values.map(v=><option key={v} value={v}>{t(v)}</option>)}</select></label>)}</div></details>;
 return <EngineScene key={JSON.stringify({...options,pool})} {...{lang,pool,selected,setSelected,options,settings}}/>;
}










