export const i18n = {
  zh: {
    title: '量化与低精度推理', subtitle:'先看低精度表示与离线算法，再沿真实推理流程追踪权重加载、激活转换与 KV 读写。',
    precisionScope:'W = 权重，A = 激活；以 BF16 权重为起点，KV 与引擎路径独立配置',
    language:'Switch to English', langToggle:'EN', bf16:'W(BF16) / A(BF16)', fp16:'FP16', w4:'W(INT4) / A(BF16)', w8:'W(INT8) / A(INT8)', fp8:'W(FP8) / A(FP8)', fp4:'W(FP4) / A(BF16)', kv4:'FP4 · E2M1 / 16', kvExample:'查看 FP4 缓存配方实例', fp4Metadata:'FP4 配方：每 16 个值共享 1 B 的 E4M3 scale；INT4/INT8/FP8 权重仍按每 128 值一个 FP32 scale 估算。',
    overview:'量化改变了什么', overviewHint:'点选对象看作用位置；切换精度，比较同一模型配置的存储需求。',
    weights:'权重', activation:'激活', kv:'KV Cache', offline:'部署准备 · 请求前', online:'在线 · 请求执行时',
    weightWhere:'Attention 投影 / MLP 权重：可以离线量化，也可以加载时转换一次；请求中反复读取，不随每个 Token 重做校准。',
    activationWhere:'层输入：每次前向重新产生。在线量化不等于动态 scale；也能使用离线校准好的固定 scale。',
    kvWhere:'Attention 的 K/V：每步产生并写入缓存，后续 Token 继续读取。它的精度与权重独立。',
    architecture:'一层 Transformer · 只标量化对象', layer:'Attention → MLP', projection:'Q / K / V / O · Linear',
    batch:'Batch', context:'上下文长度', kvPrecision:'KV 精度', kv16:'BF16', kv8:'FP8 E4M3FN',
    baseline:'BF16 参照', configured:'当前配置', total:'权重 + KV', metadata:'缩放元数据',
    capacityNote:'容量示例：32 层，hidden 4096，MLP 11008，8 个 KV heads，head dim 128。只计投影/MLP 权重和已用 KV；不含 Embedding、Norm、临时工作区或缓存预分配。',
    metadataNote:'容量模型：权重每 128 值一个 FP32 scale；KV 每 Token、每 Head、K/V 各一个 FP32 scale。是明确的教学布局，不代表所有引擎默认配置。',
    activationSize:'单份层输入 · 非峰值显存', phase:'执行阶段', decode:'Decode', prefill:'Prefill',
    perToken:'理想复用下，每输入 Token 分摊的权重读取', performanceNote:'按权重仅读取一次的理想复用估算；Prefill 的多 Token / 较大 batch 可摊薄读取。不是实际带宽或速度预测。',
    numeric:'用更少的 bit 存权重', numericHint:'少的是存储位数，不是权重个数或数值大小。点击存储条中的权重，看它怎样编码和还原。',
    floatCompare:'位字段对照（不改变 BF16 原权重）', formatBF16:'BF16 · 当前权重格式', formatFP16:'FP16 · 格式对照', floatBasics:'二进制的科学计数法', floatExample:'简单例子', floatSelected:'当前权重', floatSource:'浮点编码参考',
    floatSign:'符号', floatExponent:'指数', floatFraction:'尾数',
    floatPositive:'0 表示正', floatNegative:'1 表示负', floatBias:'指数偏置', floatImplicit:'前导 1 不占存储位',
    floatBinaryHint:'指数控制量级，尾数控制精细程度；尾数从左到右的位权是',
    floatScaleBridge:'指数存在每个浮点数自己的 bit 里；量化 scale 则是额外存储、由整组编码共用的乘数。FP8 也可配外部 scale。',
    floatScope:'位字段显示所选格式；主实验原权重始终先按 BF16 舍入，再计算量化新增误差。',
    floatFormulaHint:'b 是符号位，E 是指数位读出的整数，F 是尾数位读出的整数。BF16 的指数偏置为 127，FP16 为 15；这里展示正规数，特殊值另有规则。',
    sourceFloat:'NVIDIA · 浮点数表示',
    storageQuestion:'同样 24 个权重，占多少空间？', storageAnswer:'蓝色存权重，黄色存还原用的 scale；两条使用同一字节比例。',
    storageBaselineAnswer:'当前不量化：每个权重仍占 16 bit，没有额外 scale，也不节省存储。',
    oneWeight:'权重', sameWeights:'个权重 · 每个 2 字节', storageWeight:'存储中的权重', scaleGroup:'共享 scale 组', weightCodes:'权重编码',
    storageSaved:'少占', storageLarger:'反而多占', storageUnchanged:'节省', storageIncludesMetadata:'已计入 scale / zero point 开销',
    reconstructionQuestion:'一个权重，怎样存、怎样用？', baselineBitBudget:'16 个 bit 的存储预算，非原值的二进制编码', noConversion:'不转换', usedForCompute:'计算时使用',
    scaleRuler:'scale：还原用的尺子', integerRuler:'把原值除以 scale、舍入为小整数；用时乘回来。舍入丢掉的信息不能恢复。',
    fp8Ruler:'先除以 scale，再取最近的 FP8 数值；用时乘回来。FP8 的刻度不均匀，不是整数编码。',
    weightDelta:'重建误差', packing4:'每个编码只用 4 bit；黄色 scale 由整组共用，不是每个权重一份。',
    onePackedByte:'打包后的 1 字节', twoCodes:'两个相邻权重的编码',
    packing8:'每个整数编码占 1 字节；负数按补码表示。scale 由整组共用。', packingFP8:'这里是实际 E4M3FN 编码：1 位符号、4 位指数、3 位尾数，共 1 字节。',
    groupQuestion:'为什么多个权重共用 scale？', groupAnswer:'下划线权重共用选中的黄色 scale。组越小，尺子越多、开销越大，但能适应局部范围。',
    sharedRulers:'份 scale', weightsPerRuler:'个权重共用当前尺子', matricesAndSettings:'查看完整权重、分组与舍入设置',
    inputExperiment:'误差实验：输入变大，会怎样？', inputExperimentHint:'输入特征就是这一层收到的各项数值，不是 Token 概率。这里只切换输入，权重编码不变。',
    inputMagnitudes:'柱高表示输入绝对值；下方保留正负号。两种样例使用同一比例。', inputFeature:'输入特征',
    weightContribution:'选中权重对输出的误差贡献', contributionHint:'权重误差乘以对应输入，才是它对该输出的影响。输入大，同样的权重误差就可能被放大。',
    activationErrorAlso:'当前 W8A8 还包含激活量化误差；这个输出的额外贡献：',
    inputSharedHint:'点击任意输入柱检查对应权重。此输入样例也用于下方算法与引擎；切换会重置它们的执行进度。', sourceQuantSchemes:'NVIDIA · 量化编码与 scale',
    group:'多少权重共用一个 scale', tensor:'整张矩阵 · 24 个一组', channel:'每一行 · 8 个一组', group4:'每行分 2 组 · 每组 4 个', group2:'每行分 4 组 · 每组 2 个',
    clip:'保留范围', scheme:'整数映射', symmetric:'对称', affine:'非对称', sample:'这一层的输入样例', ordinary:'各通道幅度接近', outliers:'第 3 通道特别大',
    rowMeaning:'一行权重生成一个输出值，这一行就是“输出通道”；8 列分别对应输入的 8 个特征。',
    inputMeaning:'激活就是这一层收到的输入数值。这里展示第一个样本的 8 个特征（输入通道）。',
    outlierMeaning:'框出的第 3 个特征特别大，这就是离群通道；它会放大对应权重误差对输出的影响。',
    ordinaryMeaning:'当前各输入特征幅度接近。切换样例不会改变原始权重，但会改变输出误差。',
    sharedScale:'底部连线标出的权重共用一个 scale', groupMembers:'本组权重数', groupTotal:'全矩阵分组数', groupMetadata:'分组元数据',
    scaleMeaning:'Scale 是把编码换回原数值的倍率；对整数网格，它也决定相邻重建值的间距。不是“量化效果强弱”。',
    clipMeaning:'保留范围越小，网格越密，但超出范围的值会被截断；观察重建值和误差怎样一起变化。',
    kvCountTitle:'先数 K/V 元素，再换算字节', kvLayers:'层数', kvBatch:'并发序列数', kvContext:'每条序列的已缓存 Token 数', kvHeads:'每层 KV 头数', kvHeadDim:'每个头的维度', kvBits:'每个 K/V 元素的位数', kvPair:'K 和 V 两份', kvPayload:'KV 数值数据', kvTotal:'KV 总容量',
    channelScaleMeaning:'下面每根柱对应输入的一列：把这一列输入除以柱上的系数，同时把对应的一列权重乘以它；量化前，层输出保持不变。',
    alphaMeaning:'迁移强度控制把多少激活峰值转移到权重侧；调大不代表误差一定更小。',
    original:'原始权重', restored:'重建权重', input:'输入激活', output:'层输出', reference:'原始输出',
    encoded:'编码值', originalValue:'原值', reconstructed:'重建值', error:'输出均方误差', weightError:'权重均方误差',
    selected:'选中权重', scale:'Scale', zero:'Zero point', bytes:'存储', payload:'数据',
    floatHint:'FP8 E4M3FN：刻度不均匀；接近零时更密。它不是 INT8 的均匀整数网格。',
    intHint:'对称示例使用 -7…7 / -127…127，最小负码留空；非对称使用无符号码并保存 zero point。不是某引擎的唯一编码约定。',
    baseHint:'原权重和输入先按 BF16 舍入；误差相对这份 BF16 参照计算。后续乘加使用 JavaScript 数值，不模拟 GPU 累加。',
    numericBoundary:'先将样例权重和输入舍入到 BF16，再测量新增的量化误差；不是模型准确率。每份 scale 按 FP32 计；相邻编码打包为示意布局，非引擎文件格式。小矩阵的元数据占比尤其高。',
    formulas:'公式与变量', formulaHint:'w 是原值，q 是低精度编码，s 是 scale，z 是 zero point；重建不能恢复被舍入或裁剪的信息。',
    algorithm:'离线：如何准备量化权重', algorithmHint:'共享上述输入与权重；单步执行高亮操作后更新矩阵。这里不训练模型，也不在每个 Token 上重复校准。',
    tileLoaded:'HBM → Tile：读取原存储格式', tileRestored:'Tile 内反量化：不写回整份高精度权重',
    rtn:'RTN', awq:'AWQ', gptq:'GPTQ', smooth:'SmoothQuant',
    rtnHint:'直接舍入基线：每个输出通道一个 scale，将权重直接映射到 INT4 刻度。',
    awqHint:'用校准激活找重要输入通道，搜索等价缩放，再做 INT4 权重量化。并非单独保留重要权重的原始精度。',
    gptqHint:'先算输入相关性；逐列量化，把当前列的误差补偿到还未量化的列。绿色边框表示已经固定的列。',
    smoothHint:'把难量化的激活峰值向权重侧迁移；缩放前后乘积相同，再量化权重与激活为 INT8。',
    algorithmScope:'本例 RTN / AWQ / GPTQ 使用 W(INT4) / A(BF16)；SmoothQuant 使用 W(INT8) / A(INT8)。此处比较机制，不跨位宽做算法质量排名。',
    algorithmBoundary:'小矩阵机制复现：AWQ 搜索 11 个指数、未实现完整裁剪搜索；GPTQ 固定列序、逐列补偿、1% 阻尼；SmoothQuant 展示缩放与逐行 INT8。不是原仓库全量复现，也非 checkpoint 实测。',
    alpha:'迁移强度 α', scaleChannels:'输入通道的缩放系数', compareOutput:'同一校准输入的输出误差',
    current:'当前步骤', final:'完成量化后', rtnReference:'RTN · W4A16 参照', calibration:'校准输入：12 个样本、8 个通道；画面显示第一个样本',
    calibrate:'读取校准输入', search:'搜索通道缩放', smoothScale:'迁移激活峰值', quantWeights:'映射低精度数值', pack:'打包部署产物', column:'量化并补偿列',
    packed:'已准备：量化权重、scales 与必要的图变换', notPacked:'准备中 · 还不能作为部署产物',
    runtime:'在线：低精度数据怎么运行', runtimeHint:'单步执行一个请求片段。高亮是下一项待执行操作；完成后才出现输出或缓存写入。',
    linearScene:'线性层', kvScene:'KV 读写', scaling:'在线数据的 scale 来源', dynamic:'当前输入动态计算', static:'离线校准后固定',
    scalingHint:'两种模式都会在运行时量化新数据。区别是此时是否重新计算 scale，而不是是否重新训练权重。',
    token:'输入 Token', nextToken:'下一个输入', runtimeSample:'后续输入逐渐放大，观察静态 scale 的范围是否仍够用。',
    runtimeBoundary:'这里使用共同权重的直接量化示例，不执行上方算法实验的部署产物。展示一种融合路径，非 GPU 性能仿真；Kernel、累加精度及 KV 布局取决于后端。阶段不按耗时比例绘制。',
    loadWeights:'HBM → 权重 Tile', dynamicScale:'计算当前激活 scale', staticScale:'读取校准 scale', quantActivation:'在线量化激活',
    unpack:'Tile 内解包 / 反量化', intGemm:'INT8 乘法 / INT32 累加', fp8Gemm:'FP8 乘法 / FP32 累加', fpGemm:'高精度矩阵乘法', writeOutput:'缩放 / 写回输出',
    produceKV:'生成当前 K/V', kvDynamic:'计算当前 K/V scale', kvStatic:'读取校准 K/V scale', quantKV:'在线编码 K/V', writeKV:'提交缓存槽', readKV:'读取历史与当前 K/V', attention:'缩放后参与 Attention',
    weightTraffic:'已读取权重与元数据', clipped:'超出表示范围的输入数', kvError:'K 样例重建均方误差', cache:'已提交 KV 槽', cacheEmpty:'还没有已提交的槽',
    cacheNote:'每槽展示一个 8 维 K 样例；V 采用相同布局计算容量。示例未模拟完整多头 Attention。只有提交步骤会增长槽数。',
    waiting:'尚未完成', done:'已完成', idle:'待开始', play:'播放', pause:'暂停', replay:'重播', next:'下一步', reset:'重置',
    code:'当前操作 · 简化伪代码', references:'演示边界与来源', sourceAWQ:'AWQ · 通道保护', sourceGPTQ:'GPTQ · 误差补偿', sourceSmooth:'SmoothQuant · 激活迁移', sourceTRT:'TensorRT · 低精度执行', sourceKV:'vLLM · KV 量化',
    boundary:'只讨论推理部署的训练后量化，不涵盖 QAT 或 QLoRA。量化通常有误差，不保证输出分布或生成 Token 与原模型完全一致；质量需要在真实模型与任务上评测。',
    loadWeightsInfo:'权重早已量化并驻留显存。现在读取一个 Tile 和它的缩放参数，不重新校准权重。',
    dynamicScaleInfo:'根据当前输入的最大绝对值计算 scale。本次输入变大，scale 也随之改变。',
    staticScaleInfo:'复用离线校准范围，省去当前范围统计；新输入超出范围时会发生饱和裁剪。',
    quantActivationInfo:'将本次激活编码为 INT8 / FP8；原始输入不会因为权重量化而自动变成低精度。',
    unpackInfo:'W4A16 路径在计算 Tile 内恢复权重后与高精度激活相乘，不向 HBM 写回一整份高精度权重。',
    intGemmInfo:'低精度输入做整数乘法，以 INT32 累加；结合权重和激活 scale 恢复输出尺度。',
    fp8GemmInfo:'示例采用 FP8 输入、FP32 累加的计算路径；FP8 是浮点格式，不是整数乘法。',
    fpGemmInfo:'使用高精度输入做乘法；W4A16 的压缩收益首先体现在权重存储与读取。',
    writeOutputInfo:'完成缩放并写回高精度输出；低精度输入不意味着输出一定也是低精度。',
    produceKVInfo:'当前 Token 前向产生新的 K/V；此时还没写入持久缓存。', kvDynamicInfo:'对新 K/V 分别计算 scale，随低精度数据一起保存。', kvStaticInfo:'读取校准得到的固定 K/V scale；数据仍是在本次前向中量化。',
    quantKVInfo:'编码当前 K/V，保留 scale 供后续读取使用，旧缓存槽不重新编码。', writeKVInfo:'将当前 Token 的 K/V 与 scale 一起提交到缓存，新槽此刻才可被读取。',
    readKVInfo:'读取已提交的 K/V 与对应 scale，历史槽仍保持原来的值。', attentionInfo:'在 Attention 内按 scale 使用缓存值；本画面仅追踪读回与重建，不伪造完整 Attention 输出。',
  },
  en: {
    floatCompare:'Bit-field comparison (BF16 source unchanged)', formatBF16:'BF16 · source format', formatFP16:'FP16 · format comparison', floatBasics:'Binary scientific notation', floatExample:'Simple example', floatSelected:'Selected weight', floatSource:'Floating-point encoding reference',
    floatSign:'Sign', floatExponent:'Exponent', floatFraction:'Fraction',
    floatPositive:'0 means positive', floatNegative:'1 means negative', floatBias:'Exponent bias', floatImplicit:'Leading 1 is implicit',
    floatBinaryHint:'Exponent sets magnitude; fraction sets precision. Fractional bit weights, left to right:',
    floatScaleBridge:'An exponent lives inside each float. A quantization scale is stored separately and shared by a group of codes. FP8 can use an external scale too.',
    floatScope:'Bit fields show the selected format; source weights are always rounded to BF16 before measuring additional quantization error.',
    floatFormulaHint:'b is the sign bit; E and F are integers read from the exponent and fraction fields. BF16 uses bias 127; FP16 uses 15. These examples are normal numbers; special values follow separate rules.',
    sourceFloat:'NVIDIA · Floating-point representation',
    title: 'Quantization & Low-Precision Inference', subtitle:'Explore low-precision representations and offline algorithms, then follow weight loading, activation conversion and KV access through inference.',
    precisionScope:'W = weights, A = activations; BF16 source weights. KV and engine paths are independently configured.',
    language:'切换到中文', langToggle:'中文', bf16:'W(BF16) / A(BF16)', fp16:'FP16', w4:'W(INT4) / A(BF16)', w8:'W(INT8) / A(INT8)', fp8:'W(FP8) / A(FP8)', fp4:'W(FP4) / A(BF16)', kv4:'FP4 · E2M1 / 16', kvExample:'Inspect FP4 cache recipe examples', fp4Metadata:'FP4 recipe: one 1 B E4M3 scale per 16 values; INT4/INT8/FP8 weights retain one FP32 scale per 128 values.',
    overview:'What does quantization change?', overviewHint:'Select an object to locate it. Compare storage for the same model configuration.',
    weights:'Weights', activation:'Activations', kv:'KV Cache', offline:'Preparation · before requests', online:'Online · during requests',
    weightWhere:'Attention / MLP weights can be quantized offline or converted once at load time, then reused by requests. No per-token recalibration.',
    activationWhere:'Layer inputs are produced on each forward pass. Online quantization may use either calibrated fixed scales or dynamically computed scales.',
    kvWhere:'Attention K/V are produced and cached each step, then read by later tokens. KV precision is independent of weight precision.',
    architecture:'One Transformer layer · quantization targets', layer:'Attention → MLP', projection:'Q / K / V / O · Linear',
    batch:'Batch', context:'Context length', kvPrecision:'KV precision', kv16:'BF16', kv8:'FP8 E4M3FN',
    baseline:'BF16 reference', configured:'Selected configuration', total:'Weights + KV', metadata:'Scale metadata',
    capacityNote:'Capacity fixture: 32 layers, hidden 4096, MLP 11008, 8 KV heads, head dim 128. Only projection/MLP weights and occupied KV; excludes embeddings, norms, workspace and cache preallocation.',
    metadataNote:'Capacity layout: one FP32 scale per 128 weights; one per token/head for each of K and V. An explicit teaching layout, not a universal engine default.',
    activationSize:'One layer input · not peak memory', phase:'Execution phase', decode:'Decode', prefill:'Prefill',
    perToken:'Weight bytes per input token under ideal reuse', performanceNote:'Assumes one weight read shared across the input tokens. Prefill / larger batches amortize traffic; this is not measured bandwidth or speed.',
    numeric:'Store weights with fewer bits', numericHint:'Fewer stored bits—not fewer weights or smaller magnitudes. Select a weight in the storage bars to inspect its code and reconstruction.',
    storageQuestion:'Same 24 weights. How many bytes?', storageAnswer:'Blue stores weights; yellow stores reconstruction scales. Both bars use the same byte scale.',
    storageBaselineAnswer:'No quantization: each weight still takes 16 bits, with no extra scales or storage savings.',
    oneWeight:'weight', sameWeights:'weights · 2 bytes each', storageWeight:'Stored weight', scaleGroup:'Shared scale group', weightCodes:'Weight codes',
    storageSaved:'Saved', storageLarger:'Larger by', storageUnchanged:'Saved', storageIncludesMetadata:'Includes scale / zero-point overhead',
    reconstructionQuestion:'One weight: stored and used', baselineBitBudget:'16-bit storage budget, not the original value’s binary encoding', noConversion:'No cast', usedForCompute:'Used in computation',
    scaleRuler:'Scale: the reconstruction ruler', integerRuler:'Divide by scale and round to a small integer; multiply back when used. Rounding loses information that cannot be restored.',
    fp8Ruler:'Divide by scale, then choose the nearest FP8 value; multiply back when used. FP8 levels are nonuniform, not integer codes.',
    weightDelta:'Reconstruction error', packing4:'4 bits per code. The yellow scale is shared by a group, not stored per weight.',
    onePackedByte:'One packed byte', twoCodes:'Two adjacent weight codes',
    packing8:'One byte per integer code; negative integers use two’s complement. A group shares its scale.', packingFP8:'Actual E4M3FN bits: 1 sign, 4 exponent and 3 mantissa bits, totaling one byte.',
    groupQuestion:'Why share a scale?', groupAnswer:'Underlined weights share the selected yellow scale. Smaller groups fit local ranges but need more scales.',
    sharedRulers:'scales', weightsPerRuler:'weights share this ruler', matricesAndSettings:'Full weights, groups & rounding settings',
    inputExperiment:'Error experiment: what if inputs grow?', inputExperimentHint:'Features are the values entering this layer, not token probabilities. This changes inputs, not the weight codes.',
    inputMagnitudes:'Height shows magnitude; values retain their signs. Both fixtures use the same scale.', inputFeature:'Input feature',
    weightContribution:'Selected weight’s output-error contribution', contributionHint:'Multiply the weight error by its matching input. A large input can amplify the same weight error.',
    activationErrorAlso:'W8A8 also quantizes activations. Extra contribution to this output:',
    inputSharedHint:'Select an input bar to inspect its matching weight. Changing this shared fixture resets the algorithm and engine progress below.', sourceQuantSchemes:'NVIDIA · quantization codes and scales',
    group:'Weights sharing one scale', tensor:'Whole matrix · 24 per group', channel:'Each row · 8 per group', group4:'2 groups per row · 4 each', group2:'4 groups per row · 2 each',
    clip:'Retained range', scheme:'Integer mapping', symmetric:'Symmetric', affine:'Asymmetric', sample:'Layer input example', ordinary:'Similar channel magnitudes', outliers:'Large 3rd channel',
    rowMeaning:'One weight row produces one output value: an output channel. The 8 columns match the 8 input features.',
    inputMeaning:'Activations are the values entering this layer. Here are the first sample’s 8 features (input channels).',
    outlierMeaning:'The outlined 3rd feature is unusually large: an outlier channel. It amplifies the output effect of errors in the corresponding weights.',
    ordinaryMeaning:'Input features have similar magnitudes. Switching the fixture changes output error, not the original weights.',
    sharedScale:'Underlined weights share one scale', groupMembers:'Weights in this group', groupTotal:'Groups in the matrix', groupMetadata:'Group metadata',
    scaleMeaning:'Scale multiplies a code back into the original units. For integers, it also sets the spacing between reconstructed values—not quantization “strength”.',
    clipMeaning:'A smaller retained range makes the grid finer but clips values outside it. Watch reconstruction and error change together.',
    kvCountTitle:'Count K/V elements, then convert to bytes', kvLayers:'Layers', kvBatch:'Concurrent sequences', kvContext:'Cached tokens per sequence', kvHeads:'KV heads per layer', kvHeadDim:'Dimensions per head', kvBits:'Bits per K/V element', kvPair:'Both K and V', kvPayload:'KV numeric payload', kvTotal:'Total KV storage',
    channelScaleMeaning:'Each bar maps to one input column: divide that input column by its coefficient and multiply the matching weight column by it. Before quantization, the layer output is unchanged.',
    alphaMeaning:'Migration strength controls how much of the activation peak moves to weights. Increasing it does not guarantee less error.',
    original:'Original weights', restored:'Reconstructed weights', input:'Input activations', output:'Layer output', reference:'Original output',
    encoded:'Encoded value', originalValue:'Original', reconstructed:'Reconstructed', error:'Output MSE', weightError:'Weight MSE',
    selected:'Selected weight', scale:'Scale', zero:'Zero point', bytes:'Storage', payload:'Payload',
    floatHint:'FP8 E4M3FN has nonuniform levels, denser near zero. It is not the uniform integer grid of INT8.',
    intHint:'Symmetric fixture uses -7…7 / -127…127, leaving the most-negative code unused. Asymmetric uses unsigned codes with a zero point. Not a universal backend convention.',
    baseHint:'Source weights and inputs are rounded to BF16. Error is measured against this BF16 reference; subsequent arithmetic uses JavaScript numbers, not GPU accumulation.',
    numericBoundary:'Sources are rounded to BF16 before measuring added quantization error; not model accuracy. Scales count as FP32; adjacent-code packing is illustrative, not an engine file format. Tiny matrices magnify metadata overhead.',
    formulas:'Equations & variables', formulaHint:'w: original value; q: encoded value; s: scale; z: zero point. Reconstruction cannot recover rounded or clipped information.',
    algorithm:'Offline: preparing quantized weights', algorithmHint:'Shared inputs and weights. Each step executes the highlighted operation and updates the matrices. No training or per-token recalibration.',
    tileLoaded:'HBM → tile: read stored representation', tileRestored:'Dequantize in tile: no full high-precision HBM copy',
    rtn:'RTN', awq:'AWQ', gptq:'GPTQ', smooth:'SmoothQuant',
    rtnHint:'Direct rounding baseline: one scale per output channel maps weights directly to INT4 levels.',
    awqHint:'Use calibration activations to identify important input channels, search equivalent scaling, then quantize weights to INT4. It does not selectively keep important weights at their original precision.',
    gptqHint:'Estimate input correlations, quantize columns, and compensate error in remaining columns. Green borders mark fixed columns.',
    smoothHint:'Migrate activation outliers toward weights. The rescaled product stays identical before quantizing both weights and activations to INT8.',
    algorithmScope:'Here RTN / AWQ / GPTQ use W(INT4) / A(BF16); SmoothQuant uses W(INT8) / A(INT8). A mechanism comparison, not an accuracy ranking across bit widths.',
    algorithmBoundary:'Toy mechanism reproduction: AWQ searches 11 exponents without full clipping search; GPTQ uses fixed order, sequential compensation and 1% damping; SmoothQuant uses rescaling and row-wise INT8. Not full repository reproduction or checkpoint measurements.',
    alpha:'Migration strength α', scaleChannels:'Scale per input channel', compareOutput:'Output error on the shared calibration inputs',
    current:'Current step', final:'After quantization', rtnReference:'RTN · W4A16 reference', calibration:'Calibration: 12 samples, 8 channels; canvas shows the first sample',
    calibrate:'Read calibration inputs', search:'Search channel scales', smoothScale:'Migrate activation outliers', quantWeights:'Map to low precision', pack:'Pack deployment artifact', column:'Quantize & compensate column',
    packed:'Ready: quantized weights, scales and required graph transforms', notPacked:'In preparation · not deployable yet',
    runtime:'Online: executing with low precision', runtimeHint:'Step through one request fragment. The highlight marks the next operation; outputs and cache writes appear only after execution.',
    linearScene:'Linear layer', kvScene:'KV read / write', scaling:'Scale source for online data', dynamic:'Computed from current input', static:'Fixed after calibration',
    scalingHint:'Both modes quantize new data at runtime. The difference is whether scales are recomputed, not whether weights are retrained.',
    token:'Input token', nextToken:'Next input', runtimeSample:'Later inputs are amplified: check whether fixed calibration scales still cover their range.',
    runtimeBoundary:'Uses direct quantization of the shared weights, not the artifact from the algorithm lab. One fused path, not GPU performance simulation. Kernels, accumulation and KV layout depend on backend. Stages are not proportional latency.',
    loadWeights:'HBM → weight tile', dynamicScale:'Compute activation scale', staticScale:'Read calibrated scale', quantActivation:'Quantize activations online',
    unpack:'Unpack / dequantize in tile', intGemm:'INT8 multiply / INT32 accumulate', fp8Gemm:'FP8 multiply / FP32 accumulate', fpGemm:'High-precision matmul', writeOutput:'Rescale / write output',
    produceKV:'Produce current K/V', kvDynamic:'Compute current K/V scales', kvStatic:'Read calibrated K/V scales', quantKV:'Encode K/V online', writeKV:'Commit cache slot', readKV:'Read past and current K/V', attention:'Use scaled values in Attention',
    weightTraffic:'Weight payload + metadata read', clipped:'Inputs outside representable range', kvError:'K reconstruction MSE', cache:'Committed KV slots', cacheEmpty:'No committed slots yet',
    cacheNote:'Each slot shows an 8-D K sample; V uses the same layout for capacity accounting. Not full multi-head Attention. Slots grow only on commit.',
    waiting:'Not finished', done:'Done', idle:'Ready', play:'Play', pause:'Pause', replay:'Replay', next:'Next step', reset:'Reset',
    code:'Current operation · illustrative pseudocode', references:'Scope & sources', sourceAWQ:'AWQ · channel protection', sourceGPTQ:'GPTQ · error compensation', sourceSmooth:'SmoothQuant · outlier migration', sourceTRT:'TensorRT · low-precision execution', sourceKV:'vLLM · KV quantization',
    boundary:'Inference-time post-training quantization only; no QAT or QLoRA. Quantization generally introduces error and does not guarantee identical distributions or generated tokens. Evaluate quality on real models and tasks.',
    loadWeightsInfo:'Quantized weights already reside in HBM. Read a tile and its scale metadata, without recalibrating weights.',
    dynamicScaleInfo:'Compute scale from the current input maximum magnitude. Larger current inputs change the scale.',
    staticScaleInfo:'Reuse calibrated ranges and skip current range statistics; out-of-range inputs saturate.',
    quantActivationInfo:'Encode this input as INT8 / FP8. Quantized weights do not automatically quantize activations.',
    unpackInfo:'W4A16 reconstructs weights inside the compute tile, without writing a full high-precision copy to HBM.',
    intGemmInfo:'Multiply integer inputs with INT32 accumulation, then apply weight and activation scales.',
    fp8GemmInfo:'This path uses FP8 inputs and FP32 accumulation. FP8 is floating point, not integer arithmetic.',
    fpGemmInfo:'Multiply high-precision inputs. W4A16 first saves on weight storage and traffic.',
    writeOutputInfo:'Rescale and write high-precision output. Low-precision inputs do not require low-precision outputs.',
    produceKVInfo:'The current forward pass produces new K/V. They have not been committed to persistent cache yet.', kvDynamicInfo:'Compute new K/V scales separately and store them with the encoded data.', kvStaticInfo:'Read calibrated fixed K/V scales; data is still quantized during this forward pass.',
    quantKVInfo:'Encode new K/V and retain scales for later reads. Old cache slots are not re-encoded.', writeKVInfo:'Commit current K/V and scales together. Only now does the slot become readable.',
    readKVInfo:'Read committed K/V with their matching scales. Historical slots retain their previous values.', attentionInfo:'Use scaled cache values in Attention. This canvas tracks reads and reconstruction, not a fabricated full Attention output.',
  },
};
export const FORMULAS = {
  bfloat16:String.raw`v=(-1)^b\left(1+\frac{F}{2^7}\right)2^{E-127}`,
  float16:String.raw`v=(-1)^b\left(1+\frac{F}{2^{10}}\right)2^{E-15}`,
  fp8:String.raw`q=\operatorname{cast}_{\mathrm{E4M3FN}}(\operatorname{clip}(w/s,-448,448)),\quad \hat w=sq`,
  quant:String.raw`q=\operatorname{clip}(\operatorname{round}(w/s)+z),\quad \hat w=s(q-z)`,
  equivalent:String.raw`Y=XW^\top=(XS^{-1})(WS)^\top`,
  error:String.raw`\mathrm{MSE}=\frac{1}{N}\sum_i (Y_i-\hat Y_i)^2`,
  kvElements:String.raw`N_{\mathrm{KV}}=2\cdot L\cdot B\cdot T\cdot H_{\mathrm{KV}}\cdot d_h`,
  kv:String.raw`M_{\mathrm{KV}}=N_{\mathrm{KV}}\cdot\frac{b_{\mathrm{KV}}}{8}+M_{\mathrm{scales}}`,
};
export const CODE = {
  calibrate:'X = collect_layer_inputs(calibration_data)\nreference = linear(X, W)',
  search:'scales = search_channel_scales(X, W)\nX_scaled, W_scaled = equivalent_rescale(X, W)',
  smoothScale:'scales = activation_max**alpha / weight_max**(1-alpha)\nX_scaled, W_scaled = equivalent_rescale(X, W)',
  quantWeights:'Q, scales = quantize_per_output_channel(W)\ncheck_output_error(X, Q, scales)',
  awqQuantize:'Q, quant_scales = quantize_int4(W_scaled)\ncheck_output_error(X_scaled, Q, quant_scales)',
  smoothQuantize:'W_q = quantize_int8(W_scaled)\nX_q = quantize_int8(X_scaled)  # evaluate online path\ncheck_output_error(X_q, W_q)',
  column:'q = round_to_grid(W[:, column])\nerror = W[:, column] - q\nW[:, remaining] -= compensated(error, input_correlations)',
  pack:'artifact = pack(quantized_weights, quant_scales)\nsave_for_inference(artifact, optional_graph_rescale)',
  loadWeights:'tile, weight_scale = hbm.load(packed_weights)', dynamicScale:'activation_scale = max_abs(input) / format_max', staticScale:'activation_scale = checkpoint.activation_scale',
  quantActivation:'input_q = encode(input, activation_scale)', unpack:'weight_tile = unpack_and_dequantize(tile, weight_scale)',
  intGemm:'acc_int32 = int8_matmul(input_q, weight_q)', fp8Gemm:'acc_fp32 = fp8_matmul(input_q, weight_q)', fpGemm:'acc = matmul(input_fp16, weight_tile)',
  writeOutput:'output = apply_scales_if_needed(acc)\nhbm.store(output)',
  produceKV:'k, v = project_current_token(hidden)', kvDynamic:'k_scale, v_scale = scales_from_current(k, v)', kvStatic:'k_scale, v_scale = checkpoint.kv_scales',
  quantKV:'k_q, v_q = encode(k, k_scale), encode(v, v_scale)', writeKV:'cache.commit(slot, k, v, optional_scales)', readKV:'k, v, scales = cache.read(committed_slots)', attention:'attention.consume(k, v, optional_scales)',
};
