import React, { useState } from 'react';
import { MathFormula } from '../linear-attention/MathFormula';
import { Card, Range, fmt } from './primitives';
import { deriveFP4Model, decodeFP4 } from './fp4-model';
import './fp4.css';
import './numeric.css';
import { i18n } from './content';
import { ArrowRight } from 'lucide-react';

const copy = {
  zh: {
    title:'FP4：一个 KV 记录怎样存下来', hint:'从整条记录下钻到分组、字节和数值。这里的两个对象在系统中共存；设置仅作用于本实验。',
    main:'主 KV · E2M1 + E4M3', index:'索引 K · MXFP4 / E8M0', channels:'通道', group:'分组', inspect:'查看记录', baseline:'BF16 参照', packed:'FP4 打包', payload:'数值载荷', scales:'分组 scale', saved:'存储减少', capacity:'同等缓存预算下的记录容量', read:'每次完整读取的逻辑字节也同幅减少；实际延迟取决于解包、内核与带宽，不能直接当作加速倍数。',
    peak:'通道 18 的幅度', fixture:'确定性示例数据，非模型权重。改变通道 18，观察同组数值的精度变化；点击任意分组和数值追踪编码。', input:'① 原值 → 共用 scale', bytes:'② 两个 4-bit 编码 → 一个字节', restore:'③ 读取 → 还原', selected:'选中通道', original:'原值', recovered:'还原值', error:'有符号误差', mse:'整条记录 MSE', max:'最大绝对误差', scale:'scale 编码', offset:'载荷字节偏移', low:'低半字节', high:'高半字节', bits:'符号 / 指数 / 尾数', rounding:'E2M1 不是整数：正值档位为 0、0.5、1、1.5、2、3、4、6；另有对应负值。就近取档，中点取偶数编码。',
    mainRule:'每 16 个数共用一个 E4M3 scale：最大绝对值除以 6，再舍入到 E4M3。scale 可能向下舍入，超出范围的数会被截到 ±6。', indexRule:'每 32 个数共用一个 E8M0 scale：最大绝对值除以 6，向上取 2 的幂。scale 更粗，分组也更大，需观察实际误差。',
    packing:'示意采用前一个通道在低半字节的顺序；载荷与 scale 分列展示，未计对齐和分配器开销。', scope:'这里计算一条压缩记录，不是每个原始 token 的全模型缓存。局部窗口不套用这套 FP4 配方；上下文上限还受其他缓存、激活和模型能力约束。', source:'实现依据与范围', evidence:'配方依据官方 inference/model.py 与 kernel.py。公开 Python 路径使用 inplace 量化再还原，并非实际分配这些紧凑字节；此处展示等价打包账本。跨层共享与历史压缩的总收益在后续章节解释。', model:'缓存调用位置', kernel:'量化与 scale 内核',
  },
  en: {
    title:'FP4: inside a KV record', hint:'Drill from a record into groups, bytes and values. These objects coexist in the system; controls affect only this experiment.',
    main:'Main KV · E2M1 + E4M3', index:'Indexer K · MXFP4 / E8M0', channels:'channels', group:'Group', inspect:'Inspect record', baseline:'BF16 reference', packed:'Packed FP4', payload:'Value payload', scales:'Group scales', saved:'Storage reduction', capacity:'Record capacity at the same cache budget', read:'A full record read uses proportionally fewer logical bytes. Latency also depends on unpacking, kernels and bandwidth; this is not a speedup measurement.',
    peak:'Channel 18 magnitude', fixture:'Deterministic fixture, not checkpoint values. Change channel 18 to see effects on its group; select any group and value to trace its encoding.', input:'① Input → shared scale', bytes:'② Two 4-bit codes → one byte', restore:'③ Read → reconstruct', selected:'Selected channel', original:'Input', recovered:'Reconstructed', error:'Signed error', mse:'Whole-record MSE', max:'Maximum absolute error', scale:'Scale encoding', offset:'Payload byte offset', low:'Low nibble', high:'High nibble', bits:'Sign / exponent / mantissa', rounding:'E2M1 is not an integer format: positive levels are 0, 0.5, 1, 1.5, 2, 3, 4, 6, plus signed counterparts. Round to nearest, ties to even code.',
    mainRule:'Each 16 values share an E4M3 scale: divide the maximum magnitude by 6, then round to E4M3. A downward-rounded scale can require clipping to ±6.', indexRule:'Each 32 values share an E8M0 scale: divide the maximum magnitude by 6, then round up to a power of two. Coarser scales and larger groups affect error.',
    packing:'Illustration puts the earlier channel in the low nibble. Payload and scales are shown separately, excluding alignment and allocator overhead.', scope:'This accounts for one compressed record, not whole-model bytes per original token. The local window does not use this FP4 recipe. Context capacity also depends on other caches, activations and model capability.', source:'Implementation evidence and scope', evidence:'Recipes follow official inference/model.py and kernel.py. The public Python path quantizes and dequantizes in place rather than allocating this packed cache; this view is an equivalent packed byte budget. Cross-layer sharing and history compression are covered separately.', model:'Cache call sites', kernel:'Quantization and scale kernel',
  },
};
const generic = {
  zh: {storageQuestion:'同样 32 个权重，占多少空间？', sign:'符号 · 1 bit', exponent:'指数 · 2 bit', mantissa:'尾数 · 1 bit', title:'用更少的 bit 存权重 · FP4', hint:'FP4 是浮点格式，不等于 INT4。本例用 32 个数说明 E2M1 编码；每 16 个数共享一个 E4M3 scale，与上方容量估算采用同一配方。', capacity:'同等存储预算下的数值容量', read:'数值和 scale 一起占空间。更少的存储与读取字节不等于同倍数的内核加速。', scope:'通用 E2M1 分组量化示例，不代表特定硬件的完整 NVFP4 配方。权重 FP4、激活 16 位；KV 精度由 01 区域独立选择。', evidence:'E2M1 编码本身是通用数值格式。此例选用每 16 个数共享 E4M3 scale 来演示分组量化；具体缓存实现可在 01 的 KV 对象中查看。链接展示该配方的一种实际使用，不代表所有 FP4 都采用相同配方。'},
  en: {storageQuestion:'Same 32 weights: how much storage?', sign:'Sign · 1 bit', exponent:'Exponent · 2 bits', mantissa:'Mantissa · 1 bit', title:'Fewer bits for weights · FP4', hint:'FP4 is floating point, not INT4. This 32-value example uses E2M1 and one E4M3 scale per 16 values, matching the capacity recipe above.', capacity:'Value capacity at the same storage budget', read:'Both values and scales consume storage. Fewer stored or read bytes do not imply the same kernel speedup.', scope:'A generic grouped E2M1 example, not a complete hardware NVFP4 recipe. Weights use FP4 and activations use 16 bits; KV precision is independent in section 01.', evidence:'E2M1 is a general numeric format. This example uses one E4M3 scale per 16 values to demonstrate grouped quantization. Inspect a concrete cache use through the KV object in section 01. Linked code is one application of this recipe, not a requirement for all FP4 formats.'},
};
const hex = n => n.toString(16).padStart(2,'0').toUpperCase();
function FP4Numeric({m, setSelected, setPeak, t, lang}) {
  const n = key => i18n[lang][key], b=m.block, code=b.codes[m.local];
  const fields=[String(code>>3), ((code>>1)&3).toString(2).padStart(2,'0'), String(code&1)];
  const levels=[-6,-4,-3,-2,-1.5,-1,-.5,0,.5,1,1.5,2,3,4,6].map(v=>v*b.scale);
  const bound=Math.max(...levels.map(Math.abs),Math.abs(b.input[m.local]))*1.1;
  const pos=v=>`${50+v/bound*46}%`;
  return <Card number="02" id="quant-numeric-fp4" title="numeric" hint="numericHint" t={n}>
    <div className="qn-main"><div className="qn-storage"><h3>{t('storageQuestion')}</h3><p>{n('storageAnswer')}</p>
      {[false,true].map(low=><div className="qn-storage-row" key={String(low)}><div className="qn-label"><strong>{t(low?'packed':'baseline')}</strong><span>{low?m.total:m.baseline} B</span></div><div className="qn-byte-track"><div className={`qn-weight-payload ${low?'low':''}`} style={{width:`${(low?m.payload:m.baseline)/m.baseline*100}%`}}>{m.values.map((v,i)=><button key={i} aria-label={`${t('selected')} ${i+1} ${t(low?'packed':'baseline')}`} aria-pressed={m.selected===i} className={`${m.selected===i?'selected':''} ${Math.floor(i/m.group)===m.groupIndex?'in-group':''}`} onClick={()=>setSelected(i)}/>)}</div>{low&&<div className="qn-scale-payload" style={{width:`${m.metadata/m.baseline*100}%`}}>{m.groups.map((g,i)=><button key={i} aria-label={`${t('group')} ${i+1}`} onClick={()=>setSelected(g.start)}/>)}</div>}</div><small>{m.channels} {t('channels')}{low&&<> · {t('scales')} {m.metadata} B</>}</small></div>)}
      <div className="qn-saving"><strong>{n('storageSaved')} {m.baseline-m.total} B</strong><span>{n('storageIncludesMetadata')}</span></div>
      <section className="qn-float"><h4>{t('bits')} · E2M1</h4><div className="qn-float-fields">{fields.map((f,i)=><div key={i} className={`qn-float-field field-${i}`}><small>{t(['sign','exponent','mantissa'][i])}</small><span className="qn-float-bits">{f.split('').map((v,j)=><i key={j}>{v}</i>)}</span></div>)}</div><p>{t('rounding')}</p></section>
    </div><div className="qn-reconstruction"><h3>{n('reconstructionQuestion')} <MathFormula>{`W_{${m.selected+1}}`}</MathFormula></h3>
      <div className="q-value-flow"><div><small>{t('original')}</small><strong>{fmt(b.input[m.local])}</strong><span className="qn-bit-budget">{Array.from({length:16},(_,i)=><i key={i}/>)}</span><small>16 bit</small></div><ArrowRight size={15}/><div><small>{n('encoded')}</small><strong>{decodeFP4(code)}</strong><span className="qn-binary">{code.toString(2).padStart(4,'0').split('').map((v,i)=><i key={i}>{v}</i>)}</span><small>4 bit</small></div><ArrowRight size={15}/><div><small>{t('recovered')}</small><strong>{fmt(b.restored[m.local])}</strong><small>{n('usedForCompute')}</small></div></div>
      <div className="qn-scale-equation"><span>{n('scaleRuler')}</span><MathFormula>{`${decodeFP4(code)}\\times${b.scale}=${b.restored[m.local]}`}</MathFormula></div>
      <div className="q-numberline" role="img" aria-label={`${t('original')} ${b.input[m.local]}, ${t('recovered')} ${b.restored[m.local]}`}><div className="q-axis"/>{levels.map((v,i)=><i key={i} style={{left:pos(v)}}/>)}<span className="q-original-dot" style={{left:pos(b.input[m.local])}}/><span className="q-restored-dot" style={{left:pos(b.restored[m.local])}}/><small className="q-axis-left">{fmt(-bound)}</small><small className="q-axis-right">{fmt(bound)}</small></div>
      <div className="q-legend"><span><i className="weights"/>{t('original')}</span><span><i className="kv"/>{t('recovered')}</span><span>{t('error')} {fmt(b.restored[m.local]-b.input[m.local])}</span></div>
      <div className="qn-packed-byte"><small>{n('onePackedByte')}</small><span>{b.codes.slice(Math.floor(m.local/2)*2,Math.floor(m.local/2)*2+2).map((c,i)=><span key={i} className={m.local%2===i?'selected':''}>{c.toString(2).padStart(4,'0').split('').map((v,j)=><i key={j}>{v}</i>)}</span>)}</span><small>0x{hex(b.packed[Math.floor(m.local/2)])}</small></div><small>{t('packing')}</small>
    </div></div>
    <div className="qn-group-experiment"><div><h3>{n('groupQuestion')}</h3><p>{t('mainRule')}</p></div><div className="qn-group-result"><strong>{m.groups.length} {t('scales')} · {m.metadata} B</strong><small>{t('group')} {m.groupIndex+1} · {m.group} {t('channels')} · {b.scale}</small></div></div>
    <details className="qn-detail"><summary>{n('matricesAndSettings')}</summary><div className="f4-values">{m.values.map((v,i)=><button key={i} aria-pressed={m.selected===i} aria-label={`${t('selected')} ${i+1}`} onClick={()=>setSelected(i)}><small>{i+1}</small>{fmt(v)}</button>)}</div></details>
    <details className="qn-detail"><summary>{t('peak')}</summary><Range label="peak" value={m.peak} min={0} max={24} step={.5} onChange={v=>{setPeak(v);setSelected(17);}} t={t}/><p>{t('fixture')}</p><div className="q-metrics"><div className="q-metric"><span>{t('mse')}</span><strong>{fmt(m.mse)}</strong></div><div className="q-metric"><span>{t('max')}</span><strong>{fmt(m.maxError)}</strong></div></div></details>
    <details><summary>{t('source')}</summary><p>{t('evidence')}</p><a className="qn-source" href="https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash/blob/517ef625df97ec57aadc91b67506a57c20fdc5bb/inference/kernel.py" target="_blank" rel="noreferrer">{t('kernel')} ↗</a></details><p className="q-footnote">{t('scope')}</p>
  </Card>;
}
export default function FP4CacheWorkbench({lang, example = false}) {
  const [kind,setKind] = useState('main'), [selected,setSelected] = useState(17), [peak,setPeak] = useState(6);
  const t = key => generic[lang][key] && !example ? generic[lang][key] : copy[lang][key], m = deriveFP4Model(example ? kind : 'main',selected,peak,!example), b = m.block, code = b.codes[m.local];
  const bits = code.toString(2).padStart(4,'0');
  if (!example) return <FP4Numeric m={m} setSelected={setSelected} setPeak={setPeak} t={t} lang={lang}/>;
  return <Card number={example ? "" : "02"} id={example ? "quant-fp4-example" : "quant-numeric-fp4"} title="title" hint="hint" t={t}>
    {example && <div className="f4-records" role="group" aria-label={t('inspect')}>{['main','index'].map(k => <button aria-pressed={kind===k} key={k} onClick={() => {setKind(k);setSelected(17);}}>{t(k)}</button>)}</div>}
    <div className="f4-budget"><div><strong>{m.channels} {t('channels')} · {m.groups.length} × {m.group}</strong>{[[t('baseline'),m.baseline,0],[t('packed'),m.payload,m.metadata]].map(([label,p,s]) => <div className="f4-budget-row" key={label}><span>{label}</span><div className="f4-track"><i style={{width:`${p/m.baseline*100}%`}}/><b style={{width:`${s/m.baseline*100}%`}}/></div><strong>{p+s} B</strong></div>)}<small>{t('payload')} {m.payload} B · {t('scales')} {m.metadata} B</small></div><div><strong>{t('saved')} {fmt((1-m.total/m.baseline)*100)}%</strong><p>{t('capacity')} {fmt(m.baseline/m.total)}×</p><small>{t('read')}</small></div></div>
    <div className="f4-experiment"><Range label="peak" min={0} max={24} step={.5} value={peak} onChange={v => {setPeak(v);setSelected(17);}} t={t}/><p>{t('fixture')}</p></div>
    <div className="f4-groups" aria-label={t('group')}>{m.groups.map((g,i) => <button key={i} aria-pressed={m.groupIndex===i} onClick={() => setSelected(g.start)}>{i+1}<small>{g.start+1}–{g.start+m.group}</small></button>)}</div>
    <div className="f4-canvas"><div className="f4-flow"><section><h3>{t('input')}</h3><p>{t('group')} {m.groupIndex+1} · {t('channels')} {b.start+1}–{b.start+m.group}</p><div className="f4-values">{b.input.map((v,i) => <button key={i} aria-label={`${t('selected')} ${b.start+i+1}`} aria-pressed={m.local===i} onClick={() => setSelected(b.start+i)}><small>{b.start+i+1}</small>{fmt(v)}</button>)}</div><MathFormula>{`s=${b.scale}`}</MathFormula></section>
      <section><h3>{t('bytes')}</h3><div className="f4-byte-grid">{b.packed.map((v,i) => <button key={i} aria-pressed={Math.floor(m.local/2)===i} onClick={() => setSelected(b.start+2*i)} aria-label={`${t('offset')} ${b.start/2+i}`}><small>+{b.start/2+i}</small>{hex(v)}</button>)}</div><p>{t('scale')}: <strong>0x{hex(b.scaleCode)}</strong> · {m.scaleFormat} · 1 B</p><small>{t('packing')}</small></section></div>
      <section className="f4-inspector"><h3>{t('restore')} · {t('selected')} {m.selected+1}</h3><div className="f4-bits"><strong>{bits[0]} | {bits.slice(1,3)} | {bits[3]}</strong><span>{t('bits')}</span></div><p>{t('offset')} {Math.floor(m.selected/2)} · {t(m.local%2?'high':'low')}</p><MathFormula block>{`\\hat{x}=\\operatorname{E2M1}(q)\\,s=${decodeFP4(code)}\\times${b.scale}=${b.restored[m.local]}`}</MathFormula><dl>{[['original',b.input[m.local]],['recovered',b.restored[m.local]],['error',b.restored[m.local]-b.input[m.local]],['mse',m.mse],['max',m.maxError]].map(([k,v]) => <div key={k}><dt>{t(k)}</dt><dd>{fmt(v)}</dd></div>)}</dl><p>{t(m.kind==='main'?'mainRule':'indexRule')}</p><small>{t('rounding')}</small></section></div>
    <p className="q-footnote">{t('scope')}</p><details><summary>{t('source')}</summary><p>{t('evidence')}</p>{['model','kernel'].map(k => <a key={k} className="f4-source" target="_blank" rel="noreferrer" href={`https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash/blob/517ef625df97ec57aadc91b67506a57c20fdc5bb/inference/${k}.py`}>{t(k)} ↗</a>)}</details>
  </Card>;
}
