import { flowI18n } from './flow-content.js';
export const engineI18n = {
  zh: {
    ...flowI18n.zh,
    sourceSGLangFP8: 'SGLang · FP8 加载与层执行', sourceSGLangKV: 'SGLang · FlashInfer 与 KV',
    engineKVPool: 'KV 地址池',
    engineReadSlots: '本轮读取地址',
    engineTitle: '量化在推理中如何生效',
    engineHint: '跟随同一份权重、每轮激活和持续增长的 KV，观察加载、Prefill 与 Decode。',
    engineScope: '源码基线 v0.4.6.post5 · SM90 / CUDA 12+ · 原生 sgl-kernel · 非 block FP8 · TP=1 · Llama / FlashInfer（无前缀 Prefill → paged Decode）',
    engineRaggedAttention: '新 K/V → Attention',
    engineAttentionPrefillInfo: '普通文本模型、无缓存前缀的 Prefill 使用 ragged 包装器：直接用本轮高精度 Q/K/V 做因果 Attention，然后才写入 KV 池。此时不读取尚未写入的缓存。',
    enginePreset: '部署路径', engineBF16: 'BF16 checkpoint → BF16 计算', 'load-fp8': 'BF16 checkpoint → 加载时 FP8',
    'saved-dynamic': 'FP8 checkpoint → 动态激活', 'saved-static': 'FP8 checkpoint → 静态激活',
    engineKV: 'KV 存储', auto: 'auto · BF16', 'fp8-unit': 'FP8 · 默认 scale=1', 'fp8-file': 'FP8 · 加载校准 scale',
    engineSetup: '启动一次', enginePrefill: 'Prefill · 4 个输入', engineDecode1: 'Decode · 第 1 次', engineDecode2: 'Decode · 第 2 次',
    engineConfigure: '配置与层绑定', engineLoad: '读取 checkpoint', enginePrepare: '权重后处理', enginePool: '预分配 KV 池',
    engineBatch: '批次与地址', engineActivation: '激活转 FP8', engineGemm: 'QKV 投影', engineWrite: '写入 KV', engineAttention: '读取 KV / Attention',
    engineSource: '对应源码', engineCode: '当前调用 · 参数已简化', engineConfigDetails: '启动参数与 checkpoint 字段',
    engineCommandNote: '命令为配置示例；请替换为兼容的真实 checkpoint 与 KV scale 文件。此网页不启动 SGLang，也不运行 GPU Kernel。',
    engineSavedFields: 'FP8 checkpoint 提供 weight、weight_scale；activation_scheme 决定静态或动态激活。静态模式还须提供 input_scale，不是额外编造一个启动参数。',
    engineLoadFields: 'BF16 checkpoint 不含 FP8 权重。--quantization fp8 选择 Fp8LinearMethod；加载后的权重转换完成一次，后续请求直接复用。',
    engineBaseFields: '未指定量化：线性层使用 UnquantizedLinearMethod。KV dtype 独立选择，不由权重精度自动决定。',
    engineArtifacts: '磁盘 → GPU 常驻', engineReady: '已就绪 · 后续复用', enginePending: '尚未加载', engineLoaded: '已读取 · 待后处理',
    engineWeightCalls: '本次启动 · 权重量化次数', engineActivationCalls: '已完成 · 激活量化调用',
    engineResident: '示例权重 + scale', engineAllocated: '已分配 / 已写入', engineUsable: '示例可用 KV 预算', engineWritten: '有效 KV 数据',
    enginePoolHint: '格子是可寻址的 slot；橙色只分配，绿色才有有效 KV。显存池先预分配，增长的是占用量，不是每步重新申请整个缓存。',
    engineFree: '空闲', engineReserved: '待写', engineWrittenSlot: '已写', engineSlot: '缓存地址', enginePoolPending: 'KV 池尚未创建',
    engineInput: '本轮层输入', engineCodes: '本轮 FP8 激活', engineWeightMatrix: 'GPU 权重布局', engineProjection: '本轮 Q / K / V',
    engineStored: '新写入的 KV 编码', engineAttentionOutput: 'Attention 输出', engineXScale: '激活 scale', engineKScale: '固定层 KV scale',
    engineClipped: '超出激活表示范围', engineMSE: 'QKV 投影均方误差', engineNextOperation: '下一项待执行', engineAllDone: '轨迹完成 · 不再推进',
    engineNoTensor: '执行对应操作后，数值才会出现在这里。', engineReused: '常驻权重保持不变', engineKVWarning: '默认 scale=1 不等于已经校准；源码对此发出质量警告。',
    engineConfigureInfo: '启动参数选择量化方法。LinearBase 绑定 Fp8LinearMethod 或未量化方法；不是在 Transformer 外面再加一个“量化模型”。',
    engineLoadInfo: '加载器创建模型参数并读入 checkpoint。已量化文件直接带来 FP8 权重与 scale；普通文件此时仍是 BF16 权重。',
    enginePrepareLoadInfo: '加载后按输出通道量化权重，并转置成算子布局。这个操作只做一次；观察后续 Prefill / Decode 时权重量化次数不会增加。',
    enginePrepareSavedInfo: '已有 FP8 数值不用重新运行 AWQ / GPTQ。此路径把 fused QKV 的各分片 scale 展开为通道 scale，并调整权重布局。',
    enginePrepareBaseInfo: '16 位基线不做 FP8 转换。矩阵乘法仍读取原始精度权重。',
    enginePoolInfo: 'ModelRunner 在权重加载后按剩余显存计算可用 Token 数并创建缓存池。相同 KV 数据预算下，FP8 slot 的数据占用减半，可容纳更多位置。',
    engineBatchPrefillInfo: '4 个新输入一起进入 forward_extend。ForwardBatch 携带位置和 out_cache_loc；分配 4 个地址，不把 Prefill 假装成四次 Decode。',
    engineBatchDecodeInfo: '同一请求本次只增加 1 个输入位置，进入 forward_decode；旧 KV 保留，只为新位置分配地址。',
    engineActivationDynamicInfo: '在 apply_fp8_linear 内，逐输入行计算 scale 并转 FP8。Prefill 有 4 个行 scale，Decode 有 1 个；权重不会因此重新量化。',
    engineActivationStaticInfo: '复用 checkpoint 中的 input_scale，但激活数值仍需每次转 FP8。后续输入被刻意放大，可观察固定范围下的裁剪与误差。',
    engineGemmInfo: '所选原生 FP8 分支调用 fp8_scaled_mm，读入低精度激活、常驻权重及两侧 scale，输出仍采用输入的高精度 dtype。这里只放大一层 QKV 投影。',
    engineGemmBaseInfo: '基线通过 F.linear 计算高精度 QKV。后面的 KV 存储精度仍由独立的 --kv-cache-dtype 决定。',
    engineWriteInfo: 'set_kv_buffer 在 out_cache_loc 指定的位置写 K/V。FP8 路径先除以层级固定 scale 再转换；不是为每个 Token 新算一个 KV scale。',
    engineAttentionInfo: 'Decode 先写当前 K/V，再由 FlashInfer paged 包装器读取全部已写前缀，并接收同一组 K/V scale。这里没有整池转回 BF16 的独立步骤。',
    engineBoundary: '数值模型：原始权重作微型 QKV 投影，1 个 head、每个 Q/K/V 仅 1 维；4 个 Prefill 输入与 2 次 Decode 输入均为固定样例，不是生成的 Token。省略 RoPE、其余层、采样、调度竞争与前缀复用；不是模型质量或耗时测量。',
    enginePoolBoundary: '24 B 仅为微型样例可用 KV 数据预算，排除哨兵 slot、地址表和 scale 元数据，不是整卡显存。加载时 FP8 的峰值也不能用常驻权重大小代替。',
    engineNumerics: '这里复用数值实验的 FP8 舍入模型；原权重和输入先舍入到 BF16，但不复现中间张量舍入、GPU 累加或实际 Kernel 的形状限制。上方容量估算的 per-token scale 布局不代表此 SGLang 固定层 scale 路径。',
    engineBridge: '算法回答“如何准备量化产物”，引擎还需要匹配的格式与算子。下方用同一份原始数据追踪 SGLang FP8，未把这里的微型 INT4 / INT8 产物冒充为可加载 checkpoint。',
    engineFormulaTitle: '算子里的 scale 如何作用', engineFormulaHint: '行 scale 对应本轮输入，通道 scale 对应常驻权重；KV scale 属于 Attention 层并跨 Decode 复用。',
  },
  en: {
    ...flowI18n.en,
    sourceSGLangFP8: 'SGLang · FP8 loading & layers', sourceSGLangKV: 'SGLang · FlashInfer & KV',
    engineKVPool: 'KV address pool',
    engineReadSlots: 'Addresses read this pass',
    engineTitle: 'How quantization enters inference',
    engineHint: 'Follow resident weights, fresh activations and a growing KV cache through loading, Prefill and Decode.',
    engineScope: 'Source baseline v0.4.6.post5 · SM90 / CUDA 12+ · native sgl-kernel · non-block FP8 · TP=1 · Llama / FlashInfer (no-prefix Prefill → paged Decode)',
    engineRaggedAttention: 'New K/V → attention',
    engineAttentionPrefillInfo: 'For a plain-text model with no cached prefix, ragged Prefill uses the current high-precision Q/K/V for causal attention, then writes the KV pool. It does not read an unwritten cache.',
    enginePreset: 'Deployment path', engineBF16: 'BF16 checkpoint → BF16 compute', 'load-fp8': 'BF16 checkpoint → FP8 at load',
    'saved-dynamic': 'FP8 checkpoint → dynamic activations', 'saved-static': 'FP8 checkpoint → static activations',
    engineKV: 'KV storage', auto: 'auto · BF16', 'fp8-unit': 'FP8 · default scale=1', 'fp8-file': 'FP8 · loaded calibrated scale',
    engineSetup: 'Startup · once', enginePrefill: 'Prefill · 4 inputs', engineDecode1: 'Decode · pass 1', engineDecode2: 'Decode · pass 2',
    engineConfigure: 'Bind layer method', engineLoad: 'Read checkpoint', enginePrepare: 'Process weights', enginePool: 'Preallocate KV pool',
    engineBatch: 'Batch & addresses', engineActivation: 'Cast activations', engineGemm: 'QKV projection', engineWrite: 'Write KV', engineAttention: 'Read KV / attention',
    engineSource: 'Source implementation', engineCode: 'Current call · arguments simplified', engineConfigDetails: 'Launch arguments & checkpoint fields',
    engineCommandNote: 'Configuration example: replace paths with a compatible checkpoint and KV scale file. This page does not launch SGLang or execute GPU kernels.',
    engineSavedFields: 'The FP8 checkpoint supplies weight and weight_scale. Its activation_scheme selects static or dynamic activation scaling. Static also requires input_scale; this is not an invented launch flag.',
    engineLoadFields: 'The BF16 checkpoint has no FP8 weights. --quantization fp8 selects Fp8LinearMethod; conversion runs once after loading, then requests reuse the result.',
    engineBaseFields: 'Without quantization, linear layers use UnquantizedLinearMethod. KV dtype is independent of weight precision.',
    engineArtifacts: 'Disk → GPU residency', engineReady: 'Ready · reused by later passes', enginePending: 'Not loaded', engineLoaded: 'Loaded · awaiting processing',
    engineWeightCalls: 'Weight quantizations at startup', engineActivationCalls: 'Completed activation quantization calls',
    engineResident: 'Example weights + scales', engineAllocated: 'Allocated / written', engineUsable: 'Usable example KV budget', engineWritten: 'Valid KV payload',
    enginePoolHint: 'Each cell is an addressable slot. Amber is reserved; green has valid KV. The pool is preallocated; occupancy grows, not a newly allocated full cache each step.',
    engineFree: 'Free', engineReserved: 'Reserved', engineWrittenSlot: 'Written', engineSlot: 'Cache address', enginePoolPending: 'KV pool not created yet',
    engineInput: 'Current layer input', engineCodes: 'Current FP8 activations', engineWeightMatrix: 'GPU weight layout', engineProjection: 'Current Q / K / V',
    engineStored: 'Newly written KV codes', engineAttentionOutput: 'Attention output', engineXScale: 'Activation scale', engineKScale: 'Fixed layer KV scale',
    engineClipped: 'Activations outside range', engineMSE: 'QKV projection MSE', engineNextOperation: 'Next operation', engineAllDone: 'Trace complete · stopped',
    engineNoTensor: 'Values appear only after the corresponding operation finishes.', engineReused: 'Resident weights unchanged', engineKVWarning: 'Default scale=1 is not calibration; this version warns about possible quality loss.',
    engineConfigureInfo: 'Launch arguments select the quantization method. LinearBase binds Fp8LinearMethod or the unquantized method; there is no separate “quantization model” outside the Transformer.',
    engineLoadInfo: 'The loader creates parameters and reads the checkpoint. Serialized FP8 brings weights and scales; an ordinary checkpoint still contains BF16 weights at this point.',
    enginePrepareLoadInfo: 'After loading, weights are quantized per output channel and transposed for the kernel. This runs once: the weight conversion counter stays unchanged during Prefill and Decode.',
    enginePrepareSavedInfo: 'Existing FP8 values do not rerun AWQ or GPTQ. This path expands fused-QKV shard scales to channel scales and adjusts the weight layout.',
    enginePrepareBaseInfo: 'The 16-bit baseline performs no FP8 conversion. Matrix multiplication keeps the original-precision weights.',
    enginePoolInfo: 'After loading weights, ModelRunner derives token capacity from remaining memory and creates the cache pool. With the same KV payload budget, FP8 halves the slot payload and fits more positions.',
    engineBatchPrefillInfo: 'Four new inputs enter forward_extend together. ForwardBatch carries positions and out_cache_loc; four addresses are allocated, not four fake Decode passes.',
    engineBatchDecodeInfo: 'This request adds one input position via forward_decode. Old KV stays in place; only the new position needs an address.',
    engineActivationDynamicInfo: 'Inside apply_fp8_linear, scale is computed per input row before casting to FP8. Prefill has four row scales, Decode one. Weights are not requantized.',
    engineActivationStaticInfo: 'Reuse input_scale from the checkpoint, but cast activation values on every forward pass. Later inputs are deliberately amplified to expose clipping and error under a fixed range.',
    engineGemmInfo: 'The selected native FP8 branch calls fp8_scaled_mm with low-precision activations, resident weights and both scales. Output uses the original input dtype. We inspect one QKV projection.',
    engineGemmBaseInfo: 'The baseline computes high-precision QKV via F.linear. Subsequent KV storage still follows the independent --kv-cache-dtype setting.',
    engineWriteInfo: 'set_kv_buffer writes K/V at out_cache_loc. FP8 divides by fixed layer scales before casting; it does not derive a new KV scale for every token.',
    engineAttentionInfo: 'Decode writes current K/V first, then the paged FlashInfer wrapper reads the full written prefix with the same K/V scales. No separate full-pool BF16 conversion is modeled.',
    engineBoundary: 'Numerical model: the original matrix is a tiny QKV projection, one head with one dimension per Q/K/V. Four Prefill inputs and two Decode inputs are fixed fixtures, not generated tokens. RoPE, other layers, sampling, scheduling contention and prefix reuse are omitted. Not a quality or timing benchmark.',
    enginePoolBoundary: '24 B is only the usable toy KV payload budget, excluding the sentinel slot, address tables and scale metadata—not full GPU memory. Resident weight size also does not describe load-time peak memory.',
    engineNumerics: 'Source weights and inputs are rounded to BF16 before the numerical FP8 model; intermediate tensor rounding, GPU accumulation and actual kernel shape constraints are not reproduced. The capacity overview’s per-token scale layout is not this SGLang fixed-layer-scale path.',
    engineBridge: 'Algorithms prepare quantized artifacts; engines also require matching formats and kernels. Below, the same original data follows SGLang FP8—not a claim that these miniature INT4 / INT8 artifacts are loadable checkpoints.',
    engineFormulaTitle: 'How scales enter the kernel', engineFormulaHint: 'Row scales belong to current inputs; channel scales belong to resident weights. KV scales belong to the attention layer and are reused across Decode passes.',
  },
};

export const ENGINE_FORMULAS = {
  baseline: String.raw`Y=XW^\mathsf T`,
  gemm: String.raw`Y_{ij}\approx s_{X,i}\,s_{W,j}\sum_k Q_{X,ik}Q_{W,jk}`,
  kv: String.raw`Q_K=\operatorname{FP8}(K/s_K),\qquad \hat K=s_KQ_K`,
};
