import React,{useState,useEffect} from 'react';
import {Play,Pause,RotateCcw,SkipForward} from 'lucide-react';
import {useLanguage} from '../../lib/LanguageContext';
import {MathFormula} from './MathFormula';
import {vectorFor} from './model';
import {deriveLinearComparison} from './comparison-model';
import './comparison.css';
const i18n={zh:{title:'扫描历史，还是读取固定状态？',play:'播放计算对照',pause:'暂停计算对照',reset:'重置计算对照',next:'计算对照下一步',ready:'就绪',score:'QK 打分',softmax:'Softmax',value:'V 加权',map:'特征映射',outer:'生成写入增量',gate:'衰减旧状态',write:'更新状态',normalizer:'更新归一化状态',read:'读取状态',divide:'归一化输出',done:'完成',work:'累计乘法 / 乘加项',reads:'累计缓存 / 状态读取',stored:'驻留缓存 / 状态',note:'4 维合成矩阵；动画独立于下方详情。指标按上方 N、键维度和值维度推算，2 字节/元素；统计主乘法、乘加和状态读取，不含投影、特征映射、门生成、加法、除法、Softmax 非线性、写回与硬件缓存优化。两边各自推进，步数不是耗时。',prefill:'Prefill 按 8 个采样位置展示因果递推；指标累计到对应前缀，不代表实际并行内核。',decode:'Decode：同一段历史后的一个新查询，历史状态已构建；计入当前 Token 的状态更新。',difference:'Linear 的核映射改变注意力形式，GLA 采用门控递推；输出无需与 Softmax 相等。固定状态也不能按 Token 任意取回历史。',norm:'归一化状态',weights:'注意力权重'},en:{title:'Scan history, or read a fixed state?',play:'Play compute comparison',pause:'Pause compute comparison',reset:'Reset compute comparison',next:'Next comparison operation',ready:'Ready',score:'QK scores',softmax:'Softmax',value:'Weight V',map:'Feature map',outer:'Form update',gate:'Decay old state',write:'Update state',normalizer:'Update normalizer',read:'Read state',divide:'Normalize output',done:'Done',work:'Cumulative multiply / MAC terms',reads:'Cumulative cache / state reads',stored:'Resident cache / state',note:'Synthetic 4D matrices; playback is independent of details below. Metrics scale to N and selected key/value dimensions, at 2 bytes/element. Counts main multiply/MAC terms and state reads; excludes projections, feature maps, gate generation, additions, divisions, nonlinear Softmax, write-back and hardware caching. Independent steps are not wall time.',prefill:'Prefill shows causal recurrence at 8 sampled positions; metrics accumulate over the mapped prefix, not a parallel kernel schedule.',decode:'Decode: one new query after shared history, with prior state built. Includes the current token update.',difference:'Kernel Linear changes the attention function; GLA uses gated recurrence. Outputs need not equal Softmax. Fixed state does not preserve arbitrary token-addressable history.',norm:'Normalizer state',weights:'Attention weights'}};
function Grid({label,values,active=false,axis='col',limit=Infinity,current=-1}){
 return <div className="lc-matrix" data-active={active}><MathFormula>{label}</MathFormula><div className="lc-grid" style={{gridTemplateColumns:`repeat(${values[0].length},13px)`}}>{values.flatMap((row,r)=>row.map((v,c)=><i key={`${r}-${c}`} title={v.toFixed(3)} data-current={(axis==='col'?c:r)===current} data-hidden={(axis==='col'?c:r)>=limit} style={{background:`rgba(${v<0?'234,88,12':'109,40,217'},${.2+.75*Math.min(1,Math.abs(v))})`}}/>))}</div><MathFormula>{`${values.length}\\times${values[0].length}`}</MathFormula></div>;
}
const tr=a=>a[0].map((_,j)=>a.map(r=>r[j]));
const Op=({children})=><span className="lc-op"><MathFormula>{children}</MathFormula></span>;
export function ComputeComparison({targetMode:mode,contextMode:context,contextLength:n,dk,dv,gateStrength}){
 const [lang]=useLanguage(),t=k=>i18n[lang][k];const [cursor,setCursor]=useState(null),[playing,setPlaying]=useState(false);
 const e=deriveLinearComparison({mode,context,n,dk,dv,gateStrength,cursor});
 useEffect(()=>{if(!playing||e.done)return;const id=setTimeout(()=>setCursor(x=>(x??0)+1),700);return()=>clearTimeout(id);},[cursor,playing,e.done]);
 const complete=deriveLinearComparison({mode,context,n,dk,dv,gateStrength});
 const metrics=l=><aside>{[[t('work'),l.mac,Math.max(complete.full.mac,complete.state.mac,1)],[t('reads'),l.readBytes,Math.max(complete.full.readBytes,complete.state.readBytes,1)],[t('stored'),l.storedBytes,Math.max(complete.full.storedBytes,complete.state.storedBytes,1)]].map(([name,v,max],i)=><div key={name}><small>{name}</small><b>{i?(v/1024).toFixed(2)+' KiB':v.toLocaleString()}</b><span><i style={{width:`${v/max*100}%`}}/></span></div>)}</aside>;
 const f=e.full,s=e.state,fs=f.s,ss=s.s;
 const keys=Array.from({length:f.token+1},(_,i)=>vectorFor(i,2)),values=Array.from({length:f.token+1},(_,i)=>vectorFor(i,3));
 const normalized=['softmax','value','done'].includes(f.phase),scored=f.phase==='ready'?0:f.phase==='score'?f.count:keys.length;
 const vcount=f.phase==='value'?f.count:f.done?keys.length:0;
 const partial=Array.from({length:4},(_,d)=>values.slice(0,vcount).reduce((sum,v,i)=>sum+fs.weights[i]*v[d],0));
 const updateReady=['write','normalizer','read','divide','done'].includes(s.phase),outputReady=['read','divide','done'].includes(s.phase);
 return <div className="lc-comparison"><header><h3 data-section-anchor="linear-compute">{t('title')}</h3><div className="lc-actions"><button aria-label={t('reset')} onClick={()=>{setCursor(0);setPlaying(false);}}><RotateCcw size={15}/></button><button aria-label={t(playing&&!e.done?'pause':'play')} onClick={()=>{if(e.done){setCursor(0);setPlaying(true);}else setPlaying(!playing);}}>{playing&&!e.done?<Pause size={15}/>:<Play size={15}/>}</button><button disabled={e.done} aria-label={t('next')} onClick={()=>{setPlaying(false);setCursor((cursor??0)+1);}}><SkipForward size={15}/></button></div></header>
 <div className="lc-scroll"><div className="lc-lane"><strong>Full Attention<small>{t(f.phase)} · T{f.token+1}</small></strong><div className="lc-flow"><Grid label="q_t" values={[fs.query]} active={f.phase==='score'}/><Op>{'\\times'}</Op><Grid label="K_{1:t}^T" values={tr(keys)} active={f.phase==='score'} current={f.phase==='score'?f.count-1:-1}/><Op>{normalized?'\\xrightarrow{\\mathrm{softmax}}':'\\xrightarrow{/\\sqrt{d_k}}'}</Op><Grid label={normalized?'a_t':'\\ell_t'} values={[normalized?fs.weights:fs.scores]} limit={scored} active={['score','softmax','value'].includes(f.phase)} current={f.phase==='value'?f.count-1:-1}/><Op>{'\\times'}</Op><Grid label="V_{1:t}" values={values} axis="row" current={f.phase==='value'?f.count-1:-1} active={f.phase==='value'}/><Op>{'='}</Op><Grid label="o_t" values={[partial]} active={f.phase==='value'}/></div>{metrics(f)}</div>
 <div className="lc-lane lc-recurrent"><strong>{mode==='gla'?'GLA':'Linear Attention'}<small>{t(s.phase)} · T{s.token+1}</small></strong><div className="lc-recurrent-flow">
 <div className="lc-flow"><Grid label="S_{t-1}" values={ss.previousState} active={['gate','write'].includes(s.phase)}/>{mode==='gla'&&<><Op>{'\\odot'}</Op><Grid label="G_t" values={ss.gateMatrix} active={s.phase==='gate'}/><Op>{'\\longrightarrow'}</Op><Grid label="\widetilde S_{t-1}" values={ss.decayedState} active={s.phase==='gate'}/></>}<Op>{'+'}</Op><Grid label={mode==='gla'?'k_t':'\\phi(k_t)'} values={tr([mode==='gla'?ss.key:ss.phiKey])} active={s.phase==='outer'||s.phase==='map'}/><Op>{'\\times'}</Op><Grid label="v_t^T" values={[ss.value]} active={s.phase==='outer'}/><Op>{'\\longrightarrow'}</Op><Grid label="S_t" values={updateReady?ss.state:ss.previousState} active={s.phase==='write'||s.phase==='read'}/></div>
 {mode==='linear'&&<div className="lc-flow lc-normalizer"><small>{t('norm')}</small><Grid label="z_{t-1}" values={[ss.previousNormalizer]} active={s.phase==='normalizer'}/><Op>{'+'}</Op><Grid label="\\phi(k_t)^T" values={[ss.phiKey]} active={s.phase==='normalizer'}/><Op>{'='}</Op><Grid label="z_t" values={[['normalizer','read','divide','done'].includes(s.phase)?ss.normalizer:ss.previousNormalizer]} active={s.phase==='normalizer'||s.phase==='read'}/></div>}
 <div className="lc-flow"><Grid label={mode==='gla'?'q_t^T':'\\phi(q_t)^T'} values={[mode==='gla'?ss.query:ss.phiQuery]} active={s.phase==='read'}/><Op>{'\\times'}</Op><Grid label="S_t" values={updateReady?ss.state:ss.previousState} active={s.phase==='read'}/><Op>{'='}</Op><Grid label={mode==='linear'?'n_t':'o_t'} values={[outputReady?ss.numerator:[0,0,0,0]]} active={s.phase==='read'}/>{mode==='linear'&&<><Op>{'\\div'}</Op><Grid label="\phi(q_t)^Tz_t" values={[[outputReady?ss.denominator:0]]} active={s.phase==='read'||s.phase==='divide'}/><Op>{'='}</Op><Grid label="o_t" values={[[ 'divide','done'].includes(s.phase)?ss.linearOutput:[0,0,0,0]]} active={s.phase==='divide'}/></>}</div>
 </div>{metrics(s)}</div></div><p>{t(context)} {t('note')}</p><p>{t('difference')}</p></div>;
}
