import { FORMULAS } from './model.js';

export const getInitialLang = () => (typeof navigator !== 'undefined' && navigator.language?.toLowerCase().startsWith('zh') ? 'zh' : 'en');

export const i18n = {
  zh: {
    softmax: 'Softmax', detailPlayback: '详情动画', architectureShortTitle: '计算路径与历史状态', stageProgress: '整块算子阶段',
    title: 'Linear Attention 原理与推理可视化',
    subtitle: 'Softmax 对照 × 固定状态递归 × GLA 选择性门控',
    exact: '精确 Softmax', linear: '朴素 Linear', gla: 'GLA', softmaxVs: 'Softmax 对照',
    reset: '重置', play: '播放', pause: '暂停', next: '下一步', language: '切换语言', langToggle: 'EN', zh: '中文', en: 'EN',
    experiment: '规模与维度', sequenceLength: '序列长度 N', contextLength: '上下文长度 N', keyDim: '键维度 dₖ', valueDim: '值维度 dᵥ', comparisonTarget: '对照目标',
    designLevel: '设计视角', architectureTitle: '历史表示：逐 token KV Cache vs 固定压缩状态', architectureLead: '对比逐 token KV Cache 与固定递归状态，理解空间复杂度、可寻址性和信息损失。',
    executionContext: '执行上下文', decode: 'Decode', prefill: 'Prefill / 训练', growingKvCache: '随 N 增长的 KV Cache', pairwiseAttentionSurface: '全序列两两比较面', addressable: '可独立寻址', fixedRecurrentState: '固定递归状态', gatedFixedState: '带选择性遗忘的固定状态', compressed: '压缩摘要',
    softmaxDecodeVisual: '当前 query 连接不断增长的 KV Cache', softmaxPrefillVisual: '因果 Softmax 的 N 乘 N 两两比较面', softmaxDecodeLead: '每个历史 token 保留自己的 key 与 value；当前 query 可以分别匹配它们，但 KV Cache 与单步读取成本都会随上下文增长。', softmaxPrefillLead: '整段序列可并行计算，但逻辑上仍存在 N×N 的因果比较面，序列翻倍会让两两关系变为四倍。',
    logicalCells: '逻辑分数单元', moreSlots: '个额外 KV 槽位', chunksEnter: '并行 chunk 汇入', tokensEnter: '历史 token 汇入', fixedShape: '尺寸固定', linearCompressedLead: '历史不再保留独立槽位，而是通过外积累加进同一个 S 与 z；状态大小不随 N 增长。', glaCompressedLead: 'GLA 只持久化二维状态 S；输入相关的键轴门 α 与值轴门 β 先形成 G，再逐单元衰减旧状态并写入当前 token。',
    persistentMemory: '持久历史存储', singleTokenWork: '单 token 读取', historyAccess: '历史访问方式', addressableHistory: '每个 KV 槽位可单独匹配', compressedHistory: '只能读取合并后的状态摘要', growthWithN: '随 N 增长', linearGrowth: '存储与单步计算线性增长', fixedGrowth: '状态尺寸与单步计算基本固定',
    logicalIntermediate: '逻辑中间结构', sequenceWork: '整段序列计算', parallelForm: '并行形式', matrixParallel: '矩阵并行', chunkwiseGla: '硬件友好的分块并行', prefixOrChunk: '前缀扫描或分块并行', informationForm: '信息组织', pairwiseSurface: '保留两两关系面', compressedSummary: '合并为有限状态摘要', comparisonAxis: '比较维度', elements: '元素',
    currentMemoryRatio: '按当前 N 估算，Softmax Decode 的 KV 元素约为固定状态的', breakEvenAt: '理论交叉点约在', notYetSaving: '当前短上下文下固定状态尚未体现显存优势', prefillFlashNote: '这里比较的是逻辑计算面；FlashAttention 可避免完整物化 N² 分数矩阵，但不会消除精确注意力的两两计算。',
    compressionCostTitle: '压缩不是免费午餐：可寻址历史变成有限状态', compressionCostLead: '相似 key 对应不同 value 时，Softmax 仍能分别选择；Linear 把它们合并进同一状态，可能出现碰撞、混合与细节丢失。', separateSlots: 'Softmax：槽位保持分离', querySelectsB: 'query 精确选择 B', softmaxRecallResult: '结果：B 仍可被直接定位，其他历史不会被永久混入它的槽位。', mergedState: '固定状态：A/B/C 合并', noTokenAddress: '没有 token 地址', linearCollisionResult: '结果：只能从混合状态读取，有限维度中可能出现状态碰撞。', glaCollisionResult: '结果：门控可压低旧碰撞，但也可能把仍有用的历史一起遗忘。',
    prefillFlowTitle: 'Prefill 一次性算子流：阶段处理整块矩阵或 chunk，不逐 token 扫描', prefillSoftmax0: '并行生成 Q/K/V', prefillSoftmax1: '构造因果分数面', prefillSoftmax2: '遮罩与 Softmax', prefillSoftmax3: '矩阵聚合 V', prefillLinear0: '并行特征映射', prefillLinear1: '生成 chunk 摘要', prefillLinear2: '前缀/分块扫描', prefillLinear3: '并行读取输出', prefillGla0: '投影 Q/K/V 与 α/β', prefillGla1: 'chunk 内并行', prefillGla2: '门控状态跨 chunk', prefillGla3: '直接读取 qS',
    executionLevel: '执行视角', implementationDetailTitle: '单步 Decode 的状态更新', pairedStages: '两条流程各自推进', implementationDetailLead: '上下两条流程处理同一个 Token；每条按自己的步骤推进，步数不表示耗时。点击步骤查看右侧说明，不打断播放。', detailAlgorithm: '实现细节算法', demoSequence: '8-token 缩略演示', prefillHint: 'Prefill 播放按整块算子阶段推进，不模拟逐 token 串行执行。',
    currentToken: '当前 token', tokenPrefix: 't', tokenHint: '拖动或点击 token 会从该 token 的第一阶段开始检查完整 Decode 路径。',
    exactScores: 'Q/K/V 输入', exactMask: '相关性计算', exactAggregate: '遮罩与 Softmax', exactBottleneck: '加权聚合',
    linearMap: '特征映射', linearReorder: '外积写入', linearRecurrence: '状态累积', linearOutput: '归一化输出',
    glaProblem: '投影与双轴门控', glaGate: '逐单元衰减旧状态', glaRecurrence: '外积写入新状态', glaOutput: '直接读取 qS',
    stage: '当前阶段', principle: '原理解析', coreProblem: '核心问题', algorithmDifference: '算法差异', watchCanvas: '画板观察', equation: '核心公式', variableMeaning: '变量含义', liveState: '实时变量', pseudocode: '引擎式伪代码', boundary: '能力边界',
    pipelineTitle: '自回归 Decode 流水线', pipelineRule: '同一个 token 从左到右走完整条路径；生成输出后，下一个 token 才进入流水线。', pipelineRunning: 'Decode 自动执行中', pipelinePaused: '已暂停',
    stageComplete: '序列完成', stagePassed: '本 token 已流过', stagePending: '等待当前 token', activeStageLegend: '唯一执行阶段', glaRelationTitle: '论文版 GLA 使用门控矩阵递推，而不是带 z 的核归一化路径',
    glaRelationLead: 'GLA 直接使用投影后的 q/k/v：α 与 β 的外积形成二维门控 G，状态按单元衰减后写入 kᵀv，输出直接读取 qS；不再保留 φ(·) 与 z。',
    linearAccumulator: 'Linear：只累加', addForgetGate: '加入遗忘门', glaAccumulator: 'GLA：先衰减再累加',
    sameAtFirstToken: 't1 还没有历史状态可供遗忘，因此两种矩阵完全相同；播放到 t2 后，门控差异才会真实出现。',
    differenceAfterHistory: '历史已经写入：Linear 保留全部旧状态，GLA 先按当前门控衰减旧状态，再写入这个 token。', historyRetention: '旧状态保留率',
    logicalLayer: '逻辑层', physicalLayer: '物理层', currentWrite: '本次写入', historyState: '历史状态', updatedState: '更新后状态',
    query: '当前查询 qₜ', key: '当前键 kₜ', value: '当前值 vₜ', mappedQuery: '映射后 φ(qₜ)', mappedKey: '映射后 φ(kₜ)',
    score: '相关性分数', causalPrefix: '可见历史前缀', maskedFuture: '未来位置（遮罩）', attentionWeight: 'Softmax 权重', output: '输出 oₜ',
    exactScoreTitle: '当前 query 与所有历史 key 逐一匹配',
    exactScoreLead: '高亮行就是当前 token 的读取路径；每增加一个 token，都要多做一组两两比较。',
    exactMaskTitle: '只保留因果前缀，再把分数归一化',
    exactMaskLead: '当前 query 只能看到自己与过去。Softmax 把保留下来的分数转成总和为 1 的权重。',
    exactAggregateTitle: '权重沿数据流写入值向量',
    exactAggregateLead: '每个历史 value 按注意力权重贡献到当前输出，权重越大，数据流越亮。',
    exactInputTitle: '从输入生成当前计算所需的 Q、K、V',
    exactInputLead: '三个线性投影提供查询、匹配索引和值内容；后续算子始终沿这三条数据流工作。',
    exactBottleneckTitle: '瓶颈来自随 N 平方增长的比较面',
    exactBottleneckLead: 'FlashAttention 可以减少 HBM 往返，但不会改变精确注意力的二次计算关系。',
    linearMapTitle: '用正值特征映射替代 Softmax 核',
    linearMapLead: '映射把 q、k 送入可结合的乘积形式，为后续重排计算顺序创造条件。',
    linearReorderTitle: '先压缩历史，再让 query 读取',
    linearReorderLead: '右侧路径不再构造 N×N 分数矩阵，而是先得到固定大小的历史摘要。',
    linearOuterTitle: '把当前 key 与 value 写成一个外积增量',
    linearOuterLead: '每个 token 只产生一个固定大小的状态增量；这是递归状态真正接收的新信息。',
    linearRecurrenceTitle: '当前 token 只写入一个外积增量',
    linearRecurrenceLead: '黄色矩阵是本次写入；它与历史状态相加，得到可供后续 token 读取的新状态。',
    linearOutputTitle: 'query 从 S 读取内容，再由 z 校准尺度',
    linearOutputLead: 'S 聚合值信息，z 聚合归一化质量；两者缺一不可。',
    glaProblemTitle: '固定状态会持续累积无关历史',
    glaProblemLead: '朴素递归只会相加，不会主动遗忘。长序列中，过时信息会继续参与后续读取。',
    glaGateTitle: '键轴门与值轴门共同决定每个状态单元保留多少',
    glaGateLead: 'α 控制 dₖ 方向，β 控制 dᵥ 方向；两者外积得到 G，使二维状态的不同单元以不同速度衰减。',
    glaRecurrenceTitle: '先衰减旧状态，再写入当前信息',
    glaRecurrenceLead: '观察旧矩阵先被门控变暗，然后本次外积以高亮增量写入。',
    glaOutputTitle: '选择性记忆改变最终读取结果',
    glaOutputLead: '当前 query 直接左乘已更新的 S；这里没有 z 归一化器或除法读取。',
    glaMapGateTitle: '投影 Q/K/V，并生成 α、β 两个保留门',
    glaMapGateLead: '当前输入同时产生 q、k、v、键轴保留率 α 与值轴保留率 β；二者外积形成完整门控矩阵 G。',
    glaDecayTitle: '先让遗忘门作用到上一时刻状态',
    glaDecayLead: '保留率低的历史通道先衰减；这是 GLA 与朴素 Linear Attention 唯一关键的结构差异。',
    glaWriteTitle: '把当前 token 的外积增量写入衰减后的状态',
    glaWriteLead: '门控只处理旧历史，当前 token 的信息随后完整写入，形成供后续读取的新状态。',
    pairwiseScores: '逐键匹配', scoreMatrix: '因果分数矩阵（紧凑视图）', activeQueryRow: '当前 query 行',
    weightedValues: '按权重汇聚历史 value', contribution: '贡献',
    scoreStorage: '分数矩阵存储', recurrentStorage: '递归状态存储', scoreCellCount: '分数单元数',
    growsQuadratically: 'N 翻倍，分数单元变为 4 倍', fixedAcrossSequence: '不随序列长度 N 增长',
    hbmTraffic: 'HBM 中间结果', computeSurface: '两两比较计算面', fixedState: '固定状态 S 与 z',
    beforeMap: '映射前', afterMap: '映射后（全部为正）',
    leftAssociation: '先生成 N×N 注意力面', rightAssociation: '先生成固定大小状态', recommended: 'Linear 路径',
    nByN: 'N × N', dkByDv: 'dₖ × dᵥ', noScoreMatrix: '不物化分数矩阵',
    outerProduct: '外积增量 ΔSₜ', previousState: '旧状态 Sₜ₋₁', decayedState: '门控后的旧状态', newState: '新状态 Sₜ',
    normalizerUpdate: '归一化状态同步更新', previousNormalizer: '旧 z', newNormalizer: '新 z',
    numerator: '内容读取 φ(qₜ)ᵀSₜ', denominator: '尺度校准 φ(qₜ)ᵀzₜ',
    staleState: '过时信息仍残留', relevantState: '当前相关信息', ungated: '无门控', gated: 'GLA 门控',
    gateStrength: '遗忘强度', retention: '双轴保留率 αₜ / βₜ', retain: '保留', forget: '衰减',
    plainOutput: '无门控 qₜSₜ', gatedOutput: 'GLA qₜSₜ', noiseContribution: '旧噪声贡献', relevantContribution: '相关信号贡献',
    currentPulse: '当前 token 正在执行', sampledDimensions: '画板抽样展示 4 个维度，尺寸标签使用实际实验参数。',
    exactMetric: '精确，但计算与存储随 N² 增长', linearMetric: '固定状态，但属于核替换近似', glaMetric: '仅持久化 dₖ×dᵥ 状态，并具备输入相关的二维遗忘门',
    exactBoundary: '精确保持 Softmax 归一化关系；无法压成同样的固定递归状态。',
    linearBoundary: '效率来自核替换与结合律重排，因此不再与 Softmax 完全等价。',
    glaBoundary: '门控改善状态管理，但有限状态仍不能保证保留任意长距离细节；Prefill 还需要分块与 log-space 累积来控制连续 sigmoid 乘积的数值稳定性。',
    exactProblemSummary: '如何在保留每个历史 token 独立地址的前提下，让当前 query 精确选择相关内容？',
    linearProblemSummary: '如何避免逐 token KV Cache 持续增长，并把历史读取改写成固定状态递归？',
    glaProblemSummary: '固定状态容量有限时，如何抑制过时信息持续污染后续读取？',
    exactDifferenceSummary: 'Softmax 保存独立 K/V 槽位，读取精确但缓存和单步访存随上下文增长。',
    linearDifferenceSummary: 'Linear 用核映射和结合律先压缩历史，换取固定状态，也失去逐 token 寻址能力。',
    glaDifferenceSummary: 'GLA 使用 G=αᵀβ 对二维状态逐单元衰减，并以 o=qS 直接读取；它不沿用核 Linear 的 φ 映射、z 状态与归一化除法。',
    exactInputVisual: '观察当前 token 的 Q、K、V 三条数据流同时激活，K/V 随后进入持久缓存。',
    exactScoreVisual: '观察当前 query 扫过所有可见 K 槽位；上下文越长，被读取的槽位越多。',
    exactMaskVisual: '观察未来位置被屏蔽，可见分数经过归一化后变成总和为 1 的权重。',
    exactAggregateVisual: '观察不同亮度的数据流从历史 V 汇入当前输出。',
    linearMapVisual: '观察查询和键经过相同特征映射后进入可重排的乘积结构。',
    linearOuterVisual: '观察当前键值形成一个固定尺寸增量，而不是追加新的历史槽位。',
    linearRecurrenceVisual: '观察增量汇入旧状态，新状态随后回到下一 token 的输入位置。',
    linearOutputVisual: '观察 query 只读取固定状态与归一化状态，不再遍历历史 token。',
    glaMapGateVisual: '观察当前 token 生成 k、α、β，并由两个轴的门形成二维 G。',
    glaDecayVisual: '观察 G 的每个单元以不同强度衰减旧状态，当前写入尚未发生。',
    glaWriteVisual: '观察当前外积增量写入已经衰减的固定状态。',
    glaOutputVisual: '观察 q 直接读取更新后的 S，并比较有门与无门递推的输出差异；画板中不应再出现 z 或归一化分母。',
    exactInputVariables: ['查询向量负责检索当前需要的历史信息。', '键和值会写入该请求对应的持久 KV 槽位。'],
    exactScoreVariables: ['键维度决定单次相似度计算宽度。', '当前上下文长度决定本次 Decode 需要读取的缓存槽位数。'],
    exactMaskVariables: ['因果边界只允许当前位置访问自身和历史。', '归一化权重表示每个可见 value 的相对贡献。'],
    exactAggregateVariables: ['值向量携带最终被聚合的内容。', '输出向量是所有可见 value 的加权组合。'],
    linearMapVariables: ['特征映射必须产生可结合重排的核表示。', '映射后的查询和键维度决定固定状态的第一维。'],
    linearOuterVariables: ['状态增量编码当前键与值之间的关联。', '增量尺寸只由键维度和值维度决定。'],
    linearRecurrenceVariables: ['状态矩阵聚合历史键值关联。', '归一化状态累计映射后键的质量，防止输出尺度漂移。'],
    linearOutputVariables: ['分子从固定状态读取内容。', '分母使用归一化状态校准输出尺度。'],
    glaMapGateVariables: ['α∈(0,1)^{d_k} 控制键轴保留率，β∈(0,1)^{d_v} 控制值轴保留率。', 'G=αᵀβ 与 S 形状相同，可逐单元控制遗忘。'],
    glaDecayVariables: ['低 G 值对应的状态单元更快遗忘旧历史。', '门控只作用于旧状态，不削弱当前 token 的新写入。'],
    glaWriteVariables: ['衰减后的状态提供历史基底。', '当前外积增量随后写入同一固定状态槽位。'],
    glaOutputVariables: ['q 直接左乘 S 得到输出，不使用 z 归一化器。', '有门与无门输出的差异完全来自此前对历史状态的选择性衰减。'],
    softmaxCode0: ['slot = kv_cache.reserve(request_ids, tokens=1)', 'q, k, v = qkv_proj(hidden_states)', 'kv_cache.write_(slot_mapping=slot, key=k, value=v)', 'meta = decode_meta(block_table, sequence_lengths)'],
    softmaxCode1: ['backend = select_attention_backend(device, dtype, head_dim)', 'kv = kv_cache.view(block_table)', 'score_tiles = backend.qk_tiles(q, kv.keys, meta)', '# score tiles remain inside the fused decode kernel'],
    softmaxCode2: ['visible = causal_prefix(sequence_lengths)', 'weights = online_softmax(score_tiles, visible)', '# no attention-score tensor is persisted', 'assert_close(weights.sum(-1), 1.0)'],
    softmaxCode3: ['out = backend.decode(', '  query=q, kv_cache=kv_cache,', '  block_table=block_table, sequence_lengths=sequence_lengths)', 'return output_proj(out)'],
    linearCode0: ['state = state_pool.lookup(layer_id, request_ids)', 'q_bar, k_bar = feature_map(q), feature_map(k)', 'assert state.S.shape == [batch, heads, d_k, d_v]', 'assert state.z.shape == [batch, heads, d_k]'],
    linearCode1: ['delta_s = fused_outer_product(k_bar, v)', 'delta_z = k_bar', '# token update stays in registers/shared memory', 'kernel = recurrent_kernel if decode else chunk_kernel'],
    linearCode2: ['out, final_state = kernel(', '  q_bar, k_bar, v, initial_state=state,', '  output_final_state=True, cu_seqlens=cu_seqlens)', 'state_pool.store_(request_ids, final_state)'],
    linearCode3: ['content = batched_state_read(q_bar, final_state.S)', 'scale = batched_dot(q_bar, final_state.z).clamp_min(eps)', 'out = content / scale[..., None]', 'return output_proj(out)'],
    glaCode0: ['state = state_pool.lookup(layer_id, request_ids)', 'q, k, v, alpha, beta = fused_gla_proj(hidden_states)', 'gate = alpha[..., :, None] * beta[..., None, :]', 'kernel = recurrent_gla if decode else chunk_gla'],
    glaCode1: ['decayed_s = gate * state.S', '# canonical GLA keeps no z normalizer state', 'workspace.bind_(decayed_s)', 'meta = recurrent_meta(request_ids, sequence_lengths)'],
    glaCode2: ['out, final_s = kernel(', '  q, k, v, alpha, beta, initial_state=state.S,', '  output_final_state=True, cu_seqlens=cu_seqlens)', 'state_pool.store_(request_ids, final_s)'],
    glaCode3: ['content = batched_state_read(q, final_s)', 'out = head_norm(content)', 'out = output_gate(hidden_states) * out', 'return output_proj(out)'],
  },
  en: {
    softmax: 'Softmax', detailPlayback: 'Detail playback', architectureShortTitle: 'Compute paths and history state', stageProgress: 'Block operator stages',
    title: 'Linear Attention: Principles and Inference',
    subtitle: 'Softmax comparison × fixed-state recurrence × selective GLA gating',
    exact: 'Exact Softmax', linear: 'Naive Linear', gla: 'GLA', softmaxVs: 'Softmax vs',
    reset: 'Reset', play: 'Play', pause: 'Pause', next: 'Next step', language: 'Switch language', langToggle: '中文', zh: '中文', en: 'EN',
    experiment: 'Scale and dimensions', sequenceLength: 'Sequence length N', contextLength: 'Context length N', keyDim: 'Key dimension dₖ', valueDim: 'Value dimension dᵥ', comparisonTarget: 'Comparison target',
    designLevel: 'Design view', architectureTitle: 'History representation: per-token KV cache vs fixed compressed state', architectureLead: 'Compare per-token KV cache with fixed recurrent state to understand space complexity, addressability, and information loss.',
    executionContext: 'Execution context', decode: 'Decode', prefill: 'Prefill / training', growingKvCache: 'KV cache growing with N', pairwiseAttentionSurface: 'Full pairwise sequence surface', addressable: 'Addressable', fixedRecurrentState: 'Fixed recurrent state', gatedFixedState: 'Fixed state with selective forgetting', compressed: 'Compressed summary',
    softmaxDecodeVisual: 'The current query connects to a growing KV cache', softmaxPrefillVisual: 'The N by N causal pairwise surface of Softmax', softmaxDecodeLead: 'Every historical token keeps its own key and value. The current query can match them separately, while KV memory and per-step reads grow with context.', softmaxPrefillLead: 'The full sequence can be processed in parallel, but the logical N×N causal comparison surface remains and quadruples when sequence length doubles.',
    logicalCells: 'logical score cells', moreSlots: 'additional KV slots', chunksEnter: 'Parallel chunks enter', tokensEnter: 'History tokens enter', fixedShape: 'fixed shape', linearCompressedLead: 'History no longer has separate slots; outer-product writes merge into the same S and z whose shape is independent of N.', glaCompressedLead: 'GLA persists only the 2D state S. Input-dependent key-axis gate alpha and value-axis gate beta form G, which decays each state cell before the current token is written.',
    persistentMemory: 'Persistent history memory', singleTokenWork: 'Single-token read', historyAccess: 'History access', addressableHistory: 'Each KV slot can be matched separately', compressedHistory: 'Only the merged state summary is readable', growthWithN: 'Growth with N', linearGrowth: 'Memory and per-step work grow linearly', fixedGrowth: 'State shape and per-step work stay roughly fixed',
    logicalIntermediate: 'Logical intermediate', sequenceWork: 'Full-sequence work', parallelForm: 'Parallel form', matrixParallel: 'Matrix parallel', chunkwiseGla: 'Hardware-efficient chunkwise parallel', prefixOrChunk: 'Prefix scan or chunkwise parallel', informationForm: 'Information organization', pairwiseSurface: 'Preserves pairwise relation surface', compressedSummary: 'Merged into a finite state summary', comparisonAxis: 'Comparison axis', elements: 'elements',
    currentMemoryRatio: 'At the current N, Softmax Decode KV elements are about', breakEvenAt: 'Estimated crossover near', notYetSaving: 'At this short context, fixed state has not yet produced a memory advantage', prefillFlashNote: 'This compares the logical compute surface. FlashAttention can avoid materializing the full N² score matrix, but does not remove exact attention pairwise work.',
    compressionCostTitle: 'Compression is not free: addressable history becomes finite state', compressionCostLead: 'When similar keys map to different values, Softmax can still select them separately. Linear merges them into one state and may introduce collision, mixing, and lost detail.', separateSlots: 'Softmax: slots stay separate', querySelectsB: 'query selects B', softmaxRecallResult: 'Result: B remains directly addressable and other history is not permanently merged into its slot.', mergedState: 'Fixed state: A/B/C merge', noTokenAddress: 'No token address', linearCollisionResult: 'Result: reads come from a mixed state, so finite dimensions can create state collisions.', glaCollisionResult: 'Result: gating can suppress old collisions, but may also forget history that is still useful.',
    prefillFlowTitle: 'One-shot Prefill operator flow: each stage handles a matrix or chunk, not a serial token sweep', prefillSoftmax0: 'Project Q/K/V in parallel', prefillSoftmax1: 'Build causal score surface', prefillSoftmax2: 'Mask and Softmax', prefillSoftmax3: 'Matrix aggregation over V', prefillLinear0: 'Parallel feature map', prefillLinear1: 'Build chunk summaries', prefillLinear2: 'Prefix/chunk scan', prefillLinear3: 'Read outputs in parallel', prefillGla0: 'Project Q/K/V and alpha/beta gates', prefillGla1: 'Parallel recurrence inside chunks', prefillGla2: 'Compose gated states across chunks', prefillGla3: 'Read qS outputs in parallel',
    executionLevel: 'Execution view', implementationDetailTitle: 'Single-step Decode state update', pairedStages: 'Each lane follows its own stages', implementationDetailLead: 'Both lanes process the same token along their own stages; steps are not elapsed time. Click a stage to inspect it without stopping playback.', detailAlgorithm: 'Detail algorithm', demoSequence: '8-token miniature', prefillHint: 'Prefill playback advances by whole-matrix operator stages and does not simulate a serial token sweep.',
    currentToken: 'Current token', tokenPrefix: 't', tokenHint: 'Selecting a token restarts at its first stage so you can inspect the full Decode path.',
    exactScores: 'Q/K/V input', exactMask: 'Pairwise scores', exactAggregate: 'Mask & Softmax', exactBottleneck: 'Value aggregation',
    linearMap: 'Feature map', linearReorder: 'Outer-product write', linearRecurrence: 'State accumulation', linearOutput: 'Normalized read',
    glaProblem: 'Project & gate', glaGate: 'Cell-wise decay', glaRecurrence: 'State write', glaOutput: 'Direct state read',
    stage: 'Current stage', principle: 'Principle analysis', coreProblem: 'Core problem', algorithmDifference: 'Algorithm difference', watchCanvas: 'Watch on canvas', equation: 'Core equation', variableMeaning: 'Variable meaning', liveState: 'Live variables', pseudocode: 'Engine-style pseudocode', boundary: 'Boundary',
    pipelineTitle: 'Autoregressive Decode pipeline', pipelineRule: 'One token traverses the full path from left to right; only after its output is produced does the next token enter.', pipelineRunning: 'Decode auto running', pipelinePaused: 'Paused',
    stageComplete: 'Sequence complete', stagePassed: 'Passed by this token', stagePending: 'Waiting for token', activeStageLegend: 'Only executing stage', glaRelationTitle: 'Paper GLA uses a gated matrix recurrence, not the z-normalized kernel path',
    glaRelationLead: 'GLA predicts key-axis and value-axis gates, forms a 2D decay matrix, updates S, and reads qS directly. It does not reuse naive Linear Attention\'s feature map or z normalizer.',
    linearAccumulator: 'Linear: accumulate only', addForgetGate: 'add forget gate', glaAccumulator: 'GLA: decay then add',
    sameAtFirstToken: 'At t1 there is no previous state to forget, so both matrices are identical. The gated difference appears from t2 onward.',
    differenceAfterHistory: 'History now exists: Linear keeps all old state, while GLA decays it with the current gate before writing this token.', historyRetention: 'Old-state retention',
    logicalLayer: 'Logical layer', physicalLayer: 'Physical layer', currentWrite: 'Current write', historyState: 'History state', updatedState: 'Updated state',
    query: 'Current query qₜ', key: 'Current key kₜ', value: 'Current value vₜ', mappedQuery: 'Mapped φ(qₜ)', mappedKey: 'Mapped φ(kₜ)',
    score: 'Similarity score', causalPrefix: 'Visible causal prefix', maskedFuture: 'Future (masked)', attentionWeight: 'Softmax weight', output: 'Output oₜ',
    exactScoreTitle: 'Match the current query with every previous key',
    exactScoreLead: 'The highlighted row is the current read path. Every new token adds another set of pairwise comparisons.',
    exactMaskTitle: 'Keep the causal prefix, then normalize its scores',
    exactMaskLead: 'The current query sees only itself and the past. Softmax converts retained scores into weights that sum to one.',
    exactAggregateTitle: 'Weights route value vectors into the output',
    exactAggregateLead: 'Each historical value contributes according to its attention weight; stronger flows are drawn brighter.',
    exactInputTitle: 'Project the input into Q, K, and V for this computation',
    exactInputLead: 'The three projections provide the query, matching index, and value content used by every downstream operator.',
    exactBottleneckTitle: 'The bottleneck is the pairwise surface growing with N squared',
    exactBottleneckLead: 'FlashAttention reduces HBM traffic, but exact attention still performs quadratic pairwise work.',
    linearMapTitle: 'Replace the Softmax kernel with a positive feature map',
    linearMapLead: 'The map moves q and k into an associative product form that can be reordered.',
    linearReorderTitle: 'Compress history first, then let the query read it',
    linearReorderLead: 'The right path avoids an N×N score matrix and builds a fixed-size summary instead.',
    linearOuterTitle: 'Write the current key and value as one outer-product update',
    linearOuterLead: 'Each token produces one fixed-size state delta—the actual new information accepted by recurrent state.',
    linearRecurrenceTitle: 'The current token writes one outer-product update',
    linearRecurrenceLead: 'The amber matrix is the current write. Adding it to history produces the state consumed by later tokens.',
    linearOutputTitle: 'Read content from S and calibrate its scale with z',
    linearOutputLead: 'S aggregates values while z carries normalization mass; both are required.',
    glaProblemTitle: 'A fixed state keeps accumulating irrelevant history',
    glaProblemLead: 'Naive recurrence only adds and never forgets, so stale information keeps influencing later reads.',
    glaGateTitle: 'Two axis gates decide how much of every state cell survives',
    glaGateLead: 'The outer product of alpha and beta forms G, so each key-value state cell receives its own retention coefficient.',
    glaRecurrenceTitle: 'Decay old state before writing current information',
    glaRecurrenceLead: 'Watch the old matrix dim under the gate, then accept the highlighted outer-product update.',
    glaOutputTitle: 'Read the gated state directly with qS',
    glaOutputLead: 'The recurrent state already contains the gate history, so GLA needs no z denominator in this path.',
    glaMapGateTitle: 'Project q, k, v and predict alpha/beta gates together',
    glaMapGateLead: 'GLA uses direct projections and data-dependent key/value-axis gates; it does not apply the positive feature map used by naive kernel Linear Attention.',
    glaDecayTitle: 'Apply the forget gate to the previous state first',
    glaDecayLead: 'Low-retention history channels decay here. This is the key structural difference from naive Linear Attention.',
    glaWriteTitle: 'Write the current outer-product update into the decayed state',
    glaWriteLead: 'The gate acts only on old history; current-token information is then written into the state consumed by later reads.',
    pairwiseScores: 'Pairwise matches', scoreMatrix: 'Causal score matrix (compact)', activeQueryRow: 'Current query row', weightedValues: 'Aggregate historical values', contribution: 'Contribution',
    scoreStorage: 'Score storage', recurrentStorage: 'Recurrent storage', scoreCellCount: 'Score cells', growsQuadratically: 'Doubling N quadruples score cells', fixedAcrossSequence: 'Independent of sequence length N',
    hbmTraffic: 'HBM intermediates', computeSurface: 'Pairwise compute surface', fixedState: 'Fixed S and z state', beforeMap: 'Before mapping', afterMap: 'After mapping (positive)',
    leftAssociation: 'Build an N×N attention surface', rightAssociation: 'Build a fixed-size state first', recommended: 'Linear path', nByN: 'N × N', dkByDv: 'dₖ × dᵥ', noScoreMatrix: 'No materialized score matrix',
    outerProduct: 'Outer-product update ΔSₜ', previousState: 'Previous state Sₜ₋₁', decayedState: 'Gated previous state', newState: 'New state Sₜ', normalizerUpdate: 'Update normalizer in lockstep', previousNormalizer: 'Previous z', newNormalizer: 'New z',
    numerator: 'Content read φ(qₜ)ᵀSₜ', denominator: 'Scale calibration φ(qₜ)ᵀzₜ', staleState: 'Stale information remains', relevantState: 'Currently relevant information', ungated: 'Ungated', gated: 'GLA gated',
    gateStrength: 'Forgetting strength', retention: 'Two-axis retention αₜ / βₜ', retain: 'Retain', forget: 'Decay', plainOutput: 'Ungated qS', gatedOutput: 'GLA qS', noiseContribution: 'Stale noise contribution', relevantContribution: 'Relevant signal contribution',
    currentPulse: 'Current token executing', sampledDimensions: 'The canvas samples four dimensions while labels use the actual experiment sizes.',
    exactMetric: 'Exact, with compute and storage growing as N²', linearMetric: 'Fixed state, but based on a kernel approximation', glaMetric: 'Persists only a d_k by d_v state with input-dependent 2D forgetting',
    exactBoundary: 'Preserves exact Softmax normalization and cannot be compressed into the same fixed recurrent state.',
    linearBoundary: 'Efficiency comes from kernel replacement and reassociation, so it is not exactly equivalent to Softmax.',
    glaBoundary: 'Gating improves state management, but finite state still cannot guarantee arbitrary long-range detail. Prefill also needs chunking and log-space accumulation for stable products of sigmoid gates.',
    exactProblemSummary: 'How can the current query select relevant content while every historical token remains independently addressable?',
    linearProblemSummary: 'How can growing per-token KV cache be replaced by a fixed recurrent state?',
    glaProblemSummary: 'How can stale history be suppressed when a fixed state has limited capacity?',
    exactDifferenceSummary: 'Softmax keeps independent K/V slots: reads are exact, but cache size and per-step traffic grow with context.',
    linearDifferenceSummary: 'Linear Attention uses a kernel map and reassociation to compress history, trading away per-token addressability.',
    glaDifferenceSummary: 'GLA drops the feature-map and z-normalized path: alpha and beta form G, G decays S cell by cell, and q reads the updated state directly.',
    exactInputVisual: 'Watch Q, K, and V activate together; K and V then enter persistent cache slots.',
    exactScoreVisual: 'Watch the current query scan every visible K slot; longer context activates more reads.',
    exactMaskVisual: 'Watch future positions disappear and visible scores become weights summing to one.',
    exactAggregateVisual: 'Watch historical V flows merge into the current output with different intensities.',
    linearMapVisual: 'Watch query and key enter the same feature map and become an associative product.',
    linearOuterVisual: 'Watch the current key and value form a fixed-size update instead of a new history slot.',
    linearRecurrenceVisual: 'Watch the update merge into old state and the result return as the next token’s input.',
    linearOutputVisual: 'Watch the query read only fixed state and normalizer without scanning old tokens.',
    glaMapGateVisual: 'Watch the current token produce direct q/k/v projections plus alpha and beta gate vectors.',
    glaDecayVisual: 'Watch alpha and beta form G, then dim old-state cells before the current write.',
    glaWriteVisual: 'Watch the current outer-product update enter the already-decayed state.',
    glaOutputVisual: 'Compare gated and ungated contributions: stale noise falls while state size stays fixed.',
    exactInputVariables: ['The query vector retrieves information needed by the current token.', 'Keys and values are written into persistent request-specific KV slots.'],
    exactScoreVariables: ['Key dimension sets the width of each similarity calculation.', 'Current context length determines how many cache slots Decode must read.'],
    exactMaskVariables: ['The causal boundary exposes only the current position and history.', 'Normalized weights express each visible value’s relative contribution.'],
    exactAggregateVariables: ['Value vectors carry the content being aggregated.', 'The output is a weighted combination of all visible values.'],
    linearMapVariables: ['The feature map must produce a kernel representation that can be reassociated.', 'Mapped key/query width sets the first dimension of recurrent state.'],
    linearOuterVariables: ['The state update encodes the current key-value association.', 'Its shape depends only on key and value dimensions.'],
    linearRecurrenceVariables: ['The state matrix aggregates historical key-value associations.', 'The normalizer accumulates mapped-key mass to keep output scale stable.'],
    linearOutputVariables: ['The numerator reads content from fixed state.', 'The denominator calibrates scale with the normalizer state.'],
    glaMapGateVariables: ['Alpha controls the key axis and beta controls the value axis.', 'Their outer product gives every state cell a data-dependent retention coefficient.'],
    glaDecayVariables: ['Low-retention cells forget old history faster.', 'The gate affects old state, not the current token’s new write.'],
    glaWriteVariables: ['Decayed state provides the historical base.', 'The current outer-product update enters the same fixed state slot.'],
    glaOutputVariables: ['The query reads the state directly as qS.', 'This GLA path has no feature-map normalizer z.'],
    softmaxCode0: ['slot = kv_cache.reserve(request_ids, tokens=1)', 'q, k, v = qkv_proj(hidden_states)', 'kv_cache.write_(slot_mapping=slot, key=k, value=v)', 'meta = decode_meta(block_table, sequence_lengths)'],
    softmaxCode1: ['backend = select_attention_backend(device, dtype, head_dim)', 'kv = kv_cache.view(block_table)', 'score_tiles = backend.qk_tiles(q, kv.keys, meta)', '# score tiles remain inside the fused decode kernel'],
    softmaxCode2: ['visible = causal_prefix(sequence_lengths)', 'weights = online_softmax(score_tiles, visible)', '# no attention-score tensor is persisted', 'assert_close(weights.sum(-1), 1.0)'],
    softmaxCode3: ['out = backend.decode(', '  query=q, kv_cache=kv_cache,', '  block_table=block_table, sequence_lengths=sequence_lengths)', 'return output_proj(out)'],
    linearCode0: ['state = state_pool.lookup(layer_id, request_ids)', 'q_bar, k_bar = feature_map(q), feature_map(k)', 'assert state.S.shape == [batch, heads, d_k, d_v]', 'assert state.z.shape == [batch, heads, d_k]'],
    linearCode1: ['delta_s = fused_outer_product(k_bar, v)', 'delta_z = k_bar', '# token update stays in registers/shared memory', 'kernel = recurrent_kernel if decode else chunk_kernel'],
    linearCode2: ['out, final_state = kernel(', '  q_bar, k_bar, v, initial_state=state,', '  output_final_state=True, cu_seqlens=cu_seqlens)', 'state_pool.store_(request_ids, final_state)'],
    linearCode3: ['content = batched_state_read(q_bar, final_state.S)', 'scale = batched_dot(q_bar, final_state.z).clamp_min(eps)', 'out = content / scale[..., None]', 'return output_proj(out)'],
    glaCode0: ['state_s = state_pool.lookup(layer_id, request_ids)', 'q, k, v, alpha, beta = fused_gla_proj(hidden_states)', 'gate = alpha[..., :, None] * beta[..., None, :]', 'kernel = recurrent_gla if decode else chunk_gla'],
    glaCode1: ['decayed_s = gate * state_s', 'delta_s = fused_outer_product(k, v)', '# no z state: only the matrix recurrence is persistent', 'workspace.bind_(decayed_s, delta_s)'],
    glaCode2: ['out, final_s = kernel(', '  q, k, v, alpha, beta, initial_state=state_s,', '  output_final_state=True, log_space_gates=True)', 'state_pool.store_(request_ids, final_s)'],
    glaCode3: ['out = batched_state_read(q, final_s)', 'out = head_norm(out)', 'out = output_gate(out, hidden_states)', 'return output_proj(out)'],
  },
};

const titleKeys = {
  exact: ['exactInputTitle', 'exactScoreTitle', 'exactMaskTitle', 'exactAggregateTitle'],
  linear: ['linearMapTitle', 'linearOuterTitle', 'linearRecurrenceTitle', 'linearOutputTitle'],
  gla: ['glaMapGateTitle', 'glaDecayTitle', 'glaWriteTitle', 'glaOutputTitle'],
};

const leadKeys = {
  exact: ['exactInputLead', 'exactScoreLead', 'exactMaskLead', 'exactAggregateLead'],
  linear: ['linearMapLead', 'linearOuterLead', 'linearRecurrenceLead', 'linearOutputLead'],
  gla: ['glaMapGateLead', 'glaDecayLead', 'glaWriteLead', 'glaOutputLead'],
};

const formulaKeys = {
  exact: ['projections', 'exactScore', 'exactWeights', 'exactOutput'],
  linear: ['featureMap', 'outerUpdate', 'state', 'linearOutput'],
  gla: ['glaMapGate', 'glaDecay', 'glaWrite', 'glaOutput'],
};

const stageKeys = {
  exact: ['exactInput', 'exactScore', 'exactMask', 'exactAggregate'],
  linear: ['linearMap', 'linearOuter', 'linearRecurrence', 'linearOutput'],
  gla: ['glaMapGate', 'glaDecay', 'glaWrite', 'glaOutput'],
};

export const getStageCopy = (mode, step, t) => ({
  title: t(titleKeys[mode][step]),
  lead: t(leadKeys[mode][step]),
  problem: t(`${mode}ProblemSummary`),
  difference: t(`${mode}DifferenceSummary`),
  visual: t(`${stageKeys[mode][step]}Visual`),
  formula: FORMULAS[formulaKeys[mode][step]],
  variables: t(`${stageKeys[mode][step]}Variables`),
  code: t(`${mode === 'exact' ? 'softmax' : mode}Code${step}`),
  boundary: t(`${mode}Boundary`),
  activeLine: 2,
});
