import React from 'react';
import { MathFormula } from '../linear-attention/MathFormula';
import { InformationTradeoff } from './InformationTradeoff';

const vectorTex = (symbol, values) => `${symbol}=\\begin{bmatrix}${values.map(v => v.toFixed(3)).join('&')}\\end{bmatrix}`;

function Select({label,value,values,onChange}) { return <label className="sc-select"><span>{label}</span><select aria-label={label} value={value} onChange={e => onChange(+e.target.value)}>{values.map(v => <option key={v} value={v}>{v}</option>)}</select></label>; }
function Records({m,t,chooseRecord}) {
  return <><small>{t('recordsHint')}</small><div className="sc-records">{m.global.map(e => <button key={e.id} className={e.read ? 'sc-read' : ''} aria-label={`${e.id} · ${t(e.read?'fetched':'notFetched')}`} aria-pressed={m.tracedRecord?.id === e.id} onClick={() => chooseRecord(e)}>{e.id}{e.read && <span> ✓</span>}</button>)}</div></>;
}

export function NodeMicroscope({model:m,t,update,chooseRecord,onFocus}) {
  const c=m.channel;
  if(m.focus === 'query') return <><p>{t('matrixQueryNote')}</p><div className="sc-formula"><MathFormula block>{'h\\longrightarrow c^Q\\longrightarrow q'}</MathFormula><MathFormula block>{vectorTex('q',m.mainQuery)}</MathFormula></div><p>{t(m.indexed?'querySeparate':'noIndexer')}</p>{m.indexed && <><MathFormula block>{'c^Q\\longrightarrow q^I'}</MathFormula>{m.queryHeads.map((q,h) => <MathFormula key={h} block>{vectorTex(`q^I_{${h+1}}`,q)}</MathFormula>)}</>}</>;
  if(m.focus === 'local') return <><div className="sc-local-controls"><Select label={t('window')} value={m.window} values={[4,8,16]} onChange={window => update({window})}/><MathFormula>{`L=\\min(N,W)=${m.local.length}`}</MathFormula></div><div className="sc-history">{m.history.map(h => <span key={h.position} className={h.local?'sc-in-window':''}>{`T${h.position+1}`}</span>)}</div><p>{t('localWindowHint')}</p><div className="sc-records">{m.local.map(e=><button key={e.id} aria-pressed={m.tracedRecord?.id===e.id} onClick={()=>chooseRecord(e)}>{e.id}</button>)}</div>{m.tracedRecord?.position!==undefined&&<div className="sc-formula"><MathFormula block>{vectorTex('k=v',m.tracedRecord.key)}</MathFormula><span>{t('sourcePreview')} · {`T${m.tracedRecord.position+1}`}</span></div>}<button className="sc-inline-link" onClick={()=>onFocus('attention')}>{t('tradeOpen')}</button></>;
  if(m.focus === 'cache') return <>
    {m.compressed && <div className="sc-local-controls"><Select label={t('ratio')} value={m.ratio} values={m.mode === 'csa'?[2,4,8]:[8,16]} onChange={ratio => update(m.mode === 'csa'?{csaRatio:ratio}:{hcaRatio:ratio})}/><MathFormula>{`G=\\lfloor N/r\\rfloor=${m.global.length}`}</MathFormula></div>}
    <Records m={m} t={t} chooseRecord={chooseRecord}/><p>{t(m.compressed ? m.mode === 'csa'?'overlapHint':'nonoverlapHint':'rawHint')}</p>
    {m.entry ? <div className="sc-record-detail"><div className="sc-local-controls"><h3>{t('recordDetail')} · {m.entry.id}</h3>{m.compressed && <Select label={t('channelLabel')} value={c} values={[0,1]} onChange={channel=>update({channel})}/>}</div>
      {m.compressed ? <><div className="sc-history">{m.history.map(h=><span key={h.position} className={h.source ? h.previous?'sc-previous':'sc-source':''}>{`T${h.position+1}`}</span>)}</div><div className="sc-compression-result"><span>{t('compressionResult')} · {m.entry.id}</span><MathFormula>{`c_{${m.inspect+1},${c}}=${m.entry.key[c].toFixed(3)}`}</MathFormula></div><small>{t('gateHint')}</small><div className="sc-formula"><MathFormula>{m.gateFormula}</MathFormula><MathFormula>{m.compressionFormula}</MathFormula></div><table className="sc-table"><thead><tr>{['sourcesLabel','valueLabel','weightLabel','contributionLabel'].map(key=><th key={key}>{t(key)}</th>)}</tr></thead><tbody>{m.entry.main.rows.map(row=><tr key={row.position}><th>{`T${row.position+1}`}<small>{t(row.previous?'previous':'currentGroup')}</small></th><td>{row.values[c].toFixed(3)}</td><td><div className="sc-cell-bar" style={{backgroundSize:`${row.weights[c]*100}% 100%`}}>{row.weights[c].toFixed(3)}</div></td><td>{(row.values[c]*row.weights[c]).toFixed(3)}</td></tr>)}</tbody></table><MathFormula block>{`c_{${m.inspect+1},${c}}=${m.entry.key[c].toFixed(3)}`}</MathFormula></> : <><MathFormula block>{vectorTex('k',m.entry.key)}</MathFormula><MathFormula block>{vectorTex('v',m.entry.value)}</MathFormula></>}
    </div>:<p>{t('empty')}</p>}
    {m.compressed && <p className="sc-tail">{t('pendingLabel')}: {m.tail.length} · {t('carryLabel')}: {m.carry.length}</p>}<button className="sc-inline-link" onClick={()=>onFocus('attention')}>{t('tradeOpen')}</button>
  </>;
  if(m.focus === 'index') return <IndexInspector m={m} t={t} update={update} chooseRecord={chooseRecord}/>;
  return <><div className="sc-local-controls">{m.indexed && <Select label={t('topK')} value={m.topK} values={[1,2,4,8]} onChange={topK=>update({topK})}/>}<MathFormula>{m.readFormula}</MathFormula></div><InformationTradeoff m={m} t={t}/><h3>{t('jointWeights')}</h3><div className="sc-weights">{m.reads.map(e=><button key={e.id} data-output-record={e.id} aria-pressed={m.tracedRecord?.id===e.id} onClick={()=>chooseRecord(e)}><span>{e.id}<small>{t(e.branch==='local'?'localLabel':'globalLabel')}</small></span><div className="sc-track"><i className={e.branch==='local'?'sc-teal':''} style={{width:`${e.weight*100}%`}}/></div><b>{(e.weight*100).toFixed(1)}%</b></button>)}</div>{m.reads.find(e=>e.id===m.tracedRecord?.id)&&<div className="sc-formula"><strong>{t('contribution')} · {m.tracedRecord.id}</strong><MathFormula block>{vectorTex('a_e v_e',m.reads.find(e=>e.id===m.tracedRecord.id).value.map(v=>v*m.reads.find(e=>e.id===m.tracedRecord.id).weight))}</MathFormula><button className="sc-inline-link" onClick={()=>onFocus(m.tracedRecord.position!==undefined?'local':'cache')}>{t('backSource')}</button></div>}<div className="sc-formula"><MathFormula block>{m.attentionFormula}</MathFormula><MathFormula block>{vectorTex('o',m.output)}</MathFormula></div><small>{t('readHint')}</small></>;
}

function IndexInspector({m,t,update,chooseRecord}) {
  const entry=m.entry;
  return <><div className="sc-local-controls"><Select label={t('topK')} value={m.topK} values={[1,2,4,8]} onChange={topK=>update({topK})}/><span>{t('scanLabel')} <b>{m.indexReads}</b></span><label className="sc-select"><span>{t('sortLabel')}</span><select aria-label={t('sortLabel')} value={m.scoreOrder} onChange={e=>update({scoreOrder:e.target.value})}><option value="position">{t('positionOrder')}</option><option value="score">{t('scoreOrder')}</option></select></label></div><small>{t('scoreScale')}</small>
    <div className="sc-index-layout"><div className="sc-score-grid" tabIndex={0} aria-label={t('sortLabel')}>{m.scoreEntries.map(e=><button key={e.id} aria-label={`${e.id} · ${t(e.read?'fetched':'notFetched')}`} aria-pressed={e.id===m.tracedRecord?.id} className={e.read?'sc-read':''} onClick={()=>chooseRecord(e)}><span>{e.id}{e.read?' ✓':''}</span><div className="sc-track"><i style={{width:`${e.score/Math.max(.001,...m.global.map(x=>x.score))*100}%`}}/></div><b>{e.score.toFixed(2)}</b></button>)}</div>
    {entry?<div className="sc-score-detail"><h3>{t('viewing')} · {entry.id}</h3><p>{t(entry.read?'fetched':'notFetched')}</p><MathFormula block>{m.indexFormula}</MathFormula><MathFormula block>{vectorTex('k^I',entry.indexKey)}</MathFormula><MathFormula block>{`I_{${m.inspect+1}}=${entry.headScores.map(v=>v.toFixed(3)).join('+')}=${entry.score.toFixed(3)}`}</MathFormula><p>{t('indexVars')}</p></div>:<p>{t('empty')}</p>}</div>{m.compressed&&<p>{t('indexIndependent')}</p>}
  </>;
}
