export const canvasI18n = {
  zh: {
    outcome_better: '改善', outcome_worse: '变差', outcome_same: '持平', direction_up: '增加', direction_down: '减少', direction_same: '无变化',
    lessIsBetter: '越少越好', moreIsBetter: '越多越好', benefitsTogether: '三项收益，一眼对照',
    brief_memory: '包含全局、局部与索引缓存。', brief_traffic: '包含主 KV 读取与索引扫描，不等于实际速度。', brief_context: '固定预算下能容纳的历史，不代表模型有效上下文。',
    metric_memory: '缓存占用', metric_traffic: '每步读取量', metric_context: '预算可容纳历史', metricGroup: '查看哪一种效果',
    benefitTitle: '同一机制，三种不同的收益', byteExperiment: '单层 decode · 教学估算',
    memoryQuestion: '同样的历史，要留多少缓存？', trafficQuestion: '生成下一个 token，要搬多少缓存数据？', contextQuestion: '相同缓存预算，能容纳多长历史？',
    memoryMeaning: '包含全局主 KV、局部窗口和独立索引记录。DSA 保留全部主 KV，索引还会额外占空间；压缩减少的是全局记录数。',
    trafficMeaning: '计入本次主 KV 读取与独立索引扫描。更少的数据搬运有助于带宽受限的解码，但端到端速度还取决于索引、压缩、计算、kernel 和调度。',
    contextMeaning: '这里求的是缓存预算能装下的历史。省下的空间也能用于更多并发请求；模型实际支持的长度仍受训练、位置编码、配置和质量验证限制。',
    sameBytes: '相同占用', lessBytes: '占用减少', moreBytes: '占用增加', lessTraffic: '读取量减少', moreTraffic: '读取量增加', sameTraffic: '相同读取量',
    capacityFactor: '可容纳历史之比', tokenUnit: 'tokens', budgetLabel: '该层缓存预算', estimateNotice: '教学假设：基线 / 全局 / 局部每条 1 KiB，索引每条 128 B。不是实际模型的显存或速度测量。',
    budgetNotice: '预算已扣除权重、激活、压缩工作区等，仅分配给这一层的缓存；不代表整张 GPU 的显存。',
    contextBoundary: '装得下 ≠ 模型能有效理解这么长的上下文', efficiencyBoundary: '读取量下降 ≠ 相同比例的 tokens/s 提升', memoryBoundary: '缓存变小，可以换取更长历史或更多并发',
    costLegend: '全局主 KV / 局部主 KV / 独立索引', assumedScale: '两条共用字节尺度，包含索引开销', capacityScale: '两条共用 token 尺度，预算相同',
    formulaDetail: '查看估算口径', memoryVariables: 'G 是全局记录数，L 是窗口记录数，I 是索引记录数；b 表示相应记录的字节数。',
    trafficVariables: '仅统计一次解码的逻辑缓存读取；未计入压缩器读写、中间激活、缓存命中和实际 kernel 的重复访问。',
    contextVariables: '求满足预算 B 的最大历史 N；这只是容量约束，没有模拟模型质量或位置编码上限。',
    canvasSubtitle: '沿着整体关系，理解缓存、效率与长上下文之间的取舍。',
    strategy: '对照机制', strategy_dsa: '稀疏读取 · DSA', strategy_csa: '压缩 + 稀疏 · CSA', strategy_hca: '高压缩 · HCA',
    experiment: '同一段历史 · 同一个 query', why: '历史变长，会给缓存和读取带来什么变化？',
    baseline: '普通全量 Attention', optimized: '当前机制', mainReadsLabel: '主读取', scanLabel: '另需索引扫描',
    storeLabel: '驻留主缓存', globalLabel: '全局', localLabel: '局部', retainedLabel: '未选中仍保留',
    scaleNote: '条形按逻辑记录计数，共用 64 条比例尺。不同记录维度不等，不能换算为显存比例或实际加速。',
    overview: '整体关系', zoomHint: '点击节点，原位放大；沿连线追踪输入与输出', back: '返回整体', follow: '沿输出继续',
    historyNode: '历史 hidden states', currentNode: '当前 hidden state', queryNode: 'Query 投影', cacheNode: '全局缓存', indexNode: '索引 → Top-K', localNode: 'SWA 局部窗口', attentionNode: 'Attention 汇合',
    queryHint: '主 query 用于注意力打分', cacheHint: '完整组 → 压缩记录', rawCacheHint: '逐 token 保存 K/V', indexHint: '扫描索引 key → 读取主 KV', localHint: '保留最近逐 token 细节', attentionHint: '一次 softmax，共同加权', outputNode: '加权结果 → 输出投影',
    routeGlobal: '全局记录', routeIndexKey: '独立索引 key', routeLocal: '局部 K/V', routeQuery: '主 query', routeIndexQuery: '索引 query', routeIds: '按 ID 读取主 KV',
    focus_query: 'Query：这次需要什么信息？', focus_cache: '缓存：历史怎样被保存？', focus_index: '索引：从哪里挑选主 KV？', focus_local: 'SWA：为什么还要局部窗口？', focus_attention: '汇合：哪些记录共同生成输出？',
    desc_query: '当前 hidden 经投影生成 query。切换示例 query，会改变索引选择与注意力权重；历史缓存内容保持不变。',
    desc_cache: '点击一条全局记录，查看其来源。压缩沿历史位置合并信息，局部窗口仍独立保留近期细节。',
    desc_index: '先扫描独立的轻量索引 key，取 Top-K 的 ID，再读取对应主 KV。未选中的主 KV 不会被删除。',
    desc_local: '压缩记录无法让每个来源 token 都被单独寻址。SWA 并行保留近期逐 token K/V，与全局分支共同参与 attention。',
    desc_attention: '主 query 对读取集合打分。全局与局部记录一起归一化；它们即使覆盖相同历史位置，也不按来源去重。',
    incoming: '输入', outgoing: '输出', in_query: '当前 hidden', out_query: '主 query / 索引 query', in_cache: '历史投影', out_cache: '驻留的全局记录', in_index: '索引 query + 索引 key', out_index: 'Top-K ID → 主 KV', in_local: '近期 K/V', out_local: '窗口内 K/V', in_attention: 'query + 已读取 K/V', out_attention: '加权向量',
    recordsHint: '点选记录查看来源与数值；✓ 表示本次读取', recordDetail: '记录显微镜', channelLabel: '通道', sourcesLabel: '来源位置', valueLabel: '候选值', weightLabel: '门控权重', contributionLabel: '加权贡献',
    gateHint: '每个通道沿来源位置独立做 softmax；贡献求和得到该通道的压缩值。', overlapHint: 'CSA 使用前一组与当前组的不同投影，最多覆盖两组；每完成一组才发布一条记录。', nonoverlapHint: 'HCA 每组独立压缩，读取所有已发布的全局记录，没有 Top-K。', rawHint: '这些主 KV 全量保留。DSA 减少本次读取，并不减少主缓存的历史条目数。',
    pendingLabel: '尚未发布的尾部 token', carryLabel: '下组继续使用的前组 token', empty: '还没有完整组；当前依靠局部窗口提供 K/V。',
    scanHint: '条长为索引分数，✓ 为所选 ID；不是最终 attention 权重。', indexIndependent: '主缓存与索引缓存使用独立投影和压缩参数。索引 key 不等于主 K/V。',
    querySeparate: '主 query 与索引 query 是不同投影的输出，分别用于主注意力与轻量选择。', noIndexer: '此机制没有索引器，主 query 直接读取全局压缩项与局部窗口。',
    jointWeights: '当前读取集合 · 联合 attention 权重', localWindowHint: '窗口外位置从局部缓存移出；它们仍可由全局压缩记录表示。',
    why_dsa: '少读主 KV；仍保存全部历史，另付索引扫描成本。遗漏重要记录会影响输出。',
    why_csa: '全局先压缩再选读，局部窗口保留近期细节；代价是历史表示更粗，并增加压缩与索引开销。',
    why_hca: '更少的全局记录可以全部读取，省去索引；压缩更粗，依靠局部窗口补充近期细节。',
    shortHistory: '当前历史较短：局部与全局合读可能比全量读取更多条记录。收益取决于长度与参数。',
    boundaries: '实验边界与技术来源', boundariesText: '单层因果 decode 快照，当前 token 已写入。二维固定数值用于说明路由、门控与归一化，省略 RoPE、归一化、attention sink、量化和输出投影。条目计数不包含压缩器工作区，不代表真实速度或质量评测；这些机制需要相应训练，不能把已有模型直接切换成另一种结构。',
    sourceDetail: 'DSA、CSA 与 HCA 的原理分别参考下列技术报告。这里缩小窗口、压缩组与 Top-K，便于逐条检查；不展示某个模型的完整层配置。',
    allRead: '全局全部读取', scoreDetail: '所选记录的索引分数', mainKey: '主 key', mainValue: '主 value', indexKey: '索引 key', currentRecord: '当前记录',
  },
  en: {
    outcome_better: 'Better', outcome_worse: 'Worse', outcome_same: 'Unchanged', direction_up: 'Increase', direction_down: 'Decrease', direction_same: 'No change',
    lessIsBetter: 'Lower is better', moreIsBetter: 'Higher is better', benefitsTogether: 'Three effects, side by side',
    brief_memory: 'Includes global, local and index caches.', brief_traffic: 'Main KV reads plus index scanning; not measured speed.', brief_context: 'History that fits the budget, not effective model context.',
    metric_memory: 'Cache memory', metric_traffic: 'Reads per step', metric_context: 'History that fits', metricGroup: 'Effect to inspect',
    benefitTitle: 'One mechanism, three different effects', byteExperiment: 'Single-layer decode · estimate',
    memoryQuestion: 'How much cache must the same history retain?', trafficQuestion: 'How much cache data is read for the next token?', contextQuestion: 'How much history fits the same cache budget?',
    memoryMeaning: 'Includes global main KV, the local window and separate index records. DSA retains all main KV and adds index storage; compression reduces the number of global records.',
    trafficMeaning: 'Counts main KV reads and the separate index scan. Less data movement helps bandwidth-bound decoding, but end-to-end speed also depends on indexing, compression, compute, kernels and scheduling.',
    contextMeaning: 'This is the history that fits a cache budget. Saved space can also support more concurrent requests. Actual supported length still depends on training, positional encoding, configuration and quality validation.',
    sameBytes: 'Same memory', lessBytes: 'Less memory', moreBytes: 'More memory', lessTraffic: 'Fewer read bytes', moreTraffic: 'More read bytes', sameTraffic: 'Same read bytes',
    capacityFactor: 'History capacity ratio', tokenUnit: 'tokens', budgetLabel: 'Layer cache budget', estimateNotice: 'Teaching assumptions: 1 KiB per baseline / global / local record, 128 B per index record. Not measured model memory or speed.',
    budgetNotice: 'The budget is for this layer’s cache after reserving weights, activations and compressor workspace. It is not total GPU memory.',
    contextBoundary: 'Fits in memory ≠ effective long-context understanding', efficiencyBoundary: 'Fewer read bytes ≠ the same increase in tokens/s', memoryBoundary: 'Smaller caches can support longer history or more requests',
    costLegend: 'Global main KV / local main KV / separate index', assumedScale: 'Shared byte scale, including index overhead', capacityScale: 'Shared token scale, equal cache budget',
    formulaDetail: 'Inspect the estimate', memoryVariables: 'G counts global records, L local records and I index records; b is each record type’s byte size.',
    trafficVariables: 'Logical cache reads for one decode step only; excludes compressor traffic, intermediate activations, cache hits and repeated physical kernel accesses.',
    contextVariables: 'Find the largest history N that fits budget B. This models capacity only, not quality or positional-encoding limits.',
    canvasSubtitle: 'Follow the system to explore tradeoffs between cache memory, efficiency and long context.',
    strategy: 'Comparison mechanism', strategy_dsa: 'Sparse reads · DSA', strategy_csa: 'Compress + select · CSA', strategy_hca: 'High compression · HCA',
    experiment: 'Shared history · shared query', why: 'How does longer history affect cache memory and reads?',
    baseline: 'Ordinary full attention', optimized: 'Current mechanism', mainReadsLabel: 'Main reads', scanLabel: 'Additional index scan',
    storeLabel: 'Resident main cache', globalLabel: 'Global', localLabel: 'Local', retainedLabel: 'Unselected stays resident',
    scaleNote: 'Logical records on a shared 64-record scale. Record dimensions differ: these are not memory ratios or measured speedups.',
    overview: 'System overview', zoomHint: 'Click a node to zoom in place; follow its input and output connections', back: 'Back to overview', follow: 'Follow output',
    historyNode: 'Historical hidden states', currentNode: 'Current hidden state', queryNode: 'Query projection', cacheNode: 'Global cache', indexNode: 'Index → Top-K', localNode: 'SWA local window', attentionNode: 'Attention merge',
    queryHint: 'Main query scores attention', cacheHint: 'Complete groups → compressed records', rawCacheHint: 'Store per-token K/V', indexHint: 'Scan index keys → read main KV', localHint: 'Recent per-token detail', attentionHint: 'One softmax, joint weighting', outputNode: 'Weighted result → output projection',
    routeGlobal: 'Global records', routeIndexKey: 'Separate index keys', routeLocal: 'Local K/V', routeQuery: 'Main query', routeIndexQuery: 'Index query', routeIds: 'Fetch main KV by ID',
    focus_query: 'Query: what information is needed?', focus_cache: 'Cache: how is history stored?', focus_index: 'Index: which main KV should be read?', focus_local: 'SWA: why keep a local window?', focus_attention: 'Merge: which records produce the output?',
    desc_query: 'A projection of the current hidden state produces the query. Switching the example query changes selection and attention weights while leaving historical cache contents intact.',
    desc_cache: 'Select a global record to inspect its sources. Compression merges information along history; the local window independently retains recent details.',
    desc_index: 'Scan separate lightweight index keys, take Top-K IDs, then read those main KV records. Unselected main KV records are not deleted.',
    desc_local: 'A compressed record cannot address every source token individually. SWA keeps recent per-token K/V in parallel, sharing attention with the global branch.',
    desc_attention: 'The main query scores the read set. Global and local records normalize together, even when they cover overlapping source positions.',
    incoming: 'Input', outgoing: 'Output', in_query: 'Current hidden', out_query: 'Main / index query', in_cache: 'Historical projections', out_cache: 'Resident global records', in_index: 'Index query + index keys', out_index: 'Top-K IDs → main KV', in_local: 'Recent K/V', out_local: 'Window K/V', in_attention: 'Query + fetched K/V', out_attention: 'Weighted vector',
    recordsHint: 'Select a record for sources and values; ✓ marks a current read', recordDetail: 'Record microscope', channelLabel: 'Channel', sourcesLabel: 'Source position', valueLabel: 'Candidate', weightLabel: 'Gate weight', contributionLabel: 'Contribution',
    gateHint: 'Each channel applies softmax across source positions independently. Sum the contributions to obtain its compressed value.', overlapHint: 'CSA projects the preceding and current groups separately, covering up to two groups. One record is published per completed group.', nonoverlapHint: 'HCA compresses each group independently and reads every published global record, without Top-K.', rawHint: 'All main KV records remain resident. DSA reduces current reads, not the number of historical main-cache records.',
    pendingLabel: 'Unpublished tail tokens', carryLabel: 'Previous-group tokens carried forward', empty: 'No group is complete yet; attention currently uses the local window.',
    scanHint: 'Bar length is an index score; ✓ marks selected IDs. These are not final attention weights.', indexIndependent: 'Main and index caches have independent projection and compression parameters. Index keys are not main K/V.',
    querySeparate: 'Main and index queries come from different projections, serving attention and lightweight selection respectively.', noIndexer: 'No indexer here: the main query reads all global compressed records and the local window directly.',
    jointWeights: 'Current read set · joint attention weights', localWindowHint: 'Positions outside the window leave the local cache; global compressed records can still represent them.',
    why_dsa: 'Fewer main KV reads, but full historical residency and extra index scanning. Omitting important records can affect output.',
    why_csa: 'Compress and select global history while a local window keeps recent details. Coarser history and compression/index overhead are the tradeoffs.',
    why_hca: 'Fewer global records allow reading them all without indexing. Coarser compression relies on a local window for recent detail.',
    shortHistory: 'For this short history, combined global and local reads may exceed full attention. Benefits depend on length and parameters.',
    boundaries: 'Experiment scope and sources', boundariesText: 'A causal single-layer decode snapshot with the current token already written. Fixed 2D examples illustrate routing, gating and normalization; RoPE, normalization, attention sinks, quantization and output projections are omitted. Record counts exclude compressor workspace and are not speed or quality measurements. These mechanisms require appropriate training; an existing model cannot simply switch structures.',
    sourceDetail: 'The reports below describe DSA, CSA and HCA. Smaller windows, groups and Top-K make individual records inspectable here; this is not a full model layer configuration.',
    allRead: 'Read all global records', scoreDetail: 'Selected record index score', mainKey: 'Main key', mainValue: 'Main value', indexKey: 'Index key', currentRecord: 'Selected record',
  },
};
