import React from 'react';
import {Play,Pause,SkipForward,RotateCcw} from 'lucide-react';

export const executionCopy={
 zh:{sequenceQuery:'当前位置的 Query',sequencePosition:'播放位置',runRapid:'流畅 · 0.25 秒/步',runHalf:'快速 · 0.5 秒/步',runSpeed:'播放速度',runSlow:'慢速 · 6 秒/步',runNormal:'标准 · 2 秒/步',runFast:'快速 · 1.5 秒/步',runQuick:'快速 · 1 秒/步',runTitle:'沿 Token 位置连续查询',runPlay:'播放执行过程',runPause:'暂停执行',runStep:'执行下一步',runReplay:'从头重播',runOverview:'回到完整结果',runScope:'每个位置从当时已可见的缓存开始查询；输出完成后前进一位，到最后一个位置后停止。各位置 Query 为合成样例，不是真实文本生成；缓存创建内核未展开。上方按完整历史对照，下方只显示当前前缀。点击详情不暂停。',runIdle:'当前为完整结果，点击播放或单步查看产生过程。',runNext:'当前待执行',runDone:'本次 Query 完成',runBytes:'已读取 / 整次预计',runKeep:'缓存驻留量不变',runReference:'详情面板是完整计算参考；左侧画布展示当前执行进度。',runUnselected:'尚未选取',runUnread:'尚未读取',runPending:'尚未计算',runChosen:'已选中，尚未读取',runMoving:'本步读取',runScores:'索引分数',runTiming:'每步最多展示 4 条记录的读取；这是教学分组，非实际内核调度或耗时。',run_project:'投影 Query',run_index:'读取索引并打分',run_select:'选取 Top-K',run_read:'读取主 KV / 局部 KV',run_score:'计算 Attention 分数',run_normalize:'联合 Softmax',run_output:'加权得到输出',run_done:'完成',hint_project:'先产生主 Query；有索引器时同时准备索引 Query。',hint_index:'读取索引 K 并生成分数；此时还没有读取主 KV。',hint_select:'只产生位置编号，未选中的缓存仍驻留。',hint_read:'标亮的记录沿原路径进入汇合矩阵；已读取记录打勾。',hint_score:'用主 Query 对已读记录计算 Attention 分数。',hint_normalize:'对同一读取集合联合归一化，得到每条记录的权重。',hint_output:'根据权重汇总 V；完成后才展示输出向量。',hint_done:'当前位置输出完成；下一步进入下一个位置，到终点后停止。'},
 en:{sequenceQuery:'Query at the current position',sequencePosition:'Playback position',runRapid:'Fluid · 0.25 s/step',runHalf:'Quick · 0.5 s/step',runSpeed:'Playback speed',runSlow:'Slow · 6 s/step',runNormal:'Normal · 2 s/step',runFast:'Fast · 1.5 s/step',runQuick:'Fast · 1 s/step',runTitle:'Follow successive token positions',runPlay:'Play execution',runPause:'Pause execution',runStep:'Execute next step',runReplay:'Replay from start',runOverview:'Show complete result',runScope:'Query the cache visible at each position, advance after output, and stop at the final position. Position queries are synthetic, not generated text; cache creation kernels are omitted. Above: full-history comparison; below: current prefix. Inspecting details does not pause playback.',runIdle:'Showing the complete result. Play or step to inspect how it is produced.',runNext:'Next operation',runDone:'Query complete',runBytes:'Read so far / expected total',runKeep:'Resident cache stays unchanged',runReference:'The inspector shows the complete computation reference; the left canvas shows execution progress.',runUnselected:'Not selected yet',runUnread:'Not read yet',runPending:'Not computed yet',runChosen:'Selected, not read yet',runMoving:'Reading this step',runScores:'Indexer scores',runTiming:'Up to 4 records are shown per read step. These are teaching groups, not kernel scheduling or measured time.',run_project:'Project query',run_index:'Read and score index',run_select:'Select Top-K',run_read:'Read main / local KV',run_score:'Compute attention scores',run_normalize:'Joint softmax',run_output:'Weighted output',run_done:'Done',hint_project:'Produce the main query and, when present, indexer queries.',hint_index:'Read indexer K and compute scores. Main KV has not been read yet.',hint_select:'Produce position IDs only; unselected cache records remain resident.',hint_read:'Highlighted records enter the existing attention matrix. Completed reads receive checkmarks.',hint_score:'Use the main query to score the records already read.',hint_normalize:'Normalize jointly over the same read set to obtain record weights.',hint_output:'Accumulate values with their weights. Reveal the output vector only on completion.',hint_done:'This position is complete. Advance to the next position, or stop at the final position.'}
};
export function ExecutionControls({finished,position,limit,onPosition,e,playing,stepDelay,onSpeedChange,onPlay,onStep,onReplay,onOverview,t}) {
 return <div className="se-controls"><div className="se-heading"><strong>{t('runTitle')}</strong><div className="se-actions"><select aria-label={t('runSpeed')} value={stepDelay} onChange={event=>onSpeedChange(Number(event.target.value))}>{[[250,'runRapid'],[500,'runHalf'],[6000,'runSlow'],[2000,'runNormal'],[1500,'runFast'],[1000,'runQuick']].map(([value,key])=><option key={value} value={value}>{t(key)}</option>)}</select><button onClick={onPlay} aria-label={t(playing?'runPause':'runPlay')} title={t(playing?'runPause':'runPlay')}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><button onClick={onStep} disabled={finished} aria-label={t('runStep')} title={t('runStep')}><SkipForward size={16}/></button><button onClick={onReplay} aria-label={t('runReplay')} title={t('runReplay')}><RotateCcw size={16}/></button>{e.enabled&&<button disabled={playing} onClick={onOverview}>{t('runOverview')}</button>}</div></div>
 <div className="se-positions" role="group" aria-label={t('sequencePosition')}>{Array.from({length:limit},(_,i)=><button key={i} aria-pressed={position===i+1} onClick={()=>onPosition(i+1)}>{`T${i+1}`}</button>)}</div>
 <div className="se-phases">{e.phases.map(p=><span key={p.id} data-state={e.enabled?p.status:'overview'}>{e.enabled&&p.status==='passed'?'✓ ':''}{t(`run_${p.id}`)}</span>)}</div>
 <div className="se-status" role="status"><strong>{!e.enabled?t('runIdle'):e.done?t('runDone'):`${t('runNext')} · ${t(`run_${e.phase}`)}`}</strong>{e.enabled&&<span>{e.completed} / {e.total} · {t('runBytes')} <b>{(e.readBytes/1024).toFixed(2)} / {(e.targetBytes/1024).toFixed(2)} KiB</b></span>}</div>
 {e.enabled&&<p>{t(`hint_${e.phase}`)} {e.activeIds.join(' · ')}</p>}<small>{t('runScope')} {t('runTiming')}</small></div>;
}
