export const explorerI18n = {
  zh: {
    vectorAxes:'横轴：通道 0 · 纵轴：通道 1',
    compactAssumption:'相同字节假设：主记录 1 KiB，索引 128 B；读取量不是速度，可容纳历史不是有效上下文。',
    linkHint:'点击色条或分项，追踪到对应部件', noBranch:'此机制无此分支', locate:'查看部件',
    trendToggle:'展开三项趋势', trendClose:'收起趋势', trendHistory:'历史长度 1—64 · 固定尺度', trendBudget:'缓存预算 32 / 64 / 128 KiB', trendScope:'灰：全量参照 · 紫：当前机制 · 圆点：当前值',
    trendIndependent:'容量取决于预算和机制，不随当前历史长度变化。', trendWindow:'窗口饱和后固定；全局记录随完整组发布而增长。', trendDsa:'主缓存持续增长；选读减少主读取，索引仍扫描全部历史。',
    localImpact:'当前参数对应的资源', resident:'驻留', readNow:'读取', indexScan:'扫描', recordUnit:'条',
    impact_index:'调整 Top-K 只改变主读取与输出，缓存和容量保持不变。',
    impact_cache:'压缩组改变发布数量与历史表示，同时影响缓存、读取和容量。',
    impact_raw:'全部主 KV 仍驻留；选择只决定这一步读取哪些记录。',
    impact_local:'窗口扩大保留更多逐 token 细节，也增加驻留与读取。',
    impact_query:'切换 query 改变选择与权重，不改变缓存条数。',
    impact_attention:'全局与局部共同归一化；可从输出记录回溯来源。',
    viewing:'正在查看', fetched:'本次读取', notFetched:'本次未读', followTrace:'追踪记录', backSource:'回看来源', traceOutput:'查看输出贡献', traceIndex:'查看索引选择',
    sortLabel:'记录排列', positionOrder:'按位置', scoreOrder:'按分数', scoreScale:'条长：索引分数；勾号：本次读取；描边：正在查看。',
    recordTrace:'同一记录贯穿缓存、索引与输出', traceMissing:'这条记录未被本次读取，因此没有输出贡献；仍可回看缓存或索引。',
    tradeTitle:'省下资源，改变了哪些信息？', tradeOpen:'查看信息取舍', coverageTitle:'本次读取如何表示历史',
    direct:'逐 token 可寻址', summary:'仅由压缩项表示', missing:'本次未覆盖', coverageNote:'表示来源覆盖，不是信息保留率或语义质量。压缩来源被覆盖，也不等于能恢复原 token。',
    fullReference:'逐 token 全量参照', residentReference:'相同驻留 KV 全读', currentOutput:'当前输出', outputDistance:'与逐 token 参照的距离', selectionDistance:'只改变选择的距离',
    outputNote:'同一历史与主 query 的二维样例。距离只表示向量差异，不是准确率损失，也不保证随压缩率单调变化。',
    referenceCompressed:'逐 token 参照使用当前组的共享 K/V 投影；CSA 前组投影、压缩与选择均可能改变结果。驻留全读参照保持同一批 K/V，只移除 Top-K。',
    referenceDsa:'逐 token 参照与 DSA 使用完全相同的 K/V 和 query，只移除选择。',
    trainedNotice:'真实机制需要相应训练与评测；索引器需学习主 attention 的选择分布。这里的固定投影没有训练。',
    contribution:'对输出的贡献', sourcePreview:'来源位置', compressionResult:'来源的加权和',
    historyControl:'在此调整历史长度', queryControl:'在此切换 query',
  },
  en: {
    vectorAxes:'Horizontal: channel 0 · vertical: channel 1',
    compactAssumption:'Shared assumptions: 1 KiB per main record, 128 B per index. Read bytes are not speed; capacity is not effective context.',
    linkHint:'Select a segment or item to inspect its component', noBranch:'No such branch in this mechanism', locate:'Inspect component',
    trendToggle:'Show all three trends', trendClose:'Hide trends', trendHistory:'History 1–64 · fixed scale', trendBudget:'Cache budget 32 / 64 / 128 KiB', trendScope:'Gray: full reference · purple: current · dot: current value',
    trendIndependent:'Capacity depends on budget and mechanism, not current history length.', trendWindow:'The window saturates; global records grow as complete groups publish.', trendDsa:'Main residency grows; selection saves main reads while indexing scans all history.',
    localImpact:'Resources for these parameters', resident:'Stored', readNow:'Read', indexScan:'Scan', recordUnit:'records',
    impact_index:'Top-K changes main reads and output only; cache memory and capacity stay fixed.',
    impact_cache:'Group size changes publication and representation, affecting memory, reads and capacity.',
    impact_raw:'All main KV stays resident; selection determines only which records this step reads.',
    impact_local:'A wider window retains more per-token detail and costs more storage and reads.',
    impact_query:'Changing the query changes selection and weights, not cache record counts.',
    impact_attention:'Global and local normalize together. Trace output records back to their sources.',
    viewing:'Inspecting', fetched:'Read this step', notFetched:'Not read this step', followTrace:'Trace record', backSource:'Back to source', traceOutput:'Inspect output contribution', traceIndex:'Inspect selection',
    sortLabel:'Record order', positionOrder:'Position', scoreOrder:'Score', scoreScale:'Length: index score; check: read this step; outline: inspecting.',
    recordTrace:'Keep record identity across cache, index and output', traceMissing:'This record was not read and contributes nothing this step. Its cache and index remain inspectable.',
    tradeTitle:'What information changes when resources shrink?', tradeOpen:'Inspect information tradeoffs', coverageTitle:'How this read set represents history',
    direct:'Individually addressable', summary:'Compressed sources only', missing:'Not covered this step', coverageNote:'Source coverage is not information retention or semantic quality. Coverage by compression does not imply token recovery.',
    fullReference:'Per-token full reference', residentReference:'Read all resident KV', currentOutput:'Current output', outputDistance:'Distance from per-token reference', selectionDistance:'Selection-only distance',
    outputNote:'A 2D example with the same history and main query. Distance is not accuracy loss and need not increase monotonically with compression.',
    referenceCompressed:'The per-token reference uses current-group shared K/V projections. Previous-group projections in CSA, compression and selection can all affect output. The resident reference keeps identical KV and only removes Top-K.',
    referenceDsa:'The per-token reference uses exactly the same KV and query as DSA, with selection removed.',
    trainedNotice:'Real mechanisms need training and evaluation; the indexer learns the main attention selection distribution. These fixed example projections are untrained.',
    contribution:'Output contribution', sourcePreview:'Source positions', compressionResult:'Weighted sum of sources',
    historyControl:'Adjust history here', queryControl:'Switch query here',
  },
};
