export const matrixI18n = {
  zh: {
    matrixQuery: '同一份历史，换个问题', changeQuery: '换个问题',
    matrixQueryHint: 'Query 决定这一步要找什么；观察选行与权重怎样改变。',
    querySelected: '选中的全局记录', queryAllRead: '全部记录参与，权重随问题改变',
    jointReadSet: '共同参与 Attention', readRows: '行',
    matrixBoundary: '二维合成样例：颜色与数值表示特征，不代表真实模型维度或显存大小。',
    matrixLegend: '紫：正值 · 橙：负值 · ✓：本次读取 · 描边：正在追踪',
    matrixAction: '点击整个色块查看原理；点击矩阵行追踪来源与输出。',
    matrixOmitted: '省略行', matrixDimensions: '完整矩阵形状', matrixRows: '记录',
    matrixShared: '共享 K/V', matrixSeparate: '逻辑 K、V', matrixIndex: '独立索引 key → 分数',
    matrixJoint: '汇集 K/V → 打分 → 联合 softmax → 加权求和',
    matrixWeight: '权重', matrixLogit: '打分', matrixScore: '索引分数',
    matrixValues: '值', matrixKey: '键', matrixQueryOutput: '投影后的 Query',
    matrixQueryNote: 'Query 表示当前这一步要找什么。本例用两组预设向量模拟不同提问，不是真实文本编码；主 Query 与索引 Query 独立投影。',
    matrixAllWeights: '显示的权重按全部读取行归一化，省略行仍参与计算。',
    matrixSource: '当前追踪的来源', matrixRead: '本次读取', matrixResident: '仅驻留',
    matrixPending: '等待完整组', matrixSourceHint: '实线框：当前组来源 · 虚线框：前组来源',
    matrixOutput: '加权输出', matrixProjected: '当前状态 → 独立投影',
    matrixLocal: '最近逐 token 记录', matrixSelect: '按选中 ID 汇集主 K/V',
    matrixHead: '主 / 索引 Query', matrixEmpty: '暂无已发布记录',
    matrixNarrowKeys: '窄图显示 K；对应 V 在下方汇合矩阵中查看。',
    matrixIndependent: '历史 → 独立索引投影',
    alignedTitle: '同一条记录：保存什么、如何选中', alignedIndependent: '主缓存与索引从历史独立投影；按 ID 对齐展示。',
    alignedGlobal: '全局分支', alignedLocal: '局部分支', alignedMainRead: '主读取', alignedScan: '索引扫描',
    alignedToIndex: '用于索引选行', alignedToAttention: '用于汇合打分', alignedGather: '按 ID 取主 K/V，与局部记录一起汇合',
    alignedAllLocal: '保留近期细节 · 全部读取', alignedOpenCache: '查看主缓存', alignedOpenIndex: '查看索引分数',
    alignedNoIndex: '全局记录全部读取', alignedHistory: '同一段历史，进入下方并行分支',
    flowParallel: '两条并行分支，共同参与一次 Attention', flowSingle: '索引选行后，读取对应的主 K/V',
    flowGlobalIn: '历史 → 全局投影', flowLocalIn: '近期历史 → 局部窗口',
    flowGlobalOut: '全局读取', flowLocalOut: '局部读取', flowMerge: '合并两路读取',
    sameMap: '同一张结构图', fitMap: '适配画布', actualMap: '原尺寸查看', expandMap: '放大整体图',
    selectedIds: '选中 ID', idsNotValues: '只传 ID → 按 ID 读取主 K/V', mainStoresValues: '保存主 K/V',
    separateStorage: '索引用来选行，主缓存保存内容；两者从历史独立投影。',
    storageScale: '存储占用 · 按字节比例',
    storageScaleNote: '本例主记录 1 KiB、索引 key 128 B；条长表示占用，二维矩阵格数不表示显存。',
  },
  en: {
    matrixQuery: 'Same history, a different question', changeQuery: 'Change the question',
    matrixQueryHint: 'The Query specifies what to look for. Watch selected rows and weights change.',
    querySelected: 'Selected global records', queryAllRead: 'All records participate; the question changes their weights',
    jointReadSet: 'Attend together', readRows: 'rows',
    matrixBoundary: 'Synthetic 2D example: cells encode features, not checkpoint dimensions or memory size.',
    matrixLegend: 'Purple: positive · Orange: negative · ✓: read now · Outline: traced',
    matrixAction: 'Open any colored block for principles; select a matrix row to trace sources and output.',
    matrixOmitted: 'omitted rows', matrixDimensions: 'Full matrix shape', matrixRows: 'Records',
    matrixShared: 'Shared K/V', matrixSeparate: 'Logical K and V', matrixIndex: 'Independent index keys → scores',
    matrixJoint: 'Gather K/V → score → joint softmax → weighted sum',
    matrixWeight: 'Weight', matrixLogit: 'Logit', matrixScore: 'Index score',
    matrixValues: 'Values', matrixKey: 'Keys', matrixQueryOutput: 'Projected Query',
    matrixQueryNote: 'The Query specifies what this step looks for. Two preset vectors simulate different questions, not actual text encoding. Main and index queries use separate projections.',
    matrixAllWeights: 'Weights use every fetched row; omitted rows still participate in normalization.',
    matrixSource: 'Sources of the traced record', matrixRead: 'Read now', matrixResident: 'Resident only',
    matrixPending: 'Waiting for a complete group', matrixSourceHint: 'Solid outline: current-group source · Dashed: previous-group source',
    matrixOutput: 'Weighted output', matrixProjected: 'Current state → separate projections',
    matrixLocal: 'Recent per-token records', matrixSelect: 'Gather main K/V by selected IDs',
    matrixHead: 'Main / index Query', matrixEmpty: 'No published records yet',
    matrixNarrowKeys: 'Narrow view shows K; matching V appears in the gathered matrix below.',
    matrixIndependent: 'History → independent index projection',
    alignedTitle: 'One record: stored values and selection', alignedIndependent: 'Main and index projections are independent; IDs align the views.',
    alignedGlobal: 'Global branch', alignedLocal: 'Local branch', alignedMainRead: 'Main read', alignedScan: 'Index scan',
    alignedToIndex: 'For index selection', alignedToAttention: 'For attention scores', alignedGather: 'Fetch main K/V by ID and merge with local records',
    alignedAllLocal: 'Recent detail · read all', alignedOpenCache: 'Inspect main cache', alignedOpenIndex: 'Inspect index score',
    alignedNoIndex: 'Read every global record', alignedHistory: 'Shared history feeds the parallel branches below',
    flowParallel: 'Parallel branches contribute to one attention operation', flowSingle: 'Select IDs, then fetch their main K/V',
    flowGlobalIn: 'History → global projections', flowLocalIn: 'Recent history → local window',
    flowGlobalOut: 'Global reads', flowLocalOut: 'Local reads', flowMerge: 'Join both read paths',
    sameMap: 'Same structure', fitMap: 'Fit canvas', actualMap: 'Actual size', expandMap: 'Expand overview',
    selectedIds: 'Selected IDs', idsNotValues: 'IDs only → fetch main K/V by ID', mainStoresValues: 'Stores main K/V',
    separateStorage: 'The index selects rows; the main cache stores content. Both project history independently.',
    storageScale: 'Storage · proportional bytes',
    storageScaleNote: 'Example: 1 KiB/main record, 128 B/index key. Bar length encodes storage; 2D cell counts do not.',
  },
};
