export const matrixI18n = {
  zh: {
    sharedExperiment: "共享实验条件",
    sharedExperimentHint: "历史长度同步作用于计算对照、收益和结构图",
    benefitQuestion: "计算差异带来哪些收益与代价？",
    structureQuestion: "缓存从哪里来，如何参与查询？",
    structureBridge: "以下沿一个 Query 钻取：历史表示 → 缓存组织与读取 → Attention 输出。",
    parameterBank: "模型权重",
    queryParameterGroup: "Query 路径：降维、主分支、索引分支",
    scoreParameterGroup: "独立系数分支",
    parameterRef: "引用固定参数",
    normalizeLabel: "归一化",
    focus_history: "历史隐藏状态：缓存的来源",
    in_history: "此前各位置的上下文表示",
    out_history: "投影后的 K/V 与索引 Key",
    desc_history: "这里是历史 Token 的隐藏状态来源，不是已经保存好的全局 KV 缓存。",
    historyIdentity: "每个历史位置都有一个隐藏向量，包含该位置截至当时的上下文信息。把这些向量按位置排列，才得到这里表示的历史隐藏状态。",
    historyDerivation: "隐藏状态如何变成缓存？",
    historyProjection: "历史位置经过对应的投影，产生主 K/V；有索引器时还生成独立的索引 Key。变换后的缓存与原始隐藏状态不是同一对象，形状与数值也不应混为一谈。",
    historyCompressed: "当前压缩模式还会把多个位置的投影结果汇成压缩记录。T 表示来源位置，C 表示压缩记录；二者不一一对应。",
    historyUncompressed: "当前未压缩模式中，Token 位置与缓存条目可以按位置对应，但隐藏状态和缓存仍是不同表示。",
    historyResidency: "图中的历史隐藏状态用于说明来源，不表示推理引擎长期保存了整段隐藏状态。解码通常复用已保存的 KV，而不是每步重投影全部历史。",
    inspectDerivedCache: "查看派生出的全局缓存",

    pgFixed: "固定参数",
    pgDynamic: "当前数据",
    pgMultiply: "矩阵乘法",
    pgNorm: "乘法 + 归一化",
    pgScore: "打分系数",
    pgReference: "完整投影参考",
    pgSelect: "点击节点查看输入、参数与输出",
    pg_hidden: "当前隐藏状态",
    pg_down: "降维与归一化",
    pg_latent: "共享 Query 中间表示",
    pg_main: "主 Query 分支",
    pg_index: "索引 Query 分支",
    pg_score: "索引头打分系数",
    pgDesc_hidden: "这是本层处理当前 Token 的输入。它既进入 Query 降维路径，也直接进入索引头系数的投影路径。切换问题会改变当前数据，模型参数保持不变。",
    pgDesc_down: "左侧固定的降维矩阵与上方当前隐藏状态共同输入运算。先做矩阵乘法，再归一化，得到下方中间表示。",
    pgDesc_latent: "这个动态中间表示同时送入主分支和索引分支；连线分叉表示复用同一份输入，而不是复制或派生两组参数。",
    pgDesc_main: "固定的主投影矩阵与共享中间表示相乘，输出主 Query。随后它与读取到的主 K 计算 Attention 分数。",
    pgDesc_index: "固定的索引投影矩阵与同一个中间表示相乘，再拆成两个索引头。矩阵内的两个行块对应两个头；不是两个请求或两个执行阶段。",
    pgDesc_score: "该分支直接读取当前隐藏状态，使用另一组固定投影参数生成每头的打分系数。系数用于合并索引头分数，不是投影矩阵，也不是最终 Softmax 权重。这里的 0.7 / 0.3 仍是固定教学示例。",
    pgFixture: "数值为教学样例；符号节点表示来源，不虚构隐藏状态或模型参数值。",

    weightOrigin: "先区分：模型参数和当前数据",
    weightLifecycle: "训练中学习参数 → 保存到模型权重文件 → 推理时加载并重复使用。同一层、同一模型版本处理不同 Token 时，投影矩阵保持不变；变化的是输入和算出的 Query。不同层通常有各自的参数。",
    weightSymbol: "投影参数",
    weightJob: "作用与来源",
    weightDown: "降维矩阵：把当前隐藏状态变成较小的 Query 中间表示。不是数字 0，而是 down（降维）。",
    weightMain: "主 Query 投影矩阵：读取共享中间表示，生成用于正式注意力计算的 Query。main 表示主分支。",
    weightHeadOne: "索引投影的第 1 个头所对应的输出行块。把相同的中间表示映射到第 1 个索引头。",
    weightHeadTwo: "同一个索引投影的第 2 个输出行块，参数值与第 1 头不同。下标是头编号，不是计算步骤。",
    weightRelation: "三类投影的关系是串联后分叉：先降维，再分别走主分支与索引分支。主矩阵和索引矩阵不是由降维矩阵计算出来的；它们是分别存储的可训练参数，共享的是中间数据。",
    weightStack: "实现通常一次计算所有索引头，再 reshape 拆头。下面按两个头展示同一个索引矩阵的分块关系；不是依次执行第 1 头、第 2 头。",
    weightNotation: "上标表示 Index（索引），不是单位矩阵、乘方或额外一组权重。",
    weightNotScore: "下面索引打分里出现的每头系数又是另一类量：它是由当前隐藏状态经过另一组训练好的参数算出的标量，不是这里的投影矩阵，也不是最终 Attention 权重。",
    weightFixed: "推理时固定：投影矩阵",
    weightDynamic: "随当前 Token 变化：隐藏状态、中间表示与 Query",

    latentLabel: "Query 中间表示",
    hiddenLabel: "当前隐藏状态",
    downLabel: "降维 + 归一化",
    branchLabel: "独立投影",
    latentWhat: "1 · 这个中间表示是什么？",
    latentDefinition: "表示当前 Token 的低维 Query 特征，是两条投影分支共用的输入。上标表示 Query 路径；它不是历史 KV 缓存，也不是多个 Token 压成的一条记录。",
    latentFrom: "2 · 它从哪里来？",
    hiddenDefinition: "来自模型上一层在当前 Token 位置的输出，概括截至当前位置的上下文信息。",
    downDefinition: "降维矩阵把隐藏维度映射到较小的中间维度；再经过 RMSNorm 稳定数值尺度。矩阵参数由训练学得，不是在推理时临时拼出来的。",
    latentTo: "3 · 同一个输入，怎样产生不同 Query？",
    branchDefinition: "主分支乘主 Query 投影矩阵；索引分支乘另一组投影矩阵，再按头拆开。输入相同，矩阵参数不同，所以结果不同。这里列出两个索引头。",
    dimHidden: "隐藏维度",
    dimLatent: "中间维度",
    dimMain: "主 Query 维度",
    dimIndex: "每个索引头的维度",
    projectionScope: "这里展开 DeepSeek 低秩 Query 路径，省略后续位置编码和数值变换。图中二维输出是预设教学样例；没有提供真实隐藏状态或权重，因此不声称这些数值由上述矩阵实际算得。",
    projectionSource: "查看官方投影实现",
    projectionResult: "4 · 投影结果流向哪里？",

    queryLatentPlain: "当前 Token 的隐藏状态经过投影，形成主 Query；投影是学习到的线性变换。",
    queryRolePlain: "主 Query 为本次读取的记录计算注意力权重；此模式没有索引选行。",
    mainQueryLabel: "主 Query",
    indexHeadLabel: "索引头",
    queryRoles: "同一次查询：主 Query 决定内容权重，索引 Query 先挑读取位置。",
    tokenIds: "T1、T2、T3 = 第 1、2、3 个 Token 位置，不是请求编号或词表 ID。",
    compressedIds: "C1、C2 = 压缩记录编号；一条记录来自多个 Token，点击可追踪来源。",
    indexKeyLabel: "索引 Key：每条历史记录的检索特征",
    indexKeyHint: "上标 I 表示 Index（索引），不是乘方；小写 k 表示一条记录的向量，大写 K 表示所有记录组成的矩阵。两个索引头都匹配同一条记录的索引 Key；它与主注意力的 K/V 分开保存。",
    indexShort: "索引 Key 是历史记录的检索特征；两个索引头的贡献相加，再按总分选位置。",
    queryLatent: "h 是当前 Token 的隐藏状态；投影是学习到的线性变换。cQ 是共享的 Query 中间表示，再分别生成主 Query 和索引 Query。",
    headsMeaning: "上标 I 表示索引；下标 1、2 表示同一次查询的两个索引头，不是两个请求。此处用两个二维头作演示，数值预设且未经训练。",
    mainKVHint: "主 K 用来与主 Query 计算相关性；V 是最终按注意力权重汇总的内容。每个向量只画两个特征，不是两个 Token。",
    headCalculation: "逐头计算这条记录的分数",
    headWeightHint: "d 表示该头的内积。每行：内积 → 负值置零（ReLU）→ 乘头权重。示例权重固定为 0.7 / 0.3；真实模型由当前状态生成。",
    indexResult: "贡献相加得到索引总分，再与其他记录比较。单独的 I 表示这个总分，不是最终 Attention 权重。",
    tracePositions: "来源 Token 位置",
    indexReadResult: "选中只产生记录 ID → 按 ID 读取主 K/V → 主 Query 打分 → Softmax → 加权汇总 V。",
    vectorMeaning: "每对数字是一个向量的两个特征维度；颜色表示正负，不是概率。",

    matrixQuery: '同一份历史，换个问题', changeQuery: '换个问题',
    matrixQueryHint: 'Query 决定这一步要找什么；观察选行与权重怎样改变。',
    querySelected: '选中的全局记录', queryAllRead: '全部记录参与，权重随问题改变',
    jointReadSet: '共同参与 Attention', readRows: '行',
    matrixBoundary: '二维合成样例：颜色与数值表示特征，不代表真实模型维度或显存大小。',
    matrixLegend: '紫：正值 · 橙：负值 · ✓：本次读取 · 描边：正在追踪',
    matrixAction: '点击整个色块查看原理；点击矩阵行追踪来源与输出。',
    matrixOmitted: '省略行', matrixDimensions: '完整矩阵形状', matrixRows: '记录',
    matrixShared: '共享 K/V', matrixSeparate: '逻辑 K、V', matrixIndex: '独立索引 key → 分数',
    matrixJoint: '汇集 K/V → 打分 → 联合 softmax → 加权求和',
    matrixWeight: '权重', matrixLogit: '打分', matrixScore: '索引分数',
    matrixValues: '值', matrixKey: '键', matrixQueryOutput: '投影后的 Query',
    matrixQueryNote: 'Query 表示当前这一步要找什么。本例用两组预设向量模拟不同提问，不是真实文本编码；主 Query 与索引 Query 独立投影。',
    matrixAllWeights: '显示的权重按全部读取行归一化，省略行仍参与计算。',
    matrixSource: '当前追踪的来源', matrixRead: '本次读取', matrixResident: '仅驻留',
    matrixPending: '等待完整组', matrixSourceHint: '实线框：当前组来源 · 虚线框：前组来源',
    matrixOutput: '加权输出', matrixProjected: '当前状态 → 独立投影',
    matrixLocal: '最近逐 token 记录', matrixSelect: '按选中 ID 汇集主 K/V',
    matrixHead: '主 / 索引 Query', matrixEmpty: '暂无已发布记录',
    matrixNarrowKeys: '窄图显示 K；对应 V 在下方汇合矩阵中查看。',
    matrixIndependent: '历史 → 独立索引投影',
    alignedTitle: '同一条记录：保存什么、如何选中', alignedIndependent: '主缓存与索引从历史独立投影；按 ID 对齐展示。',
    alignedGlobal: '全局分支', alignedLocal: '局部分支', alignedMainRead: '主读取', alignedScan: '索引扫描',
    alignedToIndex: '用于索引选行', alignedToAttention: '用于汇合打分', alignedGather: '按 ID 取主 K/V，与局部记录一起汇合',
    alignedAllLocal: '保留近期细节 · 全部读取', alignedOpenCache: '查看主缓存', alignedOpenIndex: '查看索引分数',
    alignedNoIndex: '全局记录全部读取', alignedHistory: '同一段历史，进入下方并行分支',
    flowParallel: '两条并行分支，共同参与一次 Attention', flowSingle: '索引选行后，读取对应的主 K/V',
    flowGlobalIn: '历史 → 全局投影', flowLocalIn: '近期历史 → 局部窗口',
    flowGlobalOut: '全局读取', flowLocalOut: '局部读取', flowMerge: '合并两路读取',
    sameMap: '同一张结构图', fitMap: '适配画布', actualMap: '原尺寸查看', expandMap: '放大整体图',
    selectedIds: '选中 ID', idsNotValues: '只传 ID → 按 ID 读取主 K/V', mainStoresValues: '保存主 K/V',
    separateStorage: '索引用来选行，主缓存保存内容；两者从历史独立投影。',
    storageScale: '存储占用 · 按字节比例',
    storageScaleNote: '本例主记录 1 KiB、索引 key 128 B；条长表示占用，二维矩阵格数不表示显存。',
  },
  en: {
    sharedExperiment: "Shared experiment settings",
    sharedExperimentHint: "History length drives the comparison, benefits and architecture",
    benefitQuestion: "What are the benefits and costs?",
    structureQuestion: "Where does the cache come from, and how is it queried?",
    structureBridge: "Follow one query: historical representations → cache organization and reads → attention output.",
    parameterBank: "Model weights",
    queryParameterGroup: "Query path: down, main and index projections",
    scoreParameterGroup: "Separate coefficient branch",
    parameterRef: "Reference parameter",
    normalizeLabel: "Normalize",
    focus_history: "Historical hidden states: cache provenance",
    in_history: "Context representations at earlier positions",
    out_history: "Projected K/V and index keys",
    desc_history: "These are the hidden-state sources for historical tokens, not the resident global KV cache.",
    historyIdentity: "Each historical position has a hidden vector representing its context at that position. Arranging those vectors by position gives the historical hidden states shown here.",
    historyDerivation: "How do hidden states become cache records?",
    historyProjection: "Projections produce main K/V from each position, plus separate index keys when an indexer is present. Transformed caches and source hidden states are different objects; their shapes and values must not be conflated.",
    historyCompressed: "This compression mode also combines projected positions into compressed records. T identifies source positions; C identifies compressed records, without a one-to-one mapping.",
    historyUncompressed: "In this uncompressed mode, token positions can align with cache entries, but hidden states and cache records are still different representations.",
    historyResidency: "The history strip explains provenance; it does not imply that the engine retains every hidden state. Decode normally reuses cached KV instead of projecting the entire history again.",
    inspectDerivedCache: "Inspect the derived global cache",

    pgFixed: "Fixed parameters",
    pgDynamic: "Current data",
    pgMultiply: "Matrix multiply",
    pgNorm: "Multiply + normalize",
    pgScore: "Scoring coefficients",
    pgReference: "Full projection reference",
    pgSelect: "Select a node for its inputs, parameters and output",
    pg_hidden: "Current hidden state",
    pg_down: "Down-project and normalize",
    pg_latent: "Shared query latent",
    pg_main: "Main-query branch",
    pg_index: "Index-query branch",
    pg_score: "Index-head scoring coefficients",
    pgDesc_hidden: "The input at the current token position feeds both query down-projection and the separate index-head coefficient projection. Changing the question changes data, not model parameters.",
    pgDesc_down: "The fixed down-projection on the left and the current hidden state above feed the operation. Matrix multiplication followed by normalization produces the latent below.",
    pgDesc_latent: "The same dynamic intermediate feeds both main and index branches. The fork reuses input data; it does not duplicate or derive parameter matrices.",
    pgDesc_main: "The fixed main projection multiplies the shared intermediate to produce the main query, which later scores the main keys that were read.",
    pgDesc_index: "One fixed index projection multiplies the same intermediate and splits its output into two heads. Two row blocks correspond to heads, not requests or sequential stages.",
    pgDesc_score: "This branch reads the current hidden state directly. Another fixed learned projection produces per-head score coefficients. They combine index-head scores; they are neither projection matrices nor final softmax weights. Values 0.7 / 0.3 remain fixed teaching fixtures.",
    pgFixture: "Numbers are teaching fixtures; symbolic nodes show provenance without inventing hidden states or parameter values.",

    weightOrigin: "First separate model parameters from current data",
    weightLifecycle: "Learn parameters during training → save them in the checkpoint → load and reuse them for inference. For one layer and model version, projection matrices stay fixed across tokens; inputs and resulting queries change. Different layers generally own different parameters.",
    weightSymbol: "Projection parameter",
    weightJob: "Role and origin",
    weightDown: "Down-projection: maps the current hidden state into a smaller query intermediate. The label is down, not the number zero.",
    weightMain: "Main-query projection: maps the shared intermediate to queries used by attention. The label main identifies the main branch.",
    weightHeadOne: "Output-row block for head 1 of the index-query projection. It maps the shared intermediate into the first index head.",
    weightHeadTwo: "Output-row block for head 2 of that same index projection, with different parameter values. Subscripts identify heads, not execution steps.",
    weightRelation: "The dependency is a down-projection followed by two branches. Main and index matrices are not computed from the down-projection matrix: they are separately stored, trainable parameters. They share intermediate data.",
    weightStack: "Implementations usually project all index heads at once and reshape to split them. This two-head illustration shows row blocks of one index matrix, not sequential head execution.",
    weightNotation: "The superscript means Index, not an identity matrix, a power or another set of weights.",
    weightNotScore: "The per-head coefficient used later in index scoring is a different quantity: a scalar derived from the current hidden state by another learned projection. It is neither the query projection matrix nor the final attention weight.",
    weightFixed: "Fixed during inference: projection matrices",
    weightDynamic: "Changes per token: hidden state, intermediate and queries",

    latentLabel: "Query latent",
    hiddenLabel: "Current hidden state",
    downLabel: "Down-project + normalize",
    branchLabel: "Separate projections",
    latentWhat: "1 · What is this intermediate?",
    latentDefinition: "is a low-dimensional query representation of the current token, shared as the input to both projection branches. The superscript identifies the query path. It is neither historical KV nor a record combining multiple tokens.",
    latentFrom: "2 · Where does it come from?",
    hiddenDefinition: "comes from the preceding layer at the current token position and represents the context up to that position.",
    downDefinition: "A learned down-projection maps the hidden dimension to a smaller latent dimension; RMSNorm then stabilizes its scale. These weights are learned during training, not assembled at inference time.",
    latentTo: "3 · How does one input produce different queries?",
    branchDefinition: "The main branch multiplies by its query projection matrix. The index branch uses separate matrices, with outputs split into heads. Shared input and different learned weights produce different queries. Two index heads are shown here.",
    dimHidden: "Hidden dimension",
    dimLatent: "Latent dimension",
    dimMain: "Main-query dimension",
    dimIndex: "Dimension per index head",
    projectionScope: "This expands DeepSeek’s low-rank query path, omitting subsequent positional encoding and numeric transforms. The 2D outputs are preset teaching fixtures: no actual hidden states or weights are supplied, so these numbers are not claimed to result from the displayed matrix equations.",
    projectionSource: "Official projection implementation",
    projectionResult: "4 · Where do the outputs go?",

    queryLatentPlain: "Project the current token’s hidden state into the main query. Projection is a learned linear transformation.",
    queryRolePlain: "Main query computes attention weights for the read records; this mode has no index selection.",
    mainQueryLabel: "Main query",
    indexHeadLabel: "Index head",
    queryRoles: "One query: main Q weights content; index queries first select positions to read.",
    tokenIds: "T1, T2, T3 = token positions 1, 2, 3, not request numbers or vocabulary IDs.",
    compressedIds: "C1, C2 = compressed record IDs. Each combines multiple tokens; click to trace sources.",
    indexKeyLabel: "Index key: retrieval features of a history record",
    indexKeyHint: "Superscript I means Index, not a power; lowercase k is one record’s vector, uppercase K is the matrix of all records. Both index heads match the same record’s index key, stored separately from main attention K/V.",
    indexShort: "Index keys describe history for retrieval. Add both heads’ contributions, then select positions by total score.",
    queryLatent: "h is the current token’s hidden state. Projection is a learned linear transformation. cQ is a shared query intermediate, projected separately into main and index queries.",
    headsMeaning: "Superscript I means index; subscripts 1 and 2 identify heads of one query, not two requests. Two 2D heads are a teaching example with preset, untrained values.",
    mainKVHint: "Main K determines relevance to the main query; V supplies the content combined by attention weights. Two displayed features do not mean two tokens.",
    headCalculation: "Compute this record’s score head by head",
    headWeightHint: "d is the head’s dot product. Each row: dot product → clamp negatives to zero (ReLU) → multiply by head weight. Example weights are fixed at 0.7 / 0.3; the real model derives them from the current state.",
    indexResult: "Add contributions, then compare this index score with other records. Standalone I denotes this score, not the final attention weight.",
    tracePositions: "Source token positions",
    indexReadResult: "Selected IDs → read main K/V at those IDs → main-query scores → softmax → weighted sum of V.",
    vectorMeaning: "Each pair of numbers is two vector features. Colors show signs, not probabilities.",

    matrixQuery: 'Same history, a different question', changeQuery: 'Change the question',
    matrixQueryHint: 'The Query specifies what to look for. Watch selected rows and weights change.',
    querySelected: 'Selected global records', queryAllRead: 'All records participate; the question changes their weights',
    jointReadSet: 'Attend together', readRows: 'rows',
    matrixBoundary: 'Synthetic 2D example: cells encode features, not checkpoint dimensions or memory size.',
    matrixLegend: 'Purple: positive · Orange: negative · ✓: read now · Outline: traced',
    matrixAction: 'Open any colored block for principles; select a matrix row to trace sources and output.',
    matrixOmitted: 'omitted rows', matrixDimensions: 'Full matrix shape', matrixRows: 'Records',
    matrixShared: 'Shared K/V', matrixSeparate: 'Logical K and V', matrixIndex: 'Independent index keys → scores',
    matrixJoint: 'Gather K/V → score → joint softmax → weighted sum',
    matrixWeight: 'Weight', matrixLogit: 'Logit', matrixScore: 'Index score',
    matrixValues: 'Values', matrixKey: 'Keys', matrixQueryOutput: 'Projected Query',
    matrixQueryNote: 'The Query specifies what this step looks for. Two preset vectors simulate different questions, not actual text encoding. Main and index queries use separate projections.',
    matrixAllWeights: 'Weights use every fetched row; omitted rows still participate in normalization.',
    matrixSource: 'Sources of the traced record', matrixRead: 'Read now', matrixResident: 'Resident only',
    matrixPending: 'Waiting for a complete group', matrixSourceHint: 'Solid outline: current-group source · Dashed: previous-group source',
    matrixOutput: 'Weighted output', matrixProjected: 'Current state → separate projections',
    matrixLocal: 'Recent per-token records', matrixSelect: 'Gather main K/V by selected IDs',
    matrixHead: 'Main / index Query', matrixEmpty: 'No published records yet',
    matrixNarrowKeys: 'Narrow view shows K; matching V appears in the gathered matrix below.',
    matrixIndependent: 'History → independent index projection',
    alignedTitle: 'One record: stored values and selection', alignedIndependent: 'Main and index projections are independent; IDs align the views.',
    alignedGlobal: 'Global branch', alignedLocal: 'Local branch', alignedMainRead: 'Main read', alignedScan: 'Index scan',
    alignedToIndex: 'For index selection', alignedToAttention: 'For attention scores', alignedGather: 'Fetch main K/V by ID and merge with local records',
    alignedAllLocal: 'Recent detail · read all', alignedOpenCache: 'Inspect main cache', alignedOpenIndex: 'Inspect index score',
    alignedNoIndex: 'Read every global record', alignedHistory: 'Shared history feeds the parallel branches below',
    flowParallel: 'Parallel branches contribute to one attention operation', flowSingle: 'Select IDs, then fetch their main K/V',
    flowGlobalIn: 'History → global projections', flowLocalIn: 'Recent history → local window',
    flowGlobalOut: 'Global reads', flowLocalOut: 'Local reads', flowMerge: 'Join both read paths',
    sameMap: 'Same structure', fitMap: 'Fit canvas', actualMap: 'Actual size', expandMap: 'Expand overview',
    selectedIds: 'Selected IDs', idsNotValues: 'IDs only → fetch main K/V by ID', mainStoresValues: 'Stores main K/V',
    separateStorage: 'The index selects rows; the main cache stores content. Both project history independently.',
    storageScale: 'Storage · proportional bytes',
    storageScaleNote: 'Example: 1 KiB/main record, 128 B/index key. Bar length encodes storage; 2D cell counts do not.',
  },
};
