export const executionCopy = {
 en: {
  title:'Trace one forward pass', play:'Play', pause:'Pause', next:'Next step', reset:'Replay', overview:'Back to overview',
  input:'Input ready', encoder:'Encoder checkpoints', projection:'Shared global cache written', window:'Decoder checkpoints', generation:'Output ready',
  inputBody:'Start with input positions. No new hidden states or cache records have been produced yet.',
  encoderBody:'Run the next five layers in order. The complete Encoder output becomes available after L20.',
  projectionBody:'Project the Encoder output and publish the shared Decoder global KV and index records once. Later layers read this same cache.',
  windowBody:'Run the next five Decoder layers in order: each writes its own local window, attends to local and shared global records, then forwards its hidden state.',
  generationBody:'All 40 layers have finished their assigned positions. The final hidden state can now produce logits; no next input token is advanced here.',
  ready:'Ready', active:'Partially ready', pending:'Not produced', schema:'Structure preview',
  scope:'2 seconds per checkpoint; five layers are sequential, not parallel. Prefill illustrates the report’s bounded-tail path; the public reference forward still loops through all layers. This is not a kernel timing trace.',
  preserved:'Existing global records', written:'New records written', resident:'Decoder global cache', layers:'Decoder layers updated', work:'Completed token-layer positions',
  localScope:'One shared Decoder global cache, including main KV + index storage. Encoder caches and per-layer local windows are excluded from this byte count. Reads do not allocate copies.',
  prefill:'Only the last up to 128 positions pass through Decoder layers; all positions feed the global projection.',
  decode:'Only the current position is new. Existing global records and local window state stay resident; every layer still runs.',
  shapeNote:'Matrix cells show structural slots. Dashed outputs are not ready; labels and progress bars show committed state.',
  target:'Other capacity and work comparisons on this page describe the completed target state.',
 },
 zh: {
  title:'追踪一次前向执行', play:'播放', pause:'暂停', next:'下一步', reset:'重播', overview:'返回结构总览',
  input:'输入已就绪', encoder:'Encoder 层间推进', projection:'共享全局缓存已写入', window:'Decoder 层间推进', generation:'输出已就绪',
  inputBody:'从输入位置开始。此时尚未产生本次的新隐藏状态或缓存记录。',
  encoderBody:'依次执行接下来的五层。直到 L20 完成，完整的 Encoder 输出才可供下游使用。',
  projectionBody:'投影 Encoder 输出，一次发布 Decoder 共用的全局 KV 与索引记录。后续层读取同一份缓存。',
  windowBody:'依次执行接下来的五个 Decoder 层：各层写自己的局部窗口，读取局部与共享全局记录完成注意力，再传递隐藏状态。',
  generationBody:'40 层已完成各自需要处理的位置，最终隐藏状态可以生成 logits；这里不自动推进下一个输入 Token。',
  ready:'已就绪', active:'部分就绪', pending:'尚未产生', schema:'结构预览',
  scope:'每个检查点停留 2 秒；五层是依次执行，并非并行。Prefill 展示报告中的有限尾部路径，公开参考 forward 仍逐层循环。本演示不是内核计时轨迹。',
  preserved:'原有全局记录', written:'本次新写记录', resident:'Decoder 全局缓存', layers:'已更新 Decoder 层', work:'已完成 Token × 层位置数',
  localScope:'这里只统计 Decoder 共用的一份全局缓存，含主 KV 与索引存储；不包含 Encoder 缓存和各层局部窗口。读取不会产生缓存副本。',
  prefill:'仅末尾至多 128 个位置进入 Decoder 各层；全量位置仍参与全局投影。',
  decode:'只有当前位置是新增输入。原有全局记录和局部窗口状态保留，当前 Token 仍经过全部层。',
  shapeNote:'矩阵格子表示结构槽位。虚线输出尚未就绪，标签和进度条表示已完成状态。',
  target:'页面其他容量和工作量对照展示的是执行完成后的目标状态。',
 },
};
