export const sessionCopy = {
  zh: {
    title:'一条会话：连续生成 → 暂存 → 恢复',
    hint:'跟踪同一批位置：全局记录持续增长，局部窗口只保留最近 128 个位置。点击缓存块查看原理；点击会话节点跳转。',
    first:'首次输入', tool:'工具返回 · 短间隔', return:'旧会话 · 超过局部 TTL',
    history:'初始输入沿用上方 Token 数', suffix:'新增输入', prefix:'已缓存前缀', input:'新输入', generated:'生成后送入模型', sequence:'位置序列',
    play:'播放会话', pause:'暂停会话', next:'会话下一步', reset:'重播会话', scrub:'会话进度',
    encoder:'Encoder · L1–L20', decoder:'Decoder · L21–L40', archive:'会话留存',
    global:'全局 KV + 索引 K', local:'各层独立 SWA', staging:'半组暂存', records:'记录', positions:'位置',
    read:'下游层读取同一份记录', publish:'写入新记录', unchanged:'已有全局记录不变', pending:'待配对', empty:'空', needState:'待恢复', newest:'当前窗口末位', leftBehind:'已移出局部窗口', approximate:'有限回放是近似恢复，需验证任务质量。', counters:'以下为本轮已完成的处理位置，不是总 FLOPs 或时延。',
    active:'本步', ready:'已完成', waiting:'待处理', saved:'长期保留', short:'Encoder · 短 TTL 检查点', discarded:'Decoder · 不长期保留',
    device:'GPU 工作集', backing:'会话缓存', resident:'局部状态就绪', absent:'GPU 未驻留', missing:'已过期', localPending:'局部待构建',
    globalMetric:'完整全局记录', deltaMetric:'本步新增', transferMetric:'本轮已回载的全局数据',
    repairMetric:'补 Encoder 局部状态', decoderMetric:'Decoder Prefill 位置',
    reference:'全文参照', unit:'token', perLayer:'每层', noRepair:'无需修复检查点',
    metricNote:'字节只计完整全局 KV 与索引 K（含 scale）；不含 SWA、半组、激活、对齐及复制开销。回载假设请求间 GPU 工作集释放；不是磁盘 IO 或延迟测量。',
    titleadmit:'接收输入，匹配前缀', titleload:'回载匹配前缀的全局记录', titlerestore:'取回仍有效的 Encoder 检查点',
    titlerepair:'仅回放前缀尾部，修复 Encoder SWA', titleencodeInput:'处理新增输入，发布增量全局记录',
    titlebuildTail:'建立 Decoder 尾部局部状态', titleencodeToken:'当前 token 进入 Encoder', titledecodeToken:'Decoder 写入并读取，完成当前 token',
    titlesave:'保存会话，释放请求工作集', titleexpire:'短 TTL 到期，Encoder 检查点丢失',
    noteadmit:'先区分匹配前缀与新增后缀。首轮没有前缀；后两轮引用同一会话已处理的位置。示例工具结果是 3 个 token，返回时追加 2 个 token。',
    noteload:'将已保存的压缩 KV 和索引 K 重新放入 GPU 工作集，沿用原来的记录地址。载入完成之后才允许后续读取；示例不模拟 HiCache 的分层传输调度。',
    noterestore:'短间隔续聊时，Encoder 局部检查点仍在，可恢复最近窗口和相关压缩器状态。这样避免的是“补 Encoder SWA”这项工作，并不意味着整轮无需计算。',
    noterepair:'从匹配前缀末尾最多 128 个位置重新计算局部状态。历史压缩 KV 与索引 K 只读，不能被近似回放的结果覆盖。缺失的半组工作状态也必须在继续追加前恢复。',
    noteencodeInput:'新增后缀经过 Encoder。L3、L9、L15 每两位置合成一条记录；奇数末尾保留半组，等待下一位置。各源层先发布记录，下游消费者再读取，不各存一份。',
    notebuildTail:'从 Encoder 尾部特征建立 Decoder 各层自己的 SWA，再开始生成。需要的旧尾部特征按需重新求值；“Encoder 检查点命中”不等于这些特征也已保存。本图不将特征求值算成免费，也不估算总 FLOPs。',
    noteencodeToken:'已采样的 token 送入下一次前向：先更新 Encoder 的本层窗口与三个压缩源。半组凑齐才发布完整记录。此时后半段尚未完成，序列的已处理位置不提前递增。',
    notedecodeToken:'L21 从 Encoder 输出建立当前位置的全局记录；后续层读取它并更新各自 SWA，最后输出下一 token 的 logits。局部窗口向前滑动，移出窗口的位置仍可留在全局压缩历史中。',
    notesave:'完整全局记录长期保留；Encoder 局部状态可用短 TTL 留存；Decoder 局部状态不长期保存。图中保存到“已执行前向”的末尾，尚未送入模型的采样结果不冒充缓存记录。',
    noteexpire:'这里只过期 Encoder 局部检查点，已有全局历史仍然命中。下一轮因此可以用有限尾部重算来恢复，而不必把整个前缀当作未命中输入。TTL 是教学场景，不指定真实服务的超时时间。',
    inspect:'当前检查对象', globalDetail:'四个所有者分别存储完整记录；源层内每条主 KV 288 B、索引 K 68 B。读取、恢复及回放不会制造副本；增量写入只来自真正的新位置。',
    localDetail:'上下两条窗口分别代表 Encoder 与 Decoder 的逐层局部状态，不是两份跨层共享缓存。每层最多 128 位置。网格按环形槽位排列，一格一个位置；末位用橙色标出，编号标注当前窗口的起止。',
    archiveDetail:'会话标识、前缀位置与全局记录共同确定恢复点。全局命中不保证本地状态就绪；图中回载、修复、后缀处理完成后才进入生成。若全局记录也未命中，则应走完整 Prefill，本轨迹不假装能靠回放找回它。',
    back:'跟随当前步骤', boundary:'近似与实现边界',
    boundaryNote:'有限回放截断了局部注意力的边界，重建结果不保证与完整 Prefill 数值相同。本画布按报告的 20+20 架构分组；SGLang 2026-09-10 实现把 L21 全局源留在完整输入路径，L22–L40 才做尾部计算，且按 Prefill chunk 截尾。此处是单 chunk、非投机生成的状态演示。',
    source:'依据：SGLang 的缓存共享与 bounded replay 实现说明', report:'DeepSeek 官方报告 · §2.2 / §3.2',
  },
  en: {
    title:'One session: generate → retain → resume',
    hint:'Follow the same positions: global records grow while each local window keeps at most 128. Inspect a cache block, or jump to a turn in the session.',
    first:'First input', tool:'Tool result · short gap', return:'Return · local TTL expired',
    history:'Initial input uses the token count above', suffix:'New input', prefix:'Cached prefix', input:'New input', generated:'Generated, then fed back', sequence:'Positions',
    play:'Play session', pause:'Pause session', next:'Next session step', reset:'Replay session', scrub:'Session progress',
    encoder:'Encoder · L1–L20', decoder:'Decoder · L21–L40', archive:'Session retention',
    global:'Global KV + index K', local:'Layer-local SWA', staging:'Partial pair', records:'records', positions:'positions',
    read:'Downstream layers read the same records', publish:'Publish new records', unchanged:'Existing global records unchanged', pending:'Awaiting pair', empty:'Empty', needState:'Needs recovery', newest:'Current window end', leftBehind:'Outside the local window', approximate:'Bounded replay is approximate; validate task quality.', counters:'Counts below are completed positions in this turn, not total FLOPs or latency.',
    active:'This step', ready:'Completed', waiting:'Pending', saved:'Long-lived', short:'Encoder · short-TTL checkpoint', discarded:'Decoder · not retained long-term',
    device:'GPU working set', backing:'Session cache', resident:'Local states ready', absent:'Not GPU-resident', missing:'Expired', localPending:'Local states pending',
    globalMetric:'Complete global records', deltaMetric:'Added this step', transferMetric:'Global data reloaded this turn',
    repairMetric:'Encoder window repair', decoderMetric:'Decoder prefill positions',
    reference:'Full-prefix reference', unit:'tokens', perLayer:'per layer', noRepair:'No checkpoint repair',
    metricNote:'Bytes count complete global KV and index K, including scales. SWA, partial pairs, activations, alignment and copy overhead are excluded. Reload assumes the GPU working set is released between turns; this is not disk IO or latency.',
    titleadmit:'Receive input and match the prefix', titleload:'Reload the matched global records', titlerestore:'Restore the valid Encoder checkpoint',
    titlerepair:'Replay the prefix tail to repair Encoder SWA', titleencodeInput:'Process new input and publish incremental records',
    titlebuildTail:'Build Decoder tail-local states', titleencodeToken:'Feed the current token into the Encoder', titledecodeToken:'Decoder writes, reads and completes this token',
    titlesave:'Retain the session and release the working set', titleexpire:'Local TTL expires; the Encoder checkpoint is lost',
    noteadmit:'Separate the matched prefix from the new suffix. The first turn has no prefix; later turns reference positions already processed in this session. The illustrative tool result adds 3 tokens, and the return adds 2.',
    noteload:'Restore saved compressed KV and index K into the GPU working set with their original record identities. Reads wait for completion. Tiered transport scheduling belongs in Radix HiCache and is not simulated here.',
    noterestore:'A short-gap continuation can restore the Encoder window checkpoint and associated compressor state. This avoids Encoder window repair; it does not make all computation for the turn disappear.',
    noterepair:'Recompute at most the final 128 prefix positions to recover local states. Cached compressed KV and index K are read-only: approximate replay must not overwrite them. Missing partial-pair state must also be recovered before appending.',
    noteencodeInput:'The suffix runs through the Encoder. L3, L9 and L15 publish one record per completed pair; an odd trailing position waits for its partner. Each source publishes before its consumers read, without per-consumer copies.',
    notebuildTail:'Use Encoder tail features to rebuild each Decoder layer’s SWA before generation. Old tail features may need reevaluation: a window-checkpoint hit does not imply those features were retained. This work is not assumed free; total FLOPs are not estimated.',
    noteencodeToken:'A sampled token enters its next forward pass. Encoder windows and three compressed sources update first; only a complete pair is published. The processed sequence position does not advance until the Decoder finishes.',
    notedecodeToken:'L21 builds the current global record from Encoder output. Later layers read it and update their own SWA, then produce logits for the next token. Positions leaving the local window can still remain in global compressed history.',
    notesave:'Keep complete global records long-term, optionally keep Encoder local states under a short TTL, and discard Decoder local states between requests. The retained prefix ends at the last completed forward pass, not at an unprocessed sampled token.',
    noteexpire:'Only the Encoder checkpoint expires; global history still hits. The next turn can repair local state from a bounded tail instead of treating the entire prefix as a cache miss. No production TTL duration is assumed.',
    inspect:'Inspecting', globalDetail:'Four owners store complete records. Each record has 288 B of main KV and 68 B of index K. Reads, reload and replay do not allocate duplicate records; incremental publication comes only from new positions.',
    localDetail:'The two windows represent separate per-layer states in the Encoder and Decoder, not two cross-layer shared caches. Each layer holds at most 128 positions in circular slots. Each cell holds one position; orange marks the newest, and endpoints identify the window.',
    archiveDetail:'Session identity, prefix position and global records determine the recovery point. A global hit does not imply local readiness. Reload, repair and suffix processing precede generation. A global miss requires full prefill and cannot be repaired by this trace.',
    back:'Follow current step', boundary:'Approximation and runtime boundary',
    boundaryNote:'Truncating local attention at the replay boundary is approximate, not numerically identical to full prefill. This scene uses the report’s 20+20 architecture view. In SGLang’s 2026-09-10 implementation, L21 stays on the full-input path; L22–L40 use tail-only computation per prefill chunk. This is a single-chunk, non-speculative state demonstration.',
    source:'Source: SGLang cache sharing and bounded replay', report:'DeepSeek report · §2.2 / §3.2',
  },
};
